### ISSUE TITLE
I would like to help with Italian translation

### ISSUE THREAD

**Issue by Gdtex** [olive-editor/olive#1034]
I trust in this project and I would like to help it as I can. I would like to translate new features in Italian. How could I do?

**Comment by RafaMartorell** [comment]
I made the translation into Spanish, which is already included in the branch 0.1 and from the team recommended me to follow the instructions on this page
https://github.com/olive-editor/olive/wiki/Translations
When using linux, mint in my case, I simply installed the recommended tools from synaptic and with the Qt Linguist application it was very easy to translate.
I am a simple collaborator, so my response is not official, I just try to help.

**Comment by MassiminoilTrace** [comment]
Hi! I'm the olive italian translator (i'm a volunteer as you).
For now I think there's not so much work to do; developers are cleaning the base of the software and parts of Olive are now broken.
I think we should wait for the next release.
You can contact me on github or by telegram, so we can talk in Italian and save time.
In order to find me on telegram, just ask in the olive telegram users group and I'll answer you.(or ask me on github).
Anyway, as rafaMartorell said, you just need Qt linguist.
In order to mantain translations consistent, I followed the guidelines of the Kde italian localization group and I made a phrasebook I can send you.
Thank you for your interest in the project! :)

**Comment by Gdtex** [comment]
> 
> 
> Hi! I'm the olive italian translator (i'm a volunteer as you). My contribution is in the 0.1 release too.
> For now I think there's not so much work to do; developers are cleaning the base of the software and parts of Olive are now broken.
> I think we should wait for the next release.
> You can contact me on github or by telegram, so we can talk in Italian and save time.
> In order to find me on telegram, just ask in the olive telegram users group and I'll answer you.(or ask me on github).
> Anyway, as rafaMartorell said, you just need Qt linguist.
> In order to mantain translations consistent, I followed the guidelines of the Kde italian localization group and I made a phrasebook I can send you.
> Thank you for your interest in the project! :)

What is the telegram group? I can't find it

**Comment by MassiminoilTrace** [comment]
It's a community group, here it is! https://t.me/joinchat/I4MhmRWpQ_sfwC4gJduzmg
