### ISSUE TITLE
[feature request] Extending clips past their length automatically loops them

### ISSUE THREAD

**Issue by maingi2** [olive-editor/olive#104]
Feature idea from the resident Vegas testerTM [feature request]

**Comment by maingi2** [comment]
Also, in Vegas, this particular feature's default setting is that each point in which the clip loops is a snap point

**Comment by frink** [comment]
If this is implemented it could cause frustration in many scenarios. It should be able to be turned off. Music video and dialog scenes are two examples where this sort of behavior may have unintended consequences. Even with wedding videos this could do some very bad things for business...

**Comment by main-gi** [comment]
...which scenarios? In Vegas it's a feature that's difficult to accidentally do. Right now trying to extend a clip past its length does nothing. Not opposed to making it a toggle of course but I have never messed up once using it. Especially with snap points allowing you to see/extend to the end of a single loop anyway. Also, looping music is the **most common** reason to have this feature.

**Comment by frink** [comment]
> ...which scenarios?

I presented two:

> Music video and dialog scenes are two examples where this sort of behavior may have unintended consequences. 

When we're talking about pro editors, they generally want to tell a story with their timeline sequence rather than looping a few clips like VJs. There are several great open source VJ software that loops by default and works very well. But the general movie and music video edits seldom loop a video clip directly even when they show it twice. For dialog, the editor often drags all the way to the end to make sure they didn't miss a word or glance that was awesome but off script.

I understand that looping would be cool. But the only scenario I can think of where it truly empowers someone is the VJ. NLEs aren't really the right tool for VJs anyway. So I'm left scratching my head on how this empowers our core target user base...

**Comment by main-gi** [comment]
By scenarios I meant "Is it really possible for someone paying attention (especially a professional) to mess up?" I used Sony Vegas (an NLE as well) when editing which loops this same way by default. There are snap points at the 1-loop end so you can drag to the end of a clip without trouble anyway. (When I edited frequently it wasn't really for VJ-type work.)

If you want use cases it's basically the same as any project where looping is relevant. I mean ultimately it is a 'glued' loop.
- Looping, extending music (likely the most common use)
- Short clips like a moving outro background, fire effects (this also applies for .gifs, which I am not sure if they are supported?)
- "Discussion" clips where audio is playing over limited video footage

It's a minor feature anyway, but was a very welcome convenience in Vegas.

**Comment by frink** [comment]
What if we had a property on the clip and the editor interface which changed modes for how one could edit. That way everyone can be happy and the pros can go back and forth between different modes.

- Fixed (Can't drag past the end or beginning - current behavior)
- Looped ( Vegas behavior that you described)
- Stretchy (time stretch the clip)

The playback rate could be governed by keyframes allowing more fine grained control of the stretching.

We could also add loop properties to the clip to add fine tuned adjustments for the loops startpoint, endpoint and clip offset so you don't have to start the loop from the beginning.

Modal editing is a common concept with many NLEs and DAWs. In fact, I wish Ardour would allow this sort of clip properties as well. There are plenty of times I want to loop something rather than copying the clip 20 times or whatever.

As long as the mode can be switch on and off I think this will work. After thinking a bit more I would say that the clips themselves would need to have these modes individually rather than just on the interface. But, it's an intriguing idea...

**Comment by Simran-B** [comment]
As a 4th option, it would be nice if the last frame of a video clip could be held until the container end.

This might also be useful for the beginning of a clip (still of the first frame between container start and clip beginning) for a fade in.

As a workaround, you can already save the first and the last frame as image and add them to the timeline on the respective sides.

Regarding looping, you could just duplicate the clip. To make it similarly fast as the dragging beyond the end of the clip, the default behavior would need to be that the active clip is duplicated and placed on the same track right after the active one, and then the new clip would need to become the active clip automatically. This way, you could simply hit the hotkey for duplication as often as you want to repeat the clip.

By default, it shouldn't be possible to extend a container beyond the clip boundaries. A modifier key (such as Alt) could be introduced to disable the boundary lock. Should multiple modes be added, then there should be a property you can set for each clip to pick the one you want. A customizable default setting should round it off.

**Comment by frink** [comment]
This is a great discussion. Really shows the diverse use cases needed for extending clips. @Simran-B hold frame is a usual case I've used most. But I've also needed looping at times. Creating and editing  looped clips are difficult. Are we doing something that is time locked or is the loop sequence more important than where subsequent loops lay in time? Different scenarios answer differently...
