### ISSUE TITLE
[Feature Request] Insert empty clip or color clips for titles

### ISSUE THREAD

**Issue by RafaMartorell** [olive-editor/olive#1055]
I think it would be very positive to have the possibility of inserting an empty clip to be able to use it to add titles with many more animation possibilities.
Basically it would be about inserting a completely empty and transparent .png image into which you could insert text effects.
This would be very useful in the project folder in the new -> Empty clip or Color clip

![Empty clip or color clip](https://user-images.githubusercontent.com/47257587/62886686-ebe6c380-bd3b-11e9-96e4-d46a8bb18168.png)

**Comment by dimitarsp** [comment]
Thus far, freecad is the only open-soruce video editing program that I know of that treats text like video clips instead of a filter. I find that much more powerful, easier to visualise and the create intricate layouts than having them as a filter (like in KDEnlive and Shotcut).

You can do that with a nested sequence. If you right-click on a bunch of clips together and click nest, it would become similar to what you are describing. I believe then that you should be able to create effects on the whole nested sequence in the main timeline.

**Comment by RafaMartorell** [comment]
Thank you very much, I don't know freecad.
Kdenlive has a good assistant to create titles, it may be one of the good things about this application, but its development team seems to be stuck in breaking the application so I looked for other free alternatives tired of errors (they release new versions where tools that work perfectly spoil or eliminate them and their solutions are very bad, but this is another issue that I do not want to go into details, kdenlive stopped liking)

For me the easiest way to create texts in Olive is to create a completely empty .png file that I use as a support clip. In this way I have much more control over the texts than if I insert them into a video clip.

To make animated backgrounds use some of the powerful tools such as SynfigStudio, Blender or Natron.

My recommendation is something as simple as being able to create an empty and transparent image file 100% from the editor itself. This would be as simple as an assistant to create an empty clip where only one window was opened for the dimensions of the same, even this same concept could be used to create color clips, that is, the assistant could be something like what I put in the following image:

![Empty clip or color clip](https://user-images.githubusercontent.com/47257587/62886686-ebe6c380-bd3b-11e9-96e4-d46a8bb18168.png)

You can tell me very correctly, do it yourself, but the problem is that I am an audiovisual technician and I don't know how to do it.

**Comment by sobotka** [comment]
Understanding the nuances of pixel management before randomly offering up good ideas would be really terrific. Also familiarity with nodal rendering pipelines help.

In particular, glyph rendering libraries is the first stop.

**Comment by RafaMartorell** [comment]
@sobotka 
I don't really know what you are telling me. I do not understand programming. I thought that my proposal is something simple for a person who does know how to program and it was with the intention of making the tool more complete. But just as Premiere is complemented by Photoshop and AfterEffects Olive can be complemented with Gimp, SynfigStucio, Blender and Natron.
Do you recommend that I close the proposal or leave it for developers to decide?

**Comment by sobotka** [comment]
Photoshop compliments other Adobe products, and as such, their toolset is crippled somewhat due to historical code.

The text element would be a single node, the position of the text would be another node, and so on. Each of those would be plausible to bundle into a node chain, but the interface and mechanics of how something works will be entirely _unlike_ the Adobe suite; the goal is to handle footage correctly, which Adobe doesn’t.

As such, it is worth familiarizing oneself with how a nodal compositor behaves to get a holistic idea of some of the UI issues and concerns. Fusion is probably one of the more reasonable pieces of software to try.

**Comment by RafaMartorell** [comment]
Thank you very much for your explanation.
I just like adobe after effects because it's simple and fast.
I like working with Nodes a lot, as in Blender or Natron (Nuke). And yes fusion is very powerful, although I have not worked with him but I know people who use it and recommend it.
Greetings
