### ISSUE TITLE
Variable bitrate / bitrate detection

### ISSUE THREAD

**Issue by maingi2** [olive-editor/olive#106]
Likely enhancement, maybe bug: I concatenated seven clips, all around 1-1.5 MB and exported the result. The exported file is 90 MB. After Handbrake (compression software) it becomes 8 MB.

The sequence was set to 360p preset when made and the export's height and width were set for a 360p video (just in case the issue is perhaps a render at 1080p or something, though I would think a 1080p video of 360p footage should be losslessly compressed down to a same sized 360p video anyway?)

The version is still the same one I was using on stream, in case this was fixed in the most recent commits.

**Comment by itsmattkc** [comment]
I have some questions about this one:

What was your export bitrate? Were you re-encoding in handbrake or just copying the codec data between formats? How long is the final concatenated video?

**Comment by maingi2** [comment]
Export bitrate was 2 (default)
I don't really know about that second question, sorry
The length is 4 minutes.

Since I deleted the original 6-part collection of videos, I redid this with a 4-part selection. Here's some images of what I did. (All the original videos are 24 FPS so that is why I picked 24 FPS as well this time.) https://i.imgur.com/tshAcmm.png

The output size is about 10x the size of the input.

**Comment by itsmattkc** [comment]
The resulting file size seems consistent with the video length and the bitrate. I believe the real issue is the default setting being 2Mbps CBR (somewhat overkill for 360p) with no available presets, automatic detection of a more suitable bit rate, or even an option for variable bit rate (which would likely decrease the file size significantly).

For now, feel free to lower the bit rate manually ([for 360p, YouTube recommends only 1Mbps](https://support.google.com/youtube/answer/1722171)), but until then I'll keep this issue open until the following is added:

- Variable bitrate support
- Auto-detection of suitable bitrate for project
- Quality presets (maybe)

**Comment by itsmattkc** [comment]
Added CRF support for H.264 in 4e57b1c26d8535220c60d348497a4758dc640faf that'll cover this for 95% of cases. Resulting file sizes are way smaller now.
