### ISSUE TITLE
[Feature Request] LUT - STABILIZER - SPECTROGRAM - SELECT A SPECIFIC COLOR - etc...

### ISSUE THREAD

**Issue by CodigoCristo** [olive-editor/olive#1099]
[SUGGESTION] 

1*-THE SPECTROGRAM MUST BE DISPLAYED WHEN THE AUDIO GAIN IS LOWERED

![image](https://user-images.githubusercontent.com/34531165/65833630-f4696e00-e297-11e9-9347-469c3230c03e.png)

2*-YOU MUST HAVE A DROPPER TO SELECT A SPECIFIC COLOR - A dropper

![image](https://user-images.githubusercontent.com/34531165/65833551-23cbab00-e297-11e9-888e-f7209bb0e612.png)

They could use this method that they use in gimp

![image](https://user-images.githubusercontent.com/34531165/65834296-2af6b700-e29f-11e9-9064-80587f30c0ef.png)

3*-ADD CLUT .CUBE IN THE COLOR CORRECTION EFFECT
kdenlive reference
![image](https://user-images.githubusercontent.com/34531165/65833655-1d89fe80-e298-11e9-88a9-6c7ca1887c3e.png)
LUT file...
Interpolation Mode...

No Lut
![image](https://user-images.githubusercontent.com/34531165/65833673-47432580-e298-11e9-87f0-f0d3f8f1bb63.png)

yes Lut
![image](https://user-images.githubusercontent.com/34531165/65833682-57f39b80-e298-11e9-9bd1-a8e060056c56.png)

File CLUT
![image](https://user-images.githubusercontent.com/34531165/65833685-69d53e80-e298-11e9-858b-56db2d7bed76.png)

4***-When putting slow motion in several clips a problem is generated, it takes a long time to do the slow motion process to each of the clips**

https://youtu.be/fY4cXwNpEP4

5*-What I do is reduce the dimensions of my timeline to have better performance, but they should add an option to auto scale

![image](https://user-images.githubusercontent.com/34531165/65833946-98084d80-e29b-11e9-864d-ffb3f1a5f4a8.png)

Because then I have to reset each individual clip to fit the sequence change

![image](https://user-images.githubusercontent.com/34531165/65833948-a0608880-e29b-11e9-8bf2-ecc645d4fd47.png)

6*-AND THE MOST IMPORTANT, A VIDEO STABILIZER IN OLIVE EDITOR...
https://www.youtube.com/embed/7Nf4bI_5hgI
https://ai.googleblog.com/2012/05/video-stabilization-on-youtube.html

7*-TEXT, MASK and Video quality
Similar to cropping option
![image](https://user-images.githubusercontent.com/34531165/65833744-16afbb80-e299-11e9-8f6b-0cc2beb582f8.png)

.Edit text directly on screen
.Video quality  1/2 1/4 1/8 
![image](https://user-images.githubusercontent.com/34531165/65833760-3810a780-e299-11e9-91f4-aa03f8ae890f.png)

I hope you don't put aside these options
I edit videos of events and the truth I just need, cut, slow motion and colorize

**Comment by CodigoCristo** [comment]
/*And the button to restore the overall effects settings

![image](https://user-images.githubusercontent.com/34531165/65834245-c0457b80-e29e-11e9-8048-f3f7d04619fd.png)

**Comment by AGI-THB** [comment]
You try to be helpful, but at the moment you are the exact opposite...
The problem is that most of these request have already been suggested and disussed in other tickets and now you started another ticket which makes it even harder to keep track of which requests have been discussed and implementes and which not.

Use the search function!

Also: Having multiple requests / suggestions per ticket is bad!
Use one suggestion / request per ticket! (After using the search function!)

videostabilizor:
#190 

Luts have been discussed:
#590 

mask effect has been discussed:
#121 

quality multipliers are here:
#1075 

text has been discusses in other tickets as well:
#841 
#1054 
#783 

spectrogramm (audio) :
#1058
