### ISSUE TITLE
Subtitle Support

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#124]
Plans for this involve a separate section of the timeline (hidden by default) that allows for editing SRT files. Mostly UI stuff, otherwise likely fairly simple to implement.

**Comment by goldenbait** [comment]
I would look to Davinci Resolve and not Premiere Pro for inspiration on this. They have a dedicated subtitle track that is always on top, in stead of a caption clip. This separates subtitles from video editing while having them in the same visual space.

Don't know if you plan on implementing an option to burn subtitles into the video yet, but here are my thoughts on that.

When burning in subtitles you want control over style, and this is where I feel Premiere fails. They don't have a master style controlling all subtitles, which means you have to select all subtitles to change the style. This is bad, as you would have to manually deselect subtitles that needs to differ from the master style. With a master style you can always change the master style without selecting or deselecting anything.

**Comment by Symbian9** [comment]
It would be cool start solving this task by adding "Import Subtitle" for import existed `.srt` or `.aas` files.

**Comment by elsandosgrande** [comment]
Could you also include support for .scc, since that's YouTube's preferred format?

**Comment by frink** [comment]
The positional aspect of subtitles makes this a messy issue unless you are talking about the closed caption editing. In that case, there are several more sole purposed cross platform closed caption editors that will do what is needed. In a professional use case you will seldom have the video editor working on captioning so using a different software at a different point in the workflow is probably preferable...

**Comment by goldenbait** [comment]
I must disagree with you @frink 

In the freelance world you can often find yourself doing everything on smaller projects. Honestly I do subtitles in about 70% of my commercial work, and having it in the same software is a lifesaver, especially when it´s burnt into the video at the end. The bad subtitling features in Premiere Pro is actually the biggest reason why I left Premiere Pro behind. It is a must for some of us.

**Comment by oc1024** [comment]
One thing I'd like to see implemented alongside this subtitle editor is a side panel with a dinamically generated preview of the final waveform.

It's one the features I like the most about Subtitle Composer, and the reason why I prefer it over all other Linux subtitle editing software.

**Comment by frink** [comment]
@goldenbait - What do you mean by subtitle editor? Are you talking about Closed Caption editing? Or are you talking about title sequences or onscreen translation subtitles when you are shooting in multiple languages? Subtitles mean too many things to too many people...

@oc1024 An audio waveform scope of final audio could be helpful. There are many different types of graphs that audio editors use to verify their work. If we are going to support the waveform viewer it will be need to display in several different formats...

Also, thanks for injecting Subtitle Composer into the conversation. That was one of the subtitle editors I was talking about which do one thing quite well as you have eloquently pointed out...

**Comment by goldenbait** [comment]
@frink I didn't mention a subtitle editor, oc1024 did.

But what I was talking about is subtitle creation or import (as a .srt for example), editing, and being able to apply a style as you can on titles so that you can embed them into the final export if you choose. Davinci Resolve has a really slick solution, check that out, that's essentially what I mean.

**Comment by frink** [comment]
**I'll have to take a look at DR and see what you're talking about...**
Normally, I think of subtitling (closed captioning) as a completely separate process from editing that should not be done until the edit is finalized. However, if the final release is going to put translations then I can see where subtitling might be important to the overall edit of the film.

**The whole idea of compositing text into video is a nightmare!**
You have to think about so many screen resolutions and readability concerns. Credits are a real pain also:  weeks in After Effects to get all the names right...  Would love to see an easier way. (Although to be fair, AE makes it about as painless as I can imagine...)

**All that to say:** I'm dense but you've won me over to the importance of including subtitling in the editor... Esp. for foreign and multi-language films. Text and video should never meet. Terrible combination. Hard hard hard to get right!

**Comment by goldenbait** [comment]
Glad I got my point across. Obviously a separate process and workflow is optimal, but not every project can afford that luxury. And not every project that needs subtitles will be played on a platform that supports rendering subtitles. And for beginners a simple workflow for simple subtitling without messing about with a hundred titles is gold.

I totally agree, it's often a nightmare. I especially hate accurately rendering scrolling credits, to not get ugly jittery movement you have to get it to move on whole pixels, and that means expressions in After Effects. Not very intuitive.

It's totally worth attempting, a great text and subtitle workflow can set Olive apart from the rest. I already quite like the titles in it.

**Comment by oc1024** [comment]
> subtitle creation
> I didn't mention a subtitle editor

How would we create them, then?

> subtitle import

I can think of two ways:
* Show SRTs on import dialog
* If user imports an SRT:
 * A special, configurable Subtitle Clip is created. Instead of Audio Effects, one can see: Subtitle Options, basically for text settings. I can see this being the better option if we are gonna bundle a subtitle editor: importing, editing and exporting subtitle would be done through these subtitle clips.
 * The user is shown an "Import Options" dialog where he can set text options. Then a sequence made of properly timed text clips is generated. It can be edited just like any other sequence. Text is offset with Transform. However this would be a one way process with no editing and no exporting back of subtitles (unless through hackish stuff).

**Comment by frink** [comment]
Since this is an editor it's my feeling that anything that we import be editable either in an external editor or in an internal editor. @goldenbait has made some very good points about rendered subtitles - which are a pain everywhere. I still think the right way to do this is importing entered subtitles from somewhere else. But we also need to consider credits and wrangle the compositing necessary to accomplish things there.

One of the hardest things to do in projects seeking to be usable by pros is limit the scope of the project. With Olive I think it's important that we get the workflow right before we build every editable feature into the system or else it will become rigidly wrong and unusable for many cases like so many editors that we have mentioned with our mix of adoration and loathing.

I would suggest generic import of various types of media to the timeline with specific external editors configurable in settings. A large SVG, PNG or JPG scrolled over a period of time can work well as the end credits problem that we mentioned. Composited text is necessary for many opening credit scenes. There is always going to be some inventive way to screw up opening credits so I suggest we don't concern ourselves too much there...

As far as overlay settings choosing fonts etc for subtitles like the translation scenario I mentioned earlier and the rendering problems mentioned by @goldenbait, I'd say the simple and probably right solution is to have an SRT populate a text tag in an SVG overlay to be rendered. This should allow for most opening credits and also translation sub text displayed on screen. Depending on the SVG library used you may even be able to render CSS animations for the SVG and possibly embedded scripting allowing for complex overlay possibilities.

SVG keeps everything raster until the final render allowing for crisp composition under most conditions and many variation of possibilities. The only thing I would suggest is to use the SVG as a template and the SRT as the dataset that populates the template. If you go this route you will want an SVG library that plays nice and allows transparency, shadows and clipping quite well. You will also want to allow multiple placeholders  for text as well. One way to deal with these SVGs to animate placement may be to allow other int and float values to be inserted into the template through our keyframe animations that we already have working beautifully...

That's the simplest approach I can think of allowing the most diverse flexibility for almost every edge case where you would use text...

**Comment by chenlung** [comment]
I use [Subtitle Horse](https://subtitle-horse.com) to produce subtitle scripts.

There are many formats, but import and export support of the following would be ideal (some are frame-based, millisecond, or both):
- SRT
- WebVTT
- STL (Spruce Technologies)
- iTT
- SMPTE-TT

I'm happy to privately provide short samples of all these (including a video) for testing.

- I’m interested in softcoded and hardcoded subtitles.
- Olive could serve as a frame-accurate subtitle editor itself (similar to the functionality of Final Cut Pro and Premiere Pro), offering features such as validation.
