### ISSUE TITLE
[RENDER]  PNG images don't render

### ISSUE THREAD

**Issue by Electrice** [olive-editor/olive#1282]
**Commit Hash** 
5f5d6e82

**Platform**
Windows 10

**Summary**
PNG images render black

**Additional Information / Output**
![image](https://user-images.githubusercontent.com/58629417/97284359-5425a600-1817-11eb-851b-4076094669a0.png)

**Comment by Simran-B** [comment]
While I found a OpenGL driver crash (#1284) when testing with a specific PNG file, I was not able to reproduce your problem with other PNGs. They show in the footage as well as sequence viewer as expected.

Can you reproduce the problem with other PNG files? Can you share one which exhibits the issue? (Please zip the file before uploading it here, so that we can be sure that GitHub doesn't modify the image)

**Comment by Electrice** [comment]
> 
> 
> While I found a OpenGL driver crash (#1284) when testing with a specific PNG file, I was not able to reproduce your problem with other PNGs. They show in the footage as well as sequence viewer as expected.
> 
> Can you reproduce the problem with other PNG files? Can you share one which exhibits the issue? (Please zip the file before uploading it here, so that we can be sure that GitHub doesn't modify the image)

I've tested 6 different PNG's with the same result in a fresh project, and all do not display.
![image](https://user-images.githubusercontent.com/58629417/97305599-b391af00-1833-11eb-9742-dbabca6156ea.png)

**Comment by Electrice** [comment]
Oh, and Olive crashed while trying to close that project.
![image](https://user-images.githubusercontent.com/58629417/97305899-14b98280-1834-11eb-80cd-f53b6cd07b81.png)

**Comment by sobotka** [comment]
Don’t append different reports. Report a separate issue.

**Comment by itsmattkc** [comment]
This was fixed yesteday in 1e6208517fe621119f8bed838a4bae2652907f60
