### ISSUE TITLE
[CRASH] OCIO doesn't support unicode paths on Windows

### ISSUE THREAD

**Issue by AlexKiryanov** [olive-editor/olive#1287]
Win 10 64 bit

Good afternoon! I installed the program from the official site today.
Version: 379a799a (Oct 27 2020 4:37:21)
I launch the shortcut. little black field. Then it disappears and nothing happens. There is no execution of this program in the task manager either. The video is attached here. https://drive.google.com/file/d/1-vV4InwxnTZFKP-NYM8-y4LOApLFwSVo/view?usp=sharing
Thank you very much!

**Comment by Simran-B** [comment]
Can you start it from a terminal so that the log stays visible after Olive's termination?

Please provide details about your hardware, especially GPU and its driver.

**Comment by itsmattkc** [comment]
Does 59241f9023803d886c4a4d61887911a2c8bc9776 fix this?

**Comment by AlexKiryanov** [comment]
Good evening again! I have intel 3840km nvidia 1070, win 10 64 to be a video card driver 26.21.14.4166
![2020-10-28 17-15-34 (0-00-04-07)](https://user-images.githubusercontent.com/65244629/97453491-d8c31200-1946-11eb-8289-cf68c0acb8f3.jpg)
I downloaded version 0.1, it starts without problems) 
![2](https://user-images.githubusercontent.com/65244629/97454301-a665e480-1947-11eb-9d7d-1f0400b8ad06.jpg)

**Comment by Simran-B** [comment]
The top one from the nightly page: https://olivevideoeditor.org/nightly.php

**Comment by AlexKiryanov** [comment]
Good afternoon! I downloaded this version Olive-34cb7c96-Windows-x86_64 and it also does not start ...
But version 0.1 works great! I'll work on it for now! Thank you very much!

**Comment by AlexKiryanov** [comment]
Good afternoon! Again! For the purity of the experiment, I tried to run the same version (Olive-34cb7c96-Windows-x86_64) on another computer. The result is the same. Dell Inspiron n5110 2860qm gt 525m 16 GB RAM

**Comment by itsmattkc** [comment]
I'd like to address this bug regardless, I see occasional crash reports so this definitely affects more than just you.

The issue seems to be OCIO locale related. OCIO appears to have issues with non-C locale which requires special handling on our end to set C locale when interfacing with it. However, something must be wrong in our handling, as you can see in the OP's screenshot/video, their username has been garbled to a random mess of symbols, and with a garbled filename OCIO is throwing an exception trying to load the config.

Unfortunately I don't have a non-Latin language setup to properly troubleshoot this with, but I may be able to simulate it with a non-Latin filename of some kind.

**Comment by AlexKiryanov** [comment]
And the problem is in the Russian path in the files (more precisely, in the Russian characters in the username)? then what is my Russian Windows? I do not want to bother you with this trifle now) Since version 0.1 works, and that's enough for now.)) thanks!

**Comment by itsmattkc** [comment]
Well, the culprit is AcademySoftwareFoundation/OpenColorIO#406, or more specifically it's because `std::ifstream` has no inherent Unicode support in the C++ standard.

This isn't a problem for macOS because all strings are UTF-8 anyway, so a UTF-8 path correctly matches despite the fact that C++ doesn't require them to. It's probably much the same on Linux if the locale is set to UTF-8.

On Windows, MSVC provides an override of `std::ifstream` that takes a `wchar_t` string (UTF-16), this is probably the intended way of using Unicode paths on Windows. I'm not sure if that helps OCIO here, or if they'd be interested in something like that, but that's probably what has to be done to fix this issue for good.

On our end, we might be forced to use a path that's guaranteed to be ASCII (something like `C:\ocioconf`).

**Comment by itsmattkc** [comment]
I have submitted a PR to OpenColorIO to fix this here: AcademySoftwareFoundation/opencolorio#1363

**Comment by itsmattkc** [comment]
While the above PR hasn't been merged yet, this fix has been merged into our build system so it should no longer be an issue

**Comment by AlexKiryanov** [comment]
Thanks you very much))) this is great news!!

вс, 11 апр. 2021 г., 16:35 itsmattkc ***@***.***>:
