### ISSUE TITLE
Installation issue with Win 10

### ISSUE THREAD

**Issue by jss9h** [olive-editor/olive#1288]
Love the tutorials on YouTube, so I wanted to try the program. I have tried to install the latest version of Olive on 2 different Win10 machines (desktop & laptop) & both report that the download is blocked as "potentially harmful". I have been able to install the earlier version without this issue (last weekend). I am guessing the ever-increasing security in Windows is responsible. How do I stop WIndows blocking the file so that I can install it?  Thanks

**Comment by magdesign** [comment]
maybe this helps as a current workaround:
 https://support.microsoft.com/en-us/windows/protect-your-pc-from-potentially-unwanted-applications-c7668a25-174e-3b78-0191-faf0607f7a6e

**Comment by itsmattkc** [comment]
I assume you're getting an error like this:

![image](https://user-images.githubusercontent.com/34096995/97465763-7eea3880-1996-11eb-9515-0acc8ef949d5.png)

If you click "More Info", there will be a button that says "Run Anyway".

There's not much we can do about this I'm afraid. While Windows will choose to trust files that are downloaded "often", because our builds are nightly, they change all the time so they reset that "trust" factor. What we _should_ do is acquire a Microsoft certificate that we sign with so that Windows will always trust our executables, but that costs us money that we simply don't have at the moment.
