### ISSUE TITLE
[BUILD] Ubuntu 18.04 package install problem

### ISSUE THREAD

**Issue by gandsnut** [olive-editor/olive#1292]
**Commit Hash** 

**Platform**
Linux xxxxxx 5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Summary**
Original install of Olive Editor early 2020 with a 'Launchpad...' PPA began throwing errors in Synaptic when repositories rescanned (SEE ATTACHED).  Removed that PPA and followed the following commands from Olive Editor website::

sudo add-apt-repository ppa:olive-editor/olive-editor

(from https://olivevideoeditor.org/linux.php) produces:

xxxxxxxx@xxxxx:~$ sudo add-apt-repository ppa:olive-editor/olive-editor
[sudo] password for gandsnut: 

Cannot add PPA: 'ppa:~olive-editor/ubuntu/olive-editor'.
The team named '~olive-editor' has no PPA named 'ubuntu/olive-editor'
Please choose from the following available PPAs:

**Additional Information / Output**
![olive_repository_problem](https://user-images.githubusercontent.com/29338195/97572843-dd271380-19b6-11eb-8f8c-fad6d5957cf2.png)

**Comment by elsandosgrande** [comment]
@gandsnut That PPA was not made by Matthew (`olive-team`), which is why you're getting that error. It was made by some person who we have never had contact with and who is **not** affiliated with the project in any way (the following image shows who is the maintainer of the package in Ubuntu's repositories for Groovy and Focal, as the link seen in your image results in a “**Forbidden**” message): 
![image](https://user-images.githubusercontent.com/40576902/97578594-52afd580-19f1-11eb-8901-33c5c52d6033.png)

You need to either use the AppImage, which is available on the website linked to in the README, or you need to manually build Olive, for which exists a guide on the website as well.

**Comment by Simran-B** [comment]
Closing, as this is unsupported.

Find the CI AppImage builds on the website: https://olivevideoeditor.org/download.php
