### ISSUE TITLE
[UI] Everything feels backwards and completely unusable

### ISSUE THREAD

**Issue by alkaris2** [olive-editor/olive#1303]
**Commit Hash**

de48eba7

**Platform**

Manjaro
- - -

**Summary**

Everything about this editor now feels completely backwards and unusable. I've compared difference between April 2019 Alpha release and AppImage release `de48eba7` and they both feel completely different. The April 2019 Alpha (0ac9dd9) release feels more usable than the AppImage release. It's like you nerfed usability of being able to edit videos in a way that makes any sense at all.

This for example, the color picker makes absolutely no sense at all. You can't even input standard RGB numbers, and you can't even enter Hex Code for a particular color, or even drag and drop a color into it.
![image](https://user-images.githubusercontent.com/73155407/98046898-f1698580-1e7a-11eb-8760-23e892d589cc.png)

Compare the above with the April 2019 Alpha release here:

![image](https://user-images.githubusercontent.com/73155407/98047021-270e6e80-1e7b-11eb-9694-397834aeba43.png)

At least THAT made more sense. Sure add a color wheel, but at least make it properly usable by being able to input standard RGB values and Hex Code values

and now lets take a look at when trying to add images to a scene. There's no ability to resize or modify the image in any way.

![image](https://user-images.githubusercontent.com/73155407/98047228-810f3400-1e7b-11eb-85bb-79d055afd9ae.png)

and again compare to April 2019 Alpha release

![image](https://user-images.githubusercontent.com/73155407/98047286-96845e00-1e7b-11eb-80d7-0ee22f69e37f.png)

This is more usable than the other as shown above, and has everything you would expect from a video editor. Everything so far in these newer nightly releases just seems like you walked back everything you've ever done right in previous build releases, and I'm beginning to doubt whether if Olive will be a viable usable video editor in future.

- - -

**Additional Information / Output**

Please be sure to add UI Scaling, and add standard RGB value inputs and Hex Code values.

**Comment by Simran-B** [comment]
Not a bug, see #1175. This is all by design, which is still incomplete and not implemented as desired. It will certainly become more intuitive/efficient eventually. But overall this is where Olive is heading. Node compositing and color management are integral parts of the rewrite. Hex values don't make much sense in a color managed pipeline. If you look for a free, hobby-grade, more complete video editor please use KDenlive, iMovie, DaVinci Resolve or the like.

**Comment by sobotka** [comment]
Be clueless, win clueless prizes.

**Comment by itsmattkc** [comment]
> You can't even input standard RGB numbers, and you can't even enter Hex Code for a particular color, or even drag and drop a color into it.

What you refer to as "standard RGB numbers" and "hex codes" is the old 8bpc system of digital color. I acknowledge these are more familiar to you, but that system is old, limited, and flawed, and the future is higher bit depths and floating point color like what Olive uses in 0.2. I encourage you to learn how these work since you'll probably see more applications shift to them over time (particularly higher end graphics applications like Olive).

> and now lets take a look at when trying to add images to a scene. There's no ability to resize or modify the image in any way.

While node interaction certainly has a long way to go, it is possible to transform images (check the [Quickstart for help](https://github.com/olive-editor/olive/wiki/Olive-0.2.x-Quickstart)) and while it's a little cumbersome at the moment, we absolutely intend to make this easier to do.

My suggestion is to keep in mind that just because something is familiar doesn't mean it's correct, and likewise just because something is unfamiliar doesn't mean it's wrong. Also Olive is still heavily in development. A good majority of software (particularly commercial software) doesn't let you know anything about software in development, let alone use and test it yourself.

**Comment by Avispa** [comment]
> Hex values don't make much sense in a color managed pipeline. If you look for a free, hobby-grade, more complete video editor please use KDenlive, iMovie, DaVinci Resolve or the like.

Apparently to him it does make more sense, and even though I just trust you that the new way is the "correct" way I can understand him.

> What you refer to as "standard RGB numbers" and "hex codes" is the old 8bpc system of digital color. I acknowledge these are more familiar to you, but that system is old, limited, and flawed, and the future is higher bit depths and floating point color like what Olive uses in 0.2

I have no background but why you wanna ditch the average joe because of an "HTML"/RGB/Hex input field? Are they colour spaces incompatible to each other? Without any deep knowledge about it I'm pretty confident that 24bit/8bpc fits into 10 bpc as much as 16 bit fits into 24 bit colour range. Already on 24 bit colour space, if I need a grey I usually end up with `#999999`, which would easily fit into 4 bit? Not clue; anyway, my point is if he/she/whoever is happy with a "flawed" 16 colour pallet from the '90s why force somebody to *the* new thing or even another program? I further assume a text/hex field with a function to convert 8 bpc to 10 bpc floating point is no big hassle nor will need any later maintenance. Maybe give it a second thought and 30 minutes of implementation?

**Comment by sobotka** [comment]
The best way to lead someone to see why this historical madness is madness is to simply walk through meaning.

> I have no background but why you wanna ditch the average joe because of an "HTML"/RGB/Hex input field?

What does a hex code mean?

> Are they colour spaces incompatible to each other?

What is a colour space?

> Maybe give it a second thought and 30 minutes of implementation?

Not a chance. Better to educate.
