### ISSUE TITLE
[UI] Olive Icon doesn't show up on Ubuntu's taskbar with AppImage

### ISSUE THREAD

**Issue by yasharya2901** [olive-editor/olive#1317]
**Commit Hash** 
c69b63dc

**Platform** 
Ubuntu 20.04
Linux 5.4.0-52-generic

**Summary**
In the taskbar, the Olive doesn't show it's logo like others.

**Additional Information / Output**
![Screenshot from 2020-11-10 17-18-36](https://user-images.githubusercontent.com/36362019/98670602-ef229200-2378-11eb-80a6-681a6ce7c04f.png)

**Comment by itsmattkc** [comment]
This is a limitation of Linux. No application has an icon unless it's registered in the operating system as a desktop entry (icons can't just be attached to executables like they can in Windows and macOS). Registering it as a desktop entry doesn't make sense to do since AppImages aren't "installed".

Most (if not all) AppImages have no icon: AppImage/AppImageKit#346

**Comment by yasharya2901** [comment]
But Synfig Studio is the app that does have the icon and it also appears in the launcher.

**Comment by yasharya2901** [comment]
> But Synfig Studio is the app that does have the icon and it also appears in the launcher.

Plus, it also has appimage only.

**Comment by Simran-B** [comment]
> This functionality was available as part of runtime.c for type 1 AppImages but it was a dirty hack not fully implementing the thumbnail spec and has been removed in favor of the optional appimaged daemon. 

Does it use a type 1 AppImage by any chance?

**Comment by yasharya2901** [comment]
Then why don't you make a Deb or rpm file which is the easiest to install and update?

**Comment by Simran-B** [comment]
Because it's an avoidable maintenance burden. AppImages are easy to create and you create exactly one per version, which will run on almost every distro. How much simpler can it be than to download an AppImage and run it? There's no point in wasting valuable time in compiling for a variety of distros and create specific packages for software in an early alpha stage.

**Comment by gnolooo** [comment]
I may be very late, but I was facing the same problem and I found the solution online: what you actually need to do is to add the `StartupWMClass` entry to the .desktop file, putting as argument olive-editor.
You can actually find what to put there using the command `xprop | grep WM_CLASS`.
Hope this helps.
