### ISSUE TITLE
[EDIT] Clip length does not change despite changing speed

### ISSUE THREAD

**Issue by lowlevelm** [olive-editor/olive#1389]
**Commit Hash**
0.2.0 6eade26b

**Platform**
Manjaro Linux 20.2

**Summary**
Clip length does not change despite changing speed.
So I change the speed to 200x, and the clip will freeze-frame at the half way mark.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Not a bug. The idea is that speed will be keyframable (eventually) and not necessarily be tied to the timeline.

**Comment by Simran-B** [comment]
Sounds like a UX issue. Clips are just containers. Changing its content doesn't change the length, which is desirable in most cases. For constant speed adjustment, an option could be added to adjust the container length using the inverted speed factor perhaps, but it will most likely be incompatible with keyframeable speed.

**Comment by itsmattkc** [comment]
Yeah, that's how 0.1 worked (and ~incidentally~ how Premiere works), so that's probably where the confusion comes from. I feel like that's a much less flexible paradigm though and it would be confusing to two speed systems.

To have the functionality though, we might be able to add a multiplier field to the "set duration" dialog

**Comment by Simran-B** [comment]
Instead or in addition to that, an action to align the container boundaries to the footage begin and end might be helpful. For example, if the container is longer than the medium (with speed adjustments taken into account), it would set the clip end so that the last frame is not repeated. Same for the beginning of the footage.

Alternatively or on top of that, the container could snap to that point when snapping is enabled.

**Comment by lowlevelm** [comment]
The duration of the "container" could be a lighter shade, and the duration of the medium could be a darker shade so it is easy to tell where the actual video ends.
