### ISSUE TITLE
[PLAYBACK] No sound at all

### ISSUE THREAD

**Issue by thamiresklein** [olive-editor/olive#1396]
**Commit Hash** 

**Platform** 

windows 7

**Summary**

**Additional Information / Output**

My videos don`t produce any sound inside the program, but they have sounds. When I import it they go mute...

**Comment by elsandosgrande** [comment]
@thamiresklein 
1. Which version of Olive are you using? Provide the commit hash of your build (the eight-digit alphanumerical string in the title bar).
2. Are you saying that the audio is not being exported? Could you provide us with more details, like which types of footage you are using for example?

**Comment by sobotka** [comment]
If you can’t spend the time to properly document and issue, don’t post the issue and waste other people’s time.

**Comment by thamiresklein** [comment]
Oh it was midnight when I posted it... Didn't know was going to be answered so quicly... So here I go, My oliver is Alpha 1ecf533.
When I import the video the audio just doesn`t play. It has the soundtrack with the waves shown, but when I play it, it goes mute. I didn't change anything on the preferences, just clicked and dragged to the bar to edit, and the video plays with no problem, but the audio seems not be there.

I recorded a video with OBS, and I think I don't see the command prompt, but I didn't see any warnings....

I use windows and I really am a dummy with commands and everything...

**Comment by elsandosgrande** [comment]
@thamiresklein 
1. You open Command Prompt manually and then manually run `olive-editor` from it. It's the same logic as with macOS and Linux terminals.
2. That is version 0.1, which has been deprecated. You can try to see if anybody in the community Discord server has any workarounds, but that lineage is no longer being developed, as Razor (0.2) is practically a complete rewrite of Olive. I'd suggest giving Razor a shot. If you _need_ to finish your video project, then you'd be better off trying KDEnlive, DaVinci Resolve (it's free, Resolve Studio is paid), and others, since they, unlike Olive, aren't in alpha.

**Comment by thamiresklein** [comment]
oh! Got it! I will wait for the new one... I don't follow the releases.... my bad =)
