### ISSUE TITLE
[COLOR] Transform node clips hilights on V-log footage

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#1475]
**Commit Hash** 

1cd07bc1

**Platform** 

Manjaro Linux 64.-bit

**Summary**

It seems that the Transform node is clamping color information between values 0 and 1.

Lowering exposure before the Transform node gives expected results, but doing so after the Transform node exposes clipped hilights.

Here's how my footage looks on Waveform after import when leaving the input color space as sRGB OETF:

![image](https://user-images.githubusercontent.com/491704/106157421-fa6ca900-6182-11eb-999c-c02808297f0e.png)

Note the hilights at level 0.8.

Now after I select Panasonic V-Log V-Gamut:

![image](https://user-images.githubusercontent.com/491704/106157575-27b95700-6183-11eb-9de1-6ef4a8126e02.png)

Note the hilights went above 1.0 - it's fie though, since we're working in 16/32-bit float internally, right?
Not if you try to reduce exposure after the Transform node:

![image](https://user-images.githubusercontent.com/491704/106157706-44ee2580-6183-11eb-943d-bc1447628108.png)

Note the clipped hilights at exactly 0.5 (I've used math multiply with 0.5).

Here's the node setup:
![image](https://user-images.githubusercontent.com/491704/106157948-8088ef80-6183-11eb-9c5c-b3efaa0235f7.png)

And here's how it looks if Math is applied **before** Transform:

![image](https://user-images.githubusercontent.com/491704/106158033-972f4680-6183-11eb-8193-e2c09057189b.png)

Note the hilights still reach above 1.0 - they were not clipped!

**Additional Information / Output**

How to reproduce:

1. Import V-log footage and set it's input color space accordingly (could be any footage, the problem
2. Add Math node **after** the Transform node
3. Se the Math node to multiply and dial in 0.5 value
4. Check the waveform and see the clipped highlights
5. If need be, add another multiply node **before** the Transform node and set it to Multiply x 2 or huigher in order to produce clipping.

**Comment by itsmattkc** [comment]
Ahh, this is actually a known issue. The multiply is affecting the video's alpha channel as well as its RGB channels, reducing the overall opacity of the video and resulting in what looks like clipping.

Before the "Transform", Olive recognizes your footage has no alpha and therefore no alpha channel is affected. But the "Transform" node will add an alpha channel, since your transformation might result in it no longer covering the entire viewport. Since the "math" node affects all channels equally, the result will be an "opacity" effect rather than an "exposure" effect.

We've had plans to implement UI allowing users to select the channels that a node affects for a long time, but haven't gotten to a point of implementing it. Probably best to track this in #1366 and I'll merge this into that issue.
