### ISSUE TITLE
[BUILD] Build v0.1.2 for Windows since it is already marked "verified"?

### ISSUE THREAD

**Issue by Avispa** [olive-editor/olive#1509]
### Preamble / Warning
After researching a little and typing the whole issue/text I got uncertain if Travis CI is related to the process of generating the builds for _Windows_. (I can only see little Linux and Mac Icons.) Anyhow maybe you wanna solve the found (simple) issue nevertheless. ;-) So maybe this issue here should be split into two. Nevertheless the main point/request remains.

### Summary
Latest binary for _Windows_ for the legacy v0.1.x  branch is v0.1.0 *despite* the fact the _**latest release**_ is or should be v0.1.1 and latest _**verified**_ "pre-release" is v0.1.2.

Can anybody of the Devs please tell Mr. Travis to build v0.1.2 for _Windows_? From what I can read by skimming through the list of issues on _Github_ all problems with the Travis stack seem to be fixed and or at least no issues are open.

### Travis output
While having zero inside into the build stack or underlying system I had a look into the log anyway. It appears to me that just the public PGP/GPG key of _"J Fernyhough"_ for _Launchpad PPA_ is not present hence "something" cannot updated and everything from here on breaks subsequently.

#### Sidenote
Further guessing: the reason that v0.1.0 is compiling correctly is that the needed dependencies are already present on the system/cache therefore an update isn't needed subsequently the build doesn't break.

<details><summary><strong>Excerpt Travis Log</strong></summary><pre><code>
Cannot add PPA: 'ppa:jonathonf/ffmpeg-3'.
Please check that the PPA name or format is correct.
gpg: keyring `/tmp/tmpc_1ivsxn/secring.gpg' created
gpg: keyring `/tmp/tmpc_1ivsxn/pubring.gpg' created
gpg: requesting key F06FC659 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpc_1ivsxn/trustdb.gpg: trustdb created
gpg: key F06FC659: public key "Launchpad PPA for J Fernyhough" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
W: GPG error: http://dl.google.com/linux/chrome/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78BD65473CB3BD13
W: The repository 'http://dl.google.com/linux/chrome/deb stable InRelease' is not signed.
W: There is no public key available for the following key IDs:
78BD65473CB3BD13  
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
W: The repository 'http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu trusty Release' does not have a Release file.
W: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/trusty/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
E: Failed to fetch http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found
W: Some index files failed to download. They have been ignored, or old ones used instead.
The command "source ./.travis/before_install.sh" failed and exited with 100 during .
Your build has been stopped.
</code></pre></details>

Source: [https://travis-ci.org/github/olive-editor/olive/jobs/687048680](https://travis-ci.org/github/olive-editor/olive/jobs/687048680)

I would assume this should be an easy fix and as long as the v0.2.x branch is horrible slow or simply crashing: to have at least v0.1.2 on _Windows_ would be an advancement. Especially since people took the time to

**Comment by Avispa** [comment]
**NOW** I found the "view config" tab. And the comment inside the config that says/links:
```
# Can't build on Windows - affected by https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/10
```
(last update Nov. 2019)

Anyhow:
- [ ] Maybe you wanna fix the mentioned GPG issue that appears to break the signature verification.
- [ ] Maybe you wanna consider bringing the fixes of v0.1.2 also to Windows users since it seems to be just a small step left out.

**Comment by Simran-B** [comment]
The "Verified" label on GitHub merely means that a digital signature was used to confirm the authenticity of a commit, i.e. the alleged author of the code change is actually the person who she claims to be.

![0.1.2 release labeled as verified](https://user-images.githubusercontent.com/7819991/110306513-36a2ed00-7ffe-11eb-979c-2d4ae8874273.png)

This has nothing do to with any signature issues in the Travis CI. That GPG error is related to Linux package management.

Linux and macOS builds were done with Travis, Windows builds with AppVeyor:
https://ci.appveyor.com/project/itsmattkc/olive/history

The commit a449b04 is tagged as 0.1.2 and this is the respective Windows build:
https://ci.appveyor.com/project/itsmattkc/olive/builds/28873190
The build artifacts are not available anymore unfortunately.

There are mostly translation related commits between the 0.1.0 tag and the 0.1.x branch: https://github.com/olive-editor/olive/compare/0.1.0...0.1.x
The only stability related change was this: eb611b78573e011cf990c55d3dea0f520f4db9b6
The 0.1 lineage was abandoned shortly after because the majority of issues were impossible to fix because of profound problems with the core design and code organization. Hence the rewrite, also known as 0.2.x or "Razor".

With 0.1.x unsupported and 0.2.x not in a good shape yet, you may want to use another editor if you need something stable right now. Every version of Olive is alpha software and thus in an experimental stage and not suitable for production. There are no intentions to maintain 0.1.x in anyway, therefore you will have to build 0.1.2 yourself or use something else until 0.2 becomes viable option.

**Comment by Simran-B** [comment]
The old build instructions:
http://web.archive.org/web/20200326141219/https://olivevideoeditor.org/compile.php

**Comment by Avispa** [comment]
> The old build instructions:
> http://web.archive.org/web/20200326141219/https://olivevideoeditor.org/compile.php

Thank you for the hint to the build instructions. However I was hoping that the person who produced the builds in the past could just spend 15 minutes to use it's already existing setup and more improtantly knowledge of the insides to make a new build before I spend a half day or even more (maybe inifity) to try to make it build.

> The build artifacts are not available anymore unfortunately.
You mean the resulting binaries or the configuration/pre-requirements? In the former case: why not just let it compile again?

My machine is not set-up for that purpose nor I really need a the new fixes (I guess) but that does't mean that somebody else would appriciate who is not eager (or familiar) with posting issues on _Github_. I sympathise with the project and I simply think it would be a good idea -- and yes, despite the fact that you wanna distance yourself from v0.1 evidently. ;-)

To be honest I'm a bit shocked that you/the-olive-team even decied to just completely  erase the documentation from your website to relay on archive.org. What lead to this descision? (It cannot be the occupation of maybe 200kb in text.) Just mark it legacy, push it to the very back of whatever list and at least people have still -- a realistic -- chance to find it.

I completly understand that you wanna move the resources to v0.2 but that doesn't mean that you have to delete documentation or dismiss already done work indireclty -- may it be "just" translations though it's even a stability fix:
> stability related change was this: eb611b7

See it as a PR move "we are still alive" or honoring the work of the guy who invested the time to fix the stability issue. :-)

In any way: thank you for your profound responce.

**Comment by elsandosgrande** [comment]
@Avispa 

It's a part of the general push towards Razor and away from the deprecated version. In fact, the only reason that Matthew reversed his decision of having 0.1 accessible solely through a “legacy” link (and through the Releases section of the repository if they took a second to look around the repository) is that people who did not understand the gravity of the warning that Olive is software in early alpha (early alpha → highly unstable and any assumption of any sort of reliability are unfounded and downright harmful to the user making such an unfounded assumption) and thought that they were deceived by Matthew and tricked into downloading an “unstable” version of Olive, when any and all versions and builds of Olive are unstable; it's just that Olive 0.1 was unstable in different ways and areas than Razor. As such, without any further maintenance ever being provided, there is absolutely no guarantee of 0.1 working or compiling in the future. Sure, there was no actual guarantee in the first place, but there was always an implicit guarantee that it'll work for known-good parts of the application on tested software and hardware configurations, at least for a short time after testing those configurations.

On that note, the Razor build instructions should work without any issues for 0.1, provided that you omit the OpenTimelineIO, OpenColorIO, and OpenImageIO sections of the build instructions (you can also add the installation of Frei0r effects to the steps for Razor when building 0.1, since 0.1 makes use of the Frei0r effects when they're present on the system).

**Comment by Simran-B** [comment]
> I was hoping that the person who produced the builds in the past could just spend 15 minutes to use it's already existing setup

I understand your request, but it's not that simple, unfortunately. It wasn't a person, but an automated process that ran builds. AppVeyor was configured via its UI to compile Olive, and that configuration was deleted (a bit too early in hindsight). It was superseded by a file-based configuration, but this new, version-controlled config was made for the rewrite (0.2.x), which is taking much longer than anticipated and has a much larger scope meanwhile.

My own local build environment that I used for 0.1.x got corrupted somehow while messing with Ruby installations that I require for work, so I can't build 0.1.2 quickly either. I will check if I can get it to work in a virtual machine however.

**Comment by Simran-B** [comment]
@Avispa I created a build of 0.1.2 in a Windows Server Docker container. The dependency versions are different and the set of DLLs  apparently as well, but you can give [olive-0.1.2-win64.zip](https://drive.google.com/file/d/1EoRrfGT7iXf80sMy2CIqKh6h8IQoxJqF/view?usp=sharing) a go and see if it works (I may have missed some libraries).

**Comment by Avispa** [comment]
@Simran-B: Thanks for the effort. I've noticed you linked against `libcrypto-1_1-x64.dll`. As far as i can tell v0.1.0 runs without that. What is it needed for in v.0.1.2? (I've just checked the directory of v0.1.0 and had quick look/try with vim/xxd into the binary of v0.1.0. Could't find any sign. However missing proper tools on Windows.)
Can you remove unnecessary dependencies in case it is not used?

**Comment by Simran-B** [comment]
All of them are needed because transitive dependencies link against them. It doesn't mean that they are actually used. The difference between old 0.1 builds and my package are the updated dependencies you get via pacman nowadays.

I used https://github.com/lucasg/Dependencies to identify the majority of the required DLLs. You can use it to find out which component needs libcrypto.
