### ISSUE TITLE
[CLI] Qt key-value command-line parameters are wrongly interpreted as project files

### ISSUE THREAD

**Issue by mara004** [olive-editor/olive#1511]
**Commit Hash** 
5d59ecb6

**Platform** 
KDE Neon 5.21.2

**Summary**
When launching Olive with key-value based Qt command-line parameters, such as `-platform xcb`, the value is wrongly interpreted as a project file. Qt still notices the parameters correctly, however.
In this example, a popup window would open on startup explaining the project file `xcb` did not exist. Nevertheless, Olive correctly uses the xcb platform plugin (i. e. is an XWayland Client).
(I noticed this issue while trying to find a workaround for #1507)

**Note**
I wasn't sure in which component to report this, as the CLI doesn't seem to have its own one.

**Comment by elsandosgrande** [comment]
I didn't even know that Qt has terminal flags (I thought that the only way to change the plugin is through `QT_QPA_PLATFORM`).

I vote for simply preventing Qt from seeing those flags when passed to Olive and pointing users towards the environment variables which produce the same results, since those seem to be more widely referred to in my experience (I'd be interested in seeing the sites which recommend using the flags) and since this would not introduce additional complexity to Olive (at the very least, Matthew wouldn't have to look Qt's flags up and add code to ignore them). If it wouldn't be very difficult to simply ignore the flags (not needing to write an exception for each one individually for example), then I'd say that simply ignoring them in Olive and letting them reach Qt would be fine.

**Comment by mara004** [comment]
> (I'd be interested in seeing the sites which recommend using the flags)

I don't know whether there are any websites recommending it. I know about the flags only from the --help-all option in kde command-line applications, and used it because I got accustomed to them and don't remember the names of all Qt-related environment variables, but you're probably right that not using flags would greatly simplify parsing.

**Comment by mara004** [comment]
The Qt wiki seems to provide a list of those flags: https://doc.qt.io/qt-5/qguiapplication.html#QGuiApplication

**Comment by itsmattkc** [comment]
Hmm this is most likely a side effect of using our own command line parser as opposed to Qt's (there were limitations to QCommandLineParser that resulted in us rolling a custom implementation). I wonder what the best way of filtering these out is (apart from manually filtering them out, which wouldn't be super robust code-wise).
