### ISSUE TITLE
[CRASH] Olive Crashes Everytime I try to export something

### ISSUE THREAD

**Issue by GabrielMadrigal** [olive-editor/olive#1532]
Commit Hash: 1e3cf533

Platform: Windows 10
Well, I was working on a YTP, I am not a big one, so I wanted to post some sneak peeks to a discord server and when I try to export the sequence, the olive video editor just crashes and leaves an empty video behind.

How do I fix this Obnoxious problem?

**Comment by Simran-B** [comment]
0.1.x is not maintained anymore. A race condition that can lead to crashes on export was fixed in https://github.com/olive-editor/olive/commit/eb611b78573e011cf990c55d3dea0f520f4db9b6 but I cannot tell if it helps with your problem or not. There are no official builds of 0.1.1 and 0.1.2 unfortunately. Also see #1509. You can try this one that I created however: [olive-0.1.2-win64.zip](https://drive.google.com/file/d/1EoRrfGT7iXf80sMy2CIqKh6h8IQoxJqF/view?usp=sharing).
