### ISSUE TITLE
ALSA support

### ISSUE THREAD

**Issue by notramo** [olive-editor/olive#158]
If PulseAudio is not running, the editor crashes.
OS: Void Linux (by the way, it's systemd-free distro, so lot people don't have PulseAudio installed)
version: 20181130

**Comment by itsmattkc** [comment]
I'll test this some time today, but I've been looking this up and found suggestions that this might depend on the way Qt is compiled. Do you have information about the Qt version/configure args used for compiling it?

**Comment by notramo** [comment]
Qt version: 5.11.2
Is [this file](https://github.com/void-linux/void-packages/blob/master/srcpkgs/qt5/template) useful for you? I'm using this package.

**Comment by itsmattkc** [comment]
I've been able to confirm that Qt (and therefore Olive) will always try to use PulseAudio unless it is compiled with `-no-pulseaudio` (as a configure argument) or there are no PulseAudio libs found on the system when `./configure` is run. Olive will happily use ALSA if Qt is compiled without PulseAudio support.

I will however keep this issue for now as ideally Olive should be resilient enough to not crash if it can't find any audio devices.

**Comment by notramo** [comment]
[Shotcut](http://shotcut.org/) works happily with ALSA without PulseAudio installed. (On the same Void Linux installation)

**Comment by itsmattkc** [comment]
As I said, Qt does not return any audio devices if it was compiled with PulseAudio support and no PulseAudio is running on the system. If Shotcut works regardless, that probably means it doesn't use Qt for audio.

Now I _could_ rewrite the entire audio system to not use Qt, but if not relying on PulseAudio is desirable for this distribution, I feel like having a package of Qt compiled without PulseAudio support would be far more effective and wide-reaching (affecting all apps that use Qt for sound) than laboriously rewriting audio in one single app.

**Comment by itsmattkc** [comment]
I apologize, it turns out I was incorrect after all.

Qt in fact _does_ have access to both ALSA and PulseAudio devices, but will inexplicably return a NULL "default" device if PulseAudio was compiled in and isn't running, even if ALSA devices are still available. Olive just has to explicitly choose them.

I had assumed due to the error message Qt printed (`using null output device, none available`), and due to an erroneous belief that Qt would at least try to return _any_ device before it returned NULL (along with what other people appeared to be saying online) that the fact I was receiving a NULL device was because Qt literally couldn't see any devices. But it turns out this was wrong, so I apologize if I appeared stubborn (and for spreading misinformation).

I encourage you to try commit a5761861d4d42bebd54352f17b0c5ca3010fc759 and see if that will solve this issue.

**Comment by itsmattkc** [comment]
I believe this has been solved, so I shall close this issue.
