### ISSUE TITLE
[PROJECT] 

### ISSUE THREAD

**Issue by Lampadina17** [olive-editor/olive#1584]
**Commit Hash** 

**Platform** 
Windows 10

**Summary**
0.2 isn't retrocompatible with 0.1 saves

**Additional Information / Output**

**Comment by elsandosgrande** [comment]
@Lampadina17 That's intentional. Olive 0.2 is practically a complete rewrite, which means that this is nothing short of expected. As Olive 0.1 is deprecated, not to mention the completely different architecture from 0.2, there is no intention to include support for 0.1 project files (it's not like it's realistically possible in the first place). There's nothing else to be said.
