### ISSUE TITLE
Add support for Flatpak packages

### ISSUE THREAD

**Issue by LeandroStanger** [olive-editor/olive#159]
http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by notramo** [comment]
Flatpak requires the `flatpak` tool to be installed.
I recommend [AppImage](https://appimage.org/), which doesn't require a package manager. Just download it, make it executable, and run.

**Comment by LeandroStanger** [comment]
I use the Endless OS only supports only Flatpak

**Comment by notramo** [comment]
AppImage is supported by **every** Linux.

**Comment by LeandroStanger** [comment]
AppImage is not supported by Endless OS

**Comment by notramo** [comment]
From their website: "Linux apps that run anywhere"
It don't need support from distro maintainers.
Installation is not required, the AppImage file contains all the required dependencies.
It requires three simple steps:
1. Download
2. Make the file executable
3. Run the file

Indeed, it would be better to have it in the menu instead of putting the AppImage file on the Desktop, but maintaining packages requires lot of time that @itsmattkc could spend on writing code instead. Since AppImage runs on older computers also, and it don't require a custom package manager nor support from distro maintainers, I recommend packaging Olive in AppImage. Endless OS packagers could create Flatpak packages for their distro.

**Comment by itsmattkc** [comment]
I don't have an issue setting up a Flatpak package as it seems it can be set up to automatically build from the Git repo. It's true that I wouldn't have much time to _maintain_ it, but I don't think it'll require much once it's set up.

**Comment by suckybell** [comment]
AppImage has the issue of not having any real built in method of updating.  Flatpak connects to a repository, so that's not an issue.  Some distros are even starting to include the option to auto-update them.

**Comment by notramo** [comment]
@suckybell https://github.com/AppImage/appimaged

**Comment by probonopd** [comment]
AppImage as a format is not specifically endorsed or supported by Endless OS but can run on Endless OS just fine, like on most other distributions. In fact the format is specifically designed so that it does not have to be supported by the distribution, so as to make it universally usable across most.

With AppImageUpdate, you can get very efficient "binary diff" updates. 

Would you be interested in a pull request that builds and publishes an AppImage?

**Comment by AngryPenguinPL** [comment]
Well, If i can vote, I would choose Appimage.
Why? Flatpak or snap is insecure and many distros not support it. So for distro A, you need prepare Flatpak but on distro B, flatpak is not available, they provide only snap support, so then need build it as snap. On distro C, none of them available. So? Better choose Appimage.
Appimage can run on any linux distro.

**Comment by notramo** [comment]
Maintainance of two packages is hard indeed, but there is an easy solution: create an AppImage, then put the single AppImage executable in a Flatpak package.

**Comment by probonopd** [comment]
How do I compile this on Ubuntu 14.04 (trusty)? Unfortunately I am seeing some compile-time error:
https://travis-ci.com/probonopd/olive/builds/95682822

**Comment by itsmattkc** [comment]
@probonopd Olive currently requires FFmpeg 3.4 and won't compile with an older version.

I've had good luck using this PPA on xenial, it seems to have a version for trusty too: https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-3

**Comment by probonopd** [comment]
Thanks @itsmattkc now I was able to compile it. However `make install` fails, despite

https://github.com/olive-editor/olive/blob/1a08364bc5373a84856957db7e9b7980de799a53/olive.pro#L220-L244

```
make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
make: Nothing to be done for `install'.
```

Do you know why?

**Comment by eszlari** [comment]
Flathub PR: https://github.com/flathub/flathub/pull/794

@itsmattkc Please add a comment on the PR, if you want to have commit access to that repository!

**Comment by LeandroStanger** [comment]
Flatpak has already been created https://github.com/flathub/org.olivevideoeditor.Olive

**Comment by probonopd** [comment]
Please also see my pull request that will generate an AppImage:

https://github.com/olive-editor/olive/pulls

**Comment by probonopd** [comment]
> Both snap and flatpak are actually portable, as opposed to appimage which pulls libraries from host system.

Every time I try Flatpak is not installed and working out of the box on Ubuntu, and snappy is not installed and working out of the box on Fedora. AppImages work on both since there needs to be nothing special installed first.

> I'd be curious to hear which distribution specifically doesn't ship packages for both.

Many. And if they do ship them, they tend to be outdated.

> Security is also moot point when appimage doesn't offer sandboxing at all.

If you like sandboxing, you can use a sandbox like Firejail. However, I only run software I trust to begin with, and some users want this software to run unencumbered (with full access to the system and no limitations that impede look and feel and usability).

Those application shipping methods have different objectives. Think of AppImage as the equivalent of a Mac .app in a .dmg. One app = one file, simple.

**Comment by eszlari** [comment]
@itsmattkc If you need help with flatpak, I would be happy to answer any questions you might have!

**Comment by notramo** [comment]
@barthalion Are Snap and Flatpak portable? How they be used on e.g. a basic Void or Arch Linux installation with basic Xorg after downloading the package, and making it executable?

**Comment by probonopd** [comment]
Snap and Flatpack require
* Snap and Flatpak to be installed on the system
* The application to be installed on the system

AppImage requires neither.

**Comment by barthalion** [comment]
@notramo They are portable in the meaning that once you have snap or flatpak installed, nothing else is required from the host distribution. @probonopd conveniently avoids mentioning how AppImage's premise relies on a pipe dream of libraries ensuring stable ABI.

Contrary to what you're trying to do here, it's not the place for such discussions. The issue was about Flatpak and it's been implemented.

**Comment by probonopd** [comment]
> pipe dream of libraries ensuring stable ABI

We should hold library authors accountable to provide ABI stability - https://media.ccc.de/v/ASG2018-174-2018_desktop_linux_platform_issues

**Comment by notramo** [comment]
@barthalion Yes, it started to became a flame war about Flatpak vs. AppImage. Since we have both packages now, everybody is happy, so I agree to close it.
