### ISSUE TITLE
[NODES] Zoom just with mouse wheel

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1597]
**Commit Hash** 
59952fdd

**Platform** 
macOS 10.14.6

**Summary**
Continuing with Node Editor UX as in #1594 and #1596, it would be nice to zoom the view just with the mouse wheel, this way it wouldn't be necessary anymore to make use of ctrl/cmd to navigate your nodes.

Thanks

**Additional Information / Output**

**Comment by krischan941** [comment]
There is already an option for this:
Tools / Preferences / Behaviour / General / Scroll wheel zooms by default instead of scrolling
But it also affects the timeline.

**Comment by pgilfernandez** [comment]
Nice!!
well, then I would suggest to split the feature so that users can set the behavior independently for timeline and nodes editor, that makes sense?

**Comment by itsmattkc** [comment]
I don't like the idea of introducing inconsistency by default, but I'd be open to a setting per widget (or even changing that "Scroll wheel zooms by default instead of scrolling" setting to only affect the node view, since I feel like users wanting to scroll to zoom into the timeline is an unlikely use case)

**Comment by pgilfernandez** [comment]
Well, I like to zoom with the scroll wheel both in the node view and timeline, but I understand that people may think different, that's why I suggested to add a setting per widget... why not?

**Comment by sobotka** [comment]
> why no?

Because options are not design.

Every option moves the design in a different direction, and can pull away from cohesion. Options aren’t good design. Thoughtful, patterned, predictable planning is “good design”.

**Comment by itsmattkc** [comment]
I kind of agree, after some thought, I think for the most part users will work with muscle memory, and therefore most users will want the controls to stay consistent (as you yourself have found, preferring scroll wheel zooming on all widgets, not just the node view). As such, I'm leaning towards leaving it as it is.

**Comment by sobotka** [comment]
> I think full customization is a great open source weapon but I also understand your point.

Name a single open source tool that handles things properly or is well designed.

The main thing here though, and I'm not making a case either way, is _patterned_ behaviour. Why is patterned behaviour important? Because if a patterned behaviour is identified, the audience will begin to make _predictions_ of similar behaviour across different domains. This is that mysterious "intuitive" rubbish that many folks say; it's not _intuition_, but contextually driven reinforcement.

Again, I'm open to any well reasoned design choice here. The key is _reasoned_ however.

Options are not reasoning. They should be considered a last resort failure of design.

**Comment by pgilfernandez** [comment]
> Name a single open source tool that handles things properly or is well designed.

Without any doubt Blender (www.blender.org). It has the most configurable UI, themes and color schemes, keyboard/mouse customization, etc.

> Again, I'm open to any well reasoned design choice here. The key is _reasoned_ however.
> 
> Options are not reasoning. They should be considered a last resort failure of design.

I still think Options are not a failure of design per se.
Here I would say the Reason is to liberate the software so that user can choose their preferred workflow and not force one that we think is the right one. We should think that open source create software for the whole world and people/companies/workflow/younameit are different and they would make things different...

Once again, it's my modest point of view, I'm not trying to convince or discuss with anyone. At the end we are talking about having 1 setting affecting 2 Views or 2 settings affecting 1 view each... a pretty simple thing, I'm not proposing to put Olive upside down =)
