### ISSUE TITLE
[UI] - README - Please add info how to translate/revise translation

### ISSUE THREAD

**Issue by bovirus** [olive-editor/olive#1620]
**Commit Hash** 

72ed87d9

**Platform** 

Windows 10

**Summary**

Add in README (github home page) info about translation.

**Additional Information / Output**

@itsmattkc 

Please add in README (github home page) info about translation.
I propose to move all translation files on host like Transiflex.

**Comment by itsmattkc** [comment]
https://github.com/olive-editor/olive/wiki/Translations

**Comment by bovirus** [comment]
@simran-B
@itsmattkc 

Thanks for the info.

For me this a very important info for translators that should be added to README in github home page repository

https://github.com/olive-editor/olive

Please add a link for translator to show it immediately this info (as happen for other github projects).

Please consiser also to move .ts files on Transiflex page that make it more flexible.

I saw it on other github projects,

**Comment by Simran-B** [comment]
v0.2 is still undergoing a lot of changes, potentially obsoleting the work you put into translating Olive. I would recommend waiting a bit more before you put a lot of effort into it. For this very reason, we do not want to advertise how to translate Olive. It's simply too early and we don't want to waste people's time.

I don't think that the project will move to services like Transifex while in alpha stage, but it could be an option in the future somewhere around v1.0. But I'm unsure if Olive qualifies for the open source program and it's definitely too expensive as a paid service. Also, the existing translation process is straightforward. We may further simplify it by regularly updating the .ts files so that all translators need to do would be to translate strings in Qt Linguist and open a PR (removing the need for running lupdate in a terminal).

**Comment by bovirus** [comment]
@Simran-B 

Could you please provide me the info where (path) are located in Olive program installation the .qm language files?
I would check the translation in plòace bfore to push it.
I believe that this is another info useful for translators that can be added in README about translation.

Thanks.

**Comment by Simran-B** [comment]
> where are located the .qm files for Olive program in folder installation?

They get compiled into the executable using Qt's resource compiler [RCC](https://doc.qt.io/qt-5/rcc.html).

The CMake code for that is:
https://github.com/olive-editor/olive/blob/4adaedb3049340ac6a71d000db0340d873621eb7/app/CMakeLists.txt#L47-L60

And this is the template file it uses: [app/ts/translations.qrc.in](https://github.com/olive-editor/olive/blob/master/app/ts/translations.qrc.in)
