### ISSUE TITLE
Removed frames show up with scrubbing to the left

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#166]
There seems to be an issue with caching. If I trim and delete e.g. the end and the beginning of a clip and move it around, I tend to get removed bits of that clip in the preview while scrolling to the left by dragging the playhead on the ruler. It never shows up when I scroll to the right and it isn't visible in the exported video.

**Comment by itsmattkc** [comment]
I've gone ahead and added an option in the preferences dialog in 302310ab7bd1319e92f3955015f4322e1f18126b. It defaults to accurate seeking because it's probably less alarming than "not fast seeking". I believe this technically solves this issue despite still being a stopgap for what may eventually be an improved playback algorithm.
