### ISSUE TITLE
[EDIT] Waveform in timeline is inaccurate

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#1664]
**Commit Hash** 
08e2fa4d8ebfc2df9edcdb981a7e118b21a8c1c6

**Platform** 
Any

**Summary**
The audio waveform in the timeline sometimes strays from the actual audio by a substantial amount of time making it impossible to use the waveform as a guide for editing.

**Additional Information / Output**
I'm not sure what caused this, but it's likely something to do with the waveform mipmapping introduced a few months ago. Possibly some kind of rounding error.

**Comment by elsandosgrande** [comment]
@itsmattkc Do you have a screenshot as an example, or a screen recording if a screenshot is not applicable? I'd like something to check against to see if I see this on my end as well and to see how severe it is in comparison to what you're seeing.

**Comment by DwarfFighterCleric** [comment]
Interesting... Was your audio encoded in VBR/ABR (variable bitrate) or CBR? (constant bitrate)
For testing purposes, could you test if this also happens if you re-encode the audio with a constant bitrate?
In FFmpeg, you can do this without having to re-encode the entire video:
ffmpeg -i MyFile.mkv -c:v copy -c:a libvorbis -b:a 96k -t 300 NewFile.mkv
(the -t option is for trimming only a portion of the file, in this case the first 300 seconds, remove it if you want the whole file)
(I'm not shifting the blame into you... I just want to know if that's the root source cause of the problem, so diagnose comes faster...)

**Comment by elsandosgrande** [comment]
Here's an example that I came across in my own files — latest commit, Ubuntu 21.04: https://cdn.discordapp.com/attachments/774874977378893864/861767923156779069/Screencast_from_20210706_023650.webm

**Comment by elsandosgrande** [comment]
@DwarfFighterCleric Here are the parameters of my files if you're interested:

<details>
<summary>ffprobe</summary>

<pre>
<code>
$ ffprobe ./Videos/YouTube\ projects/VID_20180317_114553.mp4
ffprobe version 4.3.2-0+deb11u1ubuntu1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Ubuntu 10.2.1-20ubuntu1)
  configuration: --prefix=/usr --extra-version=0+deb11u1ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0+deb11u1ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './Videos/YouTube projects/VID_20180317_114553.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2018-03-17T10:54:24.000000Z
    com.android.version: 7.1.2
  Duration: 00:08:29.20, start: 0.000000, bitrate: 12150 kb/s
    Stream #0:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 11992 kb/s, SAR 1:1 DAR 16:9, 29.64 fps, 29.50 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2018-03-17T10:54:24.000000Z
      handler_name    : VideoHandle
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 156 kb/s (default)
    Metadata:
      creation_time   : 2018-03-17T10:54:24.000000Z
      handler_name    : SoundHandle
</code>
</pre>

</details>

**Comment by elsandosgrande** [comment]
So… Using a [self-made test tone file](http://mellemws.my.to/direct/Test_audio.flac) — my cockatiel got into the recording, so watch your volume levels — and Audacity, I was able to quantify the discrepancy between Olive's waveform and the actual audio.

## Preface

I set the frame rate of the sequence to a thousand frames per second and the timecode format to seconds to make the discrepancy easier to evaluate. If judging by the audio scrubbing in Olive, then Audacity's waveform seems to be behind the audio by about twenty milliseconds, but it seems like some audio codecs — maybe even FLAC — don't support such a high temporal resolution — this comes from some of the pages that I've come across while looking for any information regarding Audacity and possible lag in it, so take that with a healthy serving of salt — so the discrepancy might be introduced by the codec itself. There is no perceived discrepancy between the waveform that Audacity presents and the audio which the waveform represents when the file is played in Audacity itself, the twenty-millisecond discrepancy is effectively constant — it can basically be seen as an offset between Olive and Audacity — and the scale of the discrepancy between Olive's sound and Audacity's waveform is and order of magnitude smaller than that of Olive's sound and Olive's waveform at the beginning, not to mention several orders of magnitude smaller at the end of the ~48s recording, so, for all intents and purposes, it can be safely ignored.

The waveform in Olive also seems to be vertically inverted compared to that of Audacity, but I am not even close to being knowledgeable enough to figure out who's wrong and who's right in this case, so take that as you will. 

### Note
The audio level metre — the thing to the right of the timeline in the default layout — follows the waveform when playing the timeline back, but follows the sound when scrubbing with `Enable audio scrubbing` ticked in `Tools → Preferences` under `Behavior → Audio`; you can verify this yourselves by holding down the right arrow key to simulate timeline playback.

## Analysis

The first test tone starts at around 0.61s, but is shown to start at around 0.715s in Olive:

<details>

<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/40576902/124834525-3997f500-df80-11eb-8649-24fe9549681b.png)

![image](https://user-images.githubusercontent.com/40576902/124834693-7a900980-df80-11eb-8643-50645148e7e5.png)

</details>

It ends at around 1.635s, but is shown to end at around 1.916s in Olive:

<details>

<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/40576902/124843292-f2b2fb00-df91-11eb-99c7-0ccfd0f9f969.png)

![image](https://user-images.githubusercontent.com/40576902/124843330-0199ad80-df92-11eb-884b-8d9573ec0871.png)

</details>

The second test tone starts at around 3.18s, but is shown to start at around 3.728s in Olive:

<details>

<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/40576902/124844000-7caf9380-df93-11eb-993c-876b7c2e123e.png)

![image](https://user-images.githubusercontent.com/40576902/124844040-8cc77300-df93-11eb-8752-8ae96a43d361.png)

</details>

It ends at around 4.307s, but is shown to end at around 5.048s in Olive:

<details>

<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/40576902/124845171-7242c900-df96-11eb-85cc-c93b2cea31a7.png)

![image](https://user-images.githubusercontent.com/40576902/124845291-b33add80-df96-11eb-801a-c869f150f62c.png)

</details>

The third test tone starts at around 5.773s, but is shown to start at around 6.766s in Olive:

<details>

<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/40576902/124845504-280e1780-df97-11eb-9b2c-04e3f460b032.png)

![image](https://user-images.githubusercontent.com/40576902/124845527-34927000-df97-11eb-8544-632e739382f1.png)

</details>

It ends at around 6.849s, but is shown to end at around 8.025s in Olive:

<details>

<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/40576902/124845936-0eb99b00-df98-11eb-9ffb-0612c77e9fd0.png)

![image](https://user-images.githubusercontent.com/40576902/124845974-22fd9800-df98-11eb-860d-5524fd277306.png)

</details>

---

As it's getting pretty late and my battery's getting pretty drained — the laptop starts heavily slowing down at ≤20% — I'll finish the analysis when I have some more free time. I might even be able to determine the exact way in which the waveform keeps progressively slipping, though I must say that this is fairly outside anything that we were taught in mathematics class, at least as far as I can see at the moment.

_Sigh…_
_I seriously need to start doing this during the day as opposed to the middle of the night_
_I still need to test the commit which Matthew suggested on Discord might be unaffected on top of all of this_
_I've already built it, but still…_

I'll delete this little section when I finish the analysis.

Collapsible content template:

<details>

<summary>Screenshots</summary>



</details>

## Post Scriptum

For those of you wondering why the title of the Audacity window changed from “Test audio” in the first screenshot to “Audacity (Recovered)” in the latter ones, I simply managed to crash Audacity while messing around with its playback — holding the left arrow key while Audacity is playing while pressing Space to pause the playback. That crashes both Audacity 2.4.2 and Audacity 3.0.3-RC2 from what I can tell, though I didn't really look into it, since I was in the middle of looking into this bug.

Also, here's the `ffprobe` output for my test tone recording:

<details>

<summary>Test audio ffprobe</summary>

<pre>
<code>
ffprobe version 4.3.2-0+deb11u1ubuntu1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Ubuntu 10.2.1-20ubuntu1)
  configuration: --prefix=/usr --extra-version=0+deb11u1ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0+deb11u1ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, flac, from './Test audio.flac':
  Metadata:
    DATE            : 2021
    track           : 1
    ALBUM           : Test audio
    TITLE           : Test tones — vocals
    ARTIST          : Sandy Vujaković
  Duration: 00:00:48.30, start: 0.000000, bitrate: 1500 kb/s
    Stream #0:0: Audio: flac, 48000 Hz, stereo, s32 (24 bit)
</code>
</pre>

</details>

**Comment by itsmattkc** [comment]
> The waveform in Olive also seems to be vertically inverted compared to that of Audacity, but I am not even close to being knowledgeable enough to figure out who's wrong and who's right in this case, so take that as you will.

Wow good pickup, Olive is absolutely wrong here - the drawing code is incorrectly assuming a bottom-left origin (where a higher Y value would go up) while it should be written for a top-left origin (where a higher Y value would go down).

**Comment by Simran-B** [comment]
Here's what I see with a test audio file of 1000 samples at 1000 Hz (sequence at 1000 FPS):

![image](https://user-images.githubusercontent.com/7819991/124895444-d8523f00-dfdc-11eb-9d80-bfc64fe390b7.png)

The audio monitor shows the first audible sample at 481 and I can also hear it. The actual beginning is at exactly 500, however (see below). The waveform starts at 586 in Olive.

![image](https://user-images.githubusercontent.com/7819991/124896064-69291a80-dfdd-11eb-9118-9d102e497a8d.png)

With the audio clip starting at 0, toggling audio time units shifts the waveform very slightly. If you look at the yellow line, you see that the waveform is 2 pixels further to the right with audio units disabled compared to audio units enabled (orange line).

![image](https://user-images.githubusercontent.com/7819991/124897867-fe78de80-dfde-11eb-88aa-64bf9b9d6bc5.png)

**Comment by Simran-B** [comment]
There is also some general issue with updating the UI regarding waveforms. Placing or moving audio clips anywhere but at the very beginning of the sequence makes the waveform appear too far to the right.

Certain actions such as placing another audio clip on the timeline (at least in certain places) or shortening, then enlarging the clip in question again seem to invalidate the UI and trigger a recalculation of the waveform position.

At the end of the below video, note that the waveform position of the bottom clip slightly changes once more when I delete another clip - looks like some calculation is pretty inconsistent.

https://user-images.githubusercontent.com/7819991/124903349-29196600-dfe4-11eb-8a1d-e214ef554e95.mp4

The amount the waveform initially appears too far to the right appears to be proportional to the location on the timeline (start time of the clip). With my 1000 Hz test file of 1000 samples with sine waves from 500-1000, the sine waves are fully shifted out of the clip boundary if I move the clip to 2385. The sequence framerate is set to 1000 and the audio sample rate is at the default of 48000:

![image](https://user-images.githubusercontent.com/7819991/124906722-a8f4ff80-dfe7-11eb-8df5-bffb5d710401.png)

**Comment by DwarfFighterCleric** [comment]
Excuse me, this is more curiosity on my part than anything else.
Why was 1.000 FPS audio used for that test again? Any particular reason for 1.000 FPS?

**Comment by Simran-B** [comment]
I wanted it to be 1 audio sample per millisecond (1000 per second) to then set the frame rate to 1000 and have the frame counter count the audio samples.

**Comment by elsandosgrande** [comment]
@DwarfFighterCleric I wanted to be able to move the playhead in increments of one millisecond. Because the playhead moves in increments of frames — the shadow to the right of the playhead when you're really zoomed in is the frame that's currently shown on screen — I needed to set a frame rate at which one frame lasts exactly one millisecond. The length of a single frame at a given frame rate is calculated by dividing one second — whether it be represented as one thirty-six thousandth of an hour, or as a thousand milliseconds, or whatever other unit of time so long as it was properly converted — by the frame rate. As one millisecond is equal to a thousandth of a second, it is immediately noticeable that the frame rate should be one thousand frames per second, but you can easily calculate it in reverse to get that number — algebra and such.

#### Side note
The playhead in Audacity can be moved in increments of individual samples, which would, at a sampling rate 48kHz, be equivalent to 48 000FPS, but sub-millisecond precision was way overkill for the analysis, so I chose millisecond precision instead.

**Comment by elsandosgrande** [comment]
By the way, which files in the source deal with calculating and displaying the waveform? I'm curious about the mathematics behind this.

**Comment by itsmattkc** [comment]
Yep rounding error as I suspected

**Comment by elsandosgrande** [comment]
_I didn't even get to finish my report from earlier_

**Comment by itsmattkc** [comment]
@Simran-B I would be interested to see which of these are fixed/which persist following this fix. If some of those persist, it may be a different issue entirely. However it's correct behavior that the waveform is recalculated when you trim the clip because the waveform represents the actual rendered audio (i.e. it will respond to changes in volume, etc.) so any audio modification will trigger a recalculation.

**Comment by Simran-B** [comment]
Nicely done! The waveform lines up perfectly now when using audio units is turned on:

![image](https://user-images.githubusercontent.com/7819991/124983239-fe58fd00-e037-11eb-80b3-05cfc23b7735.png)

If I turn it off, then the waveform moves to the right by approx. half a sample, very slightly misaligning the waveform:

![image](https://user-images.githubusercontent.com/7819991/124985680-f9497d00-e03a-11eb-83b1-a9bf074c3cf5.png)

Not really a problem, but I'm curious what causes it (I assume that the error is below machine epsilon).

The first sine wave sample is still audible at 481 instead of 500. Might the audio buffer also suffer from rounding errors or is Qt's audio backend just not that precise?

The waveform shifting out of the clip based on the timeline location also appears to be fixed. I guess rounding errors accumulated there?

The unstable waveform drawing is also mostly gone. Changing a clip's length is visually stable. Changing the media in point is jittery if your timeline is zoomed out, but that's to be expected I suppose (the mipmap interpolation creating varying interference patterns from high-frequency imagery because of the limits of floating-point representations?)

**Comment by itsmattkc** [comment]
> Not really a problem, but I'm curious what causes it (I assume that the error is below machine epsilon).

I think what's happening there is the code determines the start sample by converting `scene position -> time -> samples`, so with audio time units off, that `time` will be rounded to the nearest frame. Probably better to ensure the audio time base is used at all times for accuracy.

> The first sine wave sample is still audible at 481 instead of 500. Might the audio buffer also suffer from rounding errors or is Qt's audio backend just not that precise?

Is that when scrubbing? That would make sense actually because the scrubbing interval is 20ms (i.e. it will play 20ms of audio when you jump somewhere), so with a sample rate of 1000, you'll just start hearing the first sample at 481.

> Changing the media in point is jittery if your timeline is zoomed out, but that's to be expected I suppose

Hmm depends how bad it is, might be worth getting a video if you can?

**Comment by elsandosgrande** [comment]
> […] That would make sense actually because the scrubbing interval is 20ms (i.e. it will play 20ms of audio when you jump somewhere), […]

So **that** is why there was a discrepancy between Audacity and Olive.

**Comment by itsmattkc** [comment]
It has to play something continuous - one sample on its own won't sound like anything but maybe a click or a pop.

**Comment by Simran-B** [comment]
> it will play 20ms of audio when you jump somewhere

Yeah, that checks out. At 480, it plays its 20 samples 480-499 (no audio), and at 481 it plays 481-500 (one audible sample included). But here comes the design question: should it play the previous samples up to the playhead instead of the following samples to match the expectation created by the waveform? Or would that break it for other cases? Should the boundary be the beginning or end of a frame? (that's quite a difference in terms of audio samples even with 24 FPS vs. 44100 Hz)

**Comment by itsmattkc** [comment]
> But here comes the design question: should it play the previous samples up to the playhead instead of the following samples to match the expectation created by the waveform?

I think the current design makes sense. I think it's fairly intuitive and useful that the audio played when jumping to that frame is the audio played during that frame - not the audio before it.

**Comment by elsandosgrande** [comment]
I'd say that the only sensible thing is that it only plays the length of a single frame when scrubbing, otherwise trying to match up the sound with the waveform if you need to align something extremely accurately to the sound is quite hard.

> It has to play something continuous - one sample on its own won't sound like anything but maybe a click or a pop.

1. Yes, but one millisecond is still long enough in my experience and allows for much greater accuracy.
2. If you go above fifty frames per second, this becomes a practical issue if you need to align something precisely with some audio recording.

**Comment by itsmattkc** [comment]
> I'd say that the only sensible thing is that it only plays the length of a single frame when scrubbing

While this sounds logical, in my testing I've found it led to more a disconcerting user experience. 60 FPS (16ms) would be too short and 25 FPS (50ms) would be too long. 20ms was the compromise.

> Yes, but one millisecond is still long enough in my experience and allows for much greater accuracy.

It really isn't. This is a 1ms interval and you can barely even tell what it is let alone what it sounds like:

https://user-images.githubusercontent.com/34096995/124994942-faee6180-e089-11eb-9e27-b53f192fdfb1.mp4

> If you go above fifty frames per second, this becomes a practical issue if you need to align something precisely with some audio recording, so having the length of audio played back when scrubbing match the length of a single frame seems natural.

As I said earlier, I feel it's quite the opposite. I found that I preferred the scrub interval to be independent of the frame rate.

**Comment by Simran-B** [comment]
At 60 FPS, one frame lasts a little less than 20ms. Playing exactly the audio samples of one frame will be too short for high framerate footage. Well, depending on your definition of what is useful to hear when scrolling one frame at a time.

With my test file, it's an extreme case (the sample rate matching the sequence FPS) that shouldn't be optimized for. There might still be something to improve here to allow for precisely aligning audio to video acoustically. The playhead marks the beginning of a frame, but also indicates the end of the frame. Should the 20ms range also be drawn in a similar way? That would visually explain why there's something audible already at 481:

![image](https://user-images.githubusercontent.com/7819991/124994212-cbb60100-e045-11eb-9683-58142bc3ef1d.png)

The jittering seems less now with the rounding error fix. Looks like there's just normal interference left:

https://user-images.githubusercontent.com/7819991/124995040-08362c80-e047-11eb-95e8-4234bdc3f6f9.mp4

It could potentially be reduced by using a smaller mimap and smoothing out the waveform with interpolation, but that seems like something a DAW might want to do but not a video editor.

One more thing: I noticed that manipulating one audio clip affects the waveform of another clip in subtle ways:

https://user-images.githubusercontent.com/7819991/124994659-77f7e780-e046-11eb-92f0-10f6c1b36e09.mp4

It occurs at the other clip past the end of the clip that is being manipulated.

**Comment by Simran-B** [comment]
> > Not really a problem, but I'm curious what causes it (I assume that the error is below machine epsilon).
> 
> I think what's happening there is the code determines the start sample by converting `scene position -> time -> samples`, so with audio time units off, that `time` will be rounded to the nearest frame. Probably better to ensure the audio time base is used at all times for accuracy.

With a normal framerate sequence (29.97 in my test), the effect is pretty pronounced when scrolling with audio units off:

https://user-images.githubusercontent.com/7819991/124996774-d1ade100-e049-11eb-89ac-c7a03d8e0b9f.mp4

Would be nice to have the same accuracy here as with audio units turned on. One may still want "frame snapping" of audio clips later on, but that should be independent of one another.

**Comment by itsmattkc** [comment]
> There might still be something to improve here to allow for precisely aligning audio to video acoustically.

Hmm I'm not opposed to some sort indication, but I'm not sure how this could be done in an intuitive/uncluttered way. We could always add a preference for scrubbing interval so that at least it's semi-transparent to the user without sifting through source (and can be adjusted to meet their definition of useful audio, as you say).

> The jittering seems less now with the rounding error fix. Looks like there's just normal interference left:

Yeah that seems like it's probably normal? As you say it could likely be smoothed out further but it's probably overkill here (at least for now).

> One more thing: I noticed that manipulating one audio clip affects the waveform of another clip in subtle ways:

That's interesting, I _think_ that's another kind of rounding error based on where the audio starts rendering (starting from that mid section rather than from 0 leading to the waveform being "summed" at different places).

> With a normal framerate sequence (29.97 in my test), the effect is pretty pronounced when scrolling with audio units off:

Ah that's a good demonstration of the issue, that's more extreme than I realized. I think we can probably officially call it a bug.

**Comment by elsandosgrande** [comment]
@itsmattkc Hm… Does Olive make small breaks in between the snippets of sound that it plays while scrubbing? I expected to be able to hear everything almost perfectly well by just holding down the right arrow key for scrubbing — almost as if the timeline were being played back — but it instead sounded kind of choppy.

In either case, I do agree that being able to go down to one-millisecond snippets with Olive as it is currently is not a pleasant experience 😅.

**Comment by itsmattkc** [comment]
> Does Olive make small breaks in between the snippets of sound that it plays while scrubbing?

Depends on your OS' key repeat interval (which will determine the frequency of key presses that Olive receives) - theoretically if it was 20ms it should play pretty consistently, but it's more likely that it's something else.

**Comment by elsandosgrande** [comment]
I'll look into that, but I hear the same kind of choppiness when scrubbing with the pointer as well — it was quite a bit more pronounced in your one-millisecond experiment though. I'll have to double-check that after I build the latest commits though, since I might be misremembering something.

**Comment by itsmattkc** [comment]
It's quite likely there's some latency/buffer issues regarding Olive pushing the audio to Qt. Again, we may see that improve with a better audio library.

**Comment by elsandosgrande** [comment]
In that case, I think that we should leave this millisecond discussion for when PortAudio gets integrated into Olive. At the very least, having a trustworthy waveform makes it reasonable to do precise alignment to the audio.

**Comment by elsandosgrande** [comment]
@itsmattkc So, after setting the key repetition rate far beyond anything useful when editing text — it almost feels like teleportation now — the timeline practically _is_ being played back, except that the same audio issue as with scrubbing via the pointer is present.

Here is a sample recorded through Audacity — the first part is me just holding the right arrow key down starting from the beginning of the timeline, while the second part is me scrubbing the timeline via the pointer: http://mellemws.my.to/direct/Olive_recorded.flac

Here is how far I set the repetition rate — key speed according to GNOME: 
![image](https://user-images.githubusercontent.com/40576902/125005250-9c11f380-e05b-11eb-8b62-b06ab6e0a00e.png)

This may or may not be something that Olive has no control over without switching to PortAudio, or just switching off of Qt's audio interface in general, but I thought that you might still like to have something concrete with regards to this issue. Oh, and just so that it's perfectly clear, I used my self-made test tone for the demonstration above.

**Comment by itsmattkc** [comment]
@Simran-B Just letting you know that the latest commit uses the audio timebase at all times when displaying the waveform.

**Comment by prokoudine** [comment]
Latest Linux build doesn't have the issue I was experiencing anymore. Whee!

**Comment by Simran-B** [comment]
@itsmattkc Works like a charm! The slight jumping when toggling audio time units is also gone due to this change.

Added a reminder to the Revisit later board about indicating which audio samples are played when scrubbing.

Regarding crackling, it might be caused by playing "arbitrary" audio chunks regardless of the waveform. There should be very little crackling if the portion of audio starts and end at a zero-crossing of the waveform, and no crackling if short fades are applied to both ends. Hardware/driver issues can also cause crackling, e.g. if the audio buffer is too small or cannot be filled in time. But before diving into that, we should make sure that Olive doesn't make the system play audio that necessarily results in popping.
