### ISSUE TITLE
Zoom control for Viewer

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#167]
Not sure if this is because I'm on a HiDPI display, but zoom in the viewers area is kinda off, and I can't zoom in or zoom to fill or whatever. Would be nice to have some basic control over it. Screenshot attached.

![2018-12-17 01-37-11](https://user-images.githubusercontent.com/57467/50059793-79b5e300-019c-11e9-8c77-bbcceb3179bb.png)

**Comment by itsmattkc** [comment]
Hi, can you describe what you mean by "zoom"? Do you mean changing the scale of the videos?

**Comment by prokoudine** [comment]
Yeah, pretty much. There's a rather large unused black area quite visible on the screenshot.

**Comment by itsmattkc** [comment]
It does seem this is specific to using QT_SCALE_FACTOR, as changing the DPI through GNOME on my setup doesn't cause this issue. Unfortunately I think different Qt versions/distros/window managers have widely varying support for HiDPI methods and probably will continue to for some time.

Regardless, I've written a fix for QT_SCALE_FACTOR in a9b8908988e44a29fab6cd910d65e18d357e7e5b that should solve this.

**Comment by itsmattkc** [comment]
I also realized what you meant by zoom controls and while it isn't the root cause of this issue, it is something I've wanted to add for some time. 04274637427726c0148df5cb0199a673a23fed7c adds the following combobox to change the viewer's scale.
<img width="320" alt="zoom control" src="https://user-images.githubusercontent.com/34096995/50124703-eecb0a80-02b9-11e9-8953-b4826dda7193.png">
Hopefully this solves this issue completely.
