### ISSUE TITLE
[PLAYBACK] Stop timeline playback at last frame of sequence instead of the frame after

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1685]
**Commit Hash** 
7dfb234b

**Platform** 
macOS 10.14.6

**Summary**
I feel like the last played frame when previewing any sequence should be the last of any track you have in your sequence but not a black one which is out of your project.
I don't know if I'm explaining myself correctly, here is an example (imagine we play the preview in the Sequence Viewer), I would say the last played frame should be as follows:
<img width="1126" alt="timeline_end" src="https://user-images.githubusercontent.com/5942369/126464505-2ff02a97-fa83-48b5-aade-d003d5df7fdc.png">

What do you think?

**Additional Information / Output**

**Comment by Simran-B** [comment]
Earlier 0.2 builds used to hold/freeze the last (and first) frame if the clip extended beyond the medium, but this is no longer the standard behavior. Now, there is a loop mode option to control the behavior: https://github.com/olive-editor/olive/commit/1fca3e1767bdd937ac010511cabf9bca43b0952a

You can choose between
- **off** (black frame, default)
- **clamp** (use first or last frame respectively outside the medium bounds)
- **loop** (repeat the medium until the end of the clip)

It's an option of the Media node in the Parameter Editor. Set it to clamp for your desired behavior:

![image](https://user-images.githubusercontent.com/7819991/126471952-ba0ae4b9-3b70-4ff5-88e8-3269881b3911.png)

**Comment by pgilfernandez** [comment]
Umm, correct me if I'm wrong but I think you didn't understand me.

What you suggest is nice and so useful but it only applies to "media", no if you have (as in my example) a solid and a text clip. In those elements I can't set up any "loop mode".

Anyway, let me explain my suggestion in another way: if you look at my screenshot, the clip length is 3 seconds. As I used a sequence of 25fps the total clip length is 3*25 = 75 frames. The actual playback behavior is to play it all and stop at frame 76. **I'm suggesting that is stops at frame 75** as it is the last one that contains "something of your interest", hehehe.
Furthermore, this is the behavior when playing in loop mode: when it reaches frame 75 then it goes back to frame 1 (it never shows frame 76 before going back to frame 1).

Thanks

**Comment by Simran-B** [comment]
Oh, my bad. You were referring to the playback behavior of the timeline as a whole, not individual clips. I can see how stopping at the last frame instead of the frame after would be beneficial.

However, I wonder whether there would be a risk of accidentally shortening the last clip by one frame when adding another clip with snapping turned on. With the playhead one frame after the clip, there is only one snapping point (both the end of the clip and the playhead are at the same frame to snap to). With the playhead one frame earlier, there are two snapping points close to each other and one has to be a bit careful to snap to the end of the clip and not the playhead.

> […] it only applies to "media", not if you have (as in my example) a solid and a text clip. In those elements I can't set up any "loop mode".

The loop mode wouldn't actually get you the desired behavior. Solids, stills, and text clips have an infinite duration in a sense, so no looping is possible. It wouldn't make sense for audio either. I guess there is no additional feature request here to add loop mode to something other than the media node, just your request to stop playback at the last frame instead of right after.

**Comment by itsmattkc** [comment]
I think there's perhaps an argument to make this available as a setting, but that it could easily be confusing or undesirable as default behavior. I'm certainly not aware of any other NLE that does this (if you know of one you can let me know).

**Comment by elsandosgrande** [comment]
The setting introduced in the commit that closed this ticket does not affect the behavior of the down arrow key, which one would assume to be in line the behavior of timeline playback.

Also, here's one video editor that has this behavior by default: https://mellemws.my.to/direct/Screencast_from_2022%25E5%25B9%25B402%25E6%259C%258817%25E6%2597%25A5_22%25E6%2599%258205%25E5%2588%258658%25E7%25A7%2592.webm
