### ISSUE TITLE
Project file incompatibilities 

### ISSUE THREAD

**Issue by FoxWhiskey** [olive-editor/olive#1700]
**Commit Hash** 9f4470f5

**Platform** Linux Mint 20.1

**Summary**
Olive refuses to open a project file if too old

**Additional Information / Output**
While the behavior is totally reasonable and probably unavoidable, it's a pain when trying to keep track of issues that may span over multiple builds.
Is there a way to "rescue" project files from aging ?

**Comment by ThomasWilshaw** [comment]
Unfortunately there isn't much you can do here. If your files are simple edits you could try exporting and reimporting a OTIO file. This will however lose any custom node setups. The only other thing to is to manually edit the .ove file and try to update it but that would probably be more work than recreating your edit.

**Comment by FoxWhiskey** [comment]
Thanks for the hints! Please allow one more question:
I have noticed in the past that it's possible to use previous .ove-files in later builds. So, not every new build introduces incompatibilty! Would I have been able to prevent this issue by not skipping four weeks of nightly builds and kind of refresh my .ove-file by downloading snapshots build by build instead?

**Comment by itsmattkc** [comment]
As you say, format-breaking changes are inevitable, especially while Olive is so heavily under development. Generally there hasn't been any effort in 0.2 to "upgrade" projects when the format is bumped because it wasn't stable enough for people to be making anything substantial anyway. But this seems to be changing now, so there may be more effort into ensuring old projects can be brought over.
