### ISSUE TITLE
[EDIT] Cross dissolve between 2 clips does not work if the first clip has already ended

### ISSUE THREAD

**Issue by rpatros1979** [olive-editor/olive#1767]
**Commit Hash**
d940c38a

**Platform** 
Arch Linux

**Summary**
With the latest commit, it seems that cross dissolve when applied between 2 clips does not work. If applied to 1 clip at a time, it does work. See the video for the behavior.

**Additional Information / Output*

https://user-images.githubusercontent.com/53153746/136667085-4b7a71e7-7875-44d9-948c-7ea52404f5fb.mp4

*

**Comment by rpatros1979** [comment]
Hello @itsmattkc , thank you for the reply. I just deleted the entire ~/.local/share/olivevideoeditor.org and re-created the 2 clips with the cross dissolve but unfortunately, I have the same behavior. I also tried with the latest build and it behaves the same.

https://user-images.githubusercontent.com/53153746/136681448-b52d6c66-1d2b-4700-b69a-c67e01d07781.mp4

**Comment by itsmattkc** [comment]
Ah I see. You're placing a transition between two clips at their ending/beginning points. The fact that it renders black is a bug, but technically that's not really an ideal thing for you to being doing (though we don't plan to prohibit it at this time) because the first clip will end before the transition is done and the second clip will start after the transition has started. Ideally you should trim your clips so this doesn't happen, or you can try some different "Loop Modes" on the Media nodes to extend the media beyond its ending/beginning (either of which will also mean the bug won't occur).

**Comment by rpatros1979** [comment]
Thank you for the confirmation Matt and keep up the great work
