### ISSUE TITLE
[PLAYBACK] Stop playback when loosing focus

### ISSUE THREAD

**Issue by chok** [olive-editor/olive#1804]
**2a80b858** 

**Ubuntu 21.10** 

**Summary**

Not sure if it's normal but when I launch playback and loose focus by swiping to go to a text editor to check things during the playback, it stops. I have to come back to olive to relaunch the playback

**Comment by itsmattkc** [comment]
This was *kind of* intentional, it was written to pause so the playback would be forced to reset some of its state if the viewer was ever closed mid-playback, with the unintentional side effect that *any* hide event would make this pause happen too. I could see how either of these behaviors would be annoying, so I refactored the timers so that reset shouldn't be necessary any more in 2afa7ecafe2a7d7fb54db76ffdc45819e55353c4.
