### ISSUE TITLE
Olive can't find effects

### ISSUE THREAD

**Issue by eszlari** [olive-editor/olive#186]
I'm working on the flatpak for olive: https://github.com/olive-editor/olive/issues/159

Since there is no `make install` target (https://github.com/olive-editor/olive/issues/185), I copy the files manually:
```
install -Dt /app/bin Olive
cp -R effects /app/bin
```
Unfortunately, Olive can't find the effects. Maybe you can add an environment variable for setting the path to search in.

**Comment by itsmattkc** [comment]
In n5bb579e9d1b900d8cc8ae973a7e689aca5a1882c I added the environment variable `OLIVE_EFFECTS_PATH` which will override the default search path for effects.

It is in the `alpha` branch which I wouldn't necessarily recommend packaging (due to its slightly more volatile nature), but I'll be doing a merge with the `master` branch very soon.

**Comment by LeandroStanger** [comment]
@flathub Could help?

**Comment by itsmattkc** [comment]
The `OLIVE_EFFECTS_PATH` environment variable has been merged into master. Hopefully that will help fix this issue.

**Comment by eszlari** [comment]
It works, thanks!
