### ISSUE TITLE
[UI] Remember app settings (including custom shortcuts)

### ISSUE THREAD

**Issue by hyuri** [olive-editor/olive#1930]
**Commit Hash** 
912dcfdb?
I don't know because Olive 0.2 isn't opening right now after my Nvidia GPU stopped working.
But the behavior has been the same in all daily builds I've downloaded in the past few days.

**Platform** 
Pop!_OS 21.10
Windows 10
(happens in both)

**Summary**
Settings are reset to factory default every time I close and open the app. Shortcuts are also reset.

So every time I open Olive I have to change settings to my liking and import the shortcuts again.

When I open an existing project, my custom shortcuts are loaded but app settings are still reset.

Note: Render settings are not saving either. That is to say: if I export a sequence, make a few changes and open the export dialog again, the settings I've just used in the previous export are not loaded, it's reset as well.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
What's most likely happening here is the app is crashing for you before the config gets saved (which happens after the main window closes). Since it doesn't crash on my end (and therefore the config is saved as expected), I can't really address that, but what I have done is added another config save point when the preferences dialog is "accepted" (i.e. OK is clicked) so that if it crashes before close it will have already saved changes earlier. This should solve this issue and therefore I will close it, but if you can get a backtrace for that crash, feel free to make another one.

> Note: Render settings are not saving either. That is to say: if I export a sequence, make a few changes and open the export dialog again, the settings I've just used in the previous export are not loaded, it's reset as well.

#1338

**Comment by hyuri** [comment]
Ah, I see. Nice. But is it feasible for the settings to be saved every time a setting is changed? Some settings are outside the preferences dialog, e.g. "Smooth Edge" and "Scroll Zoom By Default" in the Node Editor.

**Comment by itsmattkc** [comment]
That becomes a lot more complicated, and I think the priority should be tracking down crashes like the one you're probably having. I consider this a stop-gap measure.
