### ISSUE TITLE
[UI] Mask effect is VERY slow on M1

### ISSUE THREAD

**Issue by ImperfectGithub** [olive-editor/olive#1990]
**Commit Hash** : None

**Platform** : Apple M1 Silicon running on macOS Monterey 12.4

**Summary**: Basically as soon as i use a mask effect on anything, the dragging and updating of the mask is INCREDIBLY SLOW and completely unusable, also the export render times seems to be too long for just re-encoding a simple clip, taking as long as 1:40 to convert an MOV file to MP4

**Additional Information / Output**: I don't know how to code, i just made a Github account to send this feedback, since i really like your project, the workflow alone is better than Premiere and FCP IMO, and i'd really like for this to become a fully fledged sotfware one day

**Comment by itsmattkc** [comment]
Thanks for the kind words. I was going to mention how the mask/polygon is calculated entirely on the CPU (rather than most of Olive's pipeline which is GPU driven), including the upconversion to float, but then I realized that latter section could very easily be GPU accelerated and was in fact the biggest bottleneck. So I moved that to the GPU and it should perform a lot better. Please test it out and let me know.

**Comment by itsmattkc** [comment]
Closing for now. Will re-open if necessary.
