### ISSUE TITLE
[UI] Move "Vertical alignment" options to the Text editor toolbar

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#2008]
**Commit Hash** 
409f24be

**Platform** 
macOS 12.3 (all)

**Summary**
I would suggest to transfer the "Vertical alignment" options to the Text editor toolbar as in the following mockup:
<img width="555" alt="vertical" src="https://user-images.githubusercontent.com/5942369/184095507-796cb011-0ac3-4237-acb8-351e73cfa164.png">

It would need 3 new icons that, once again, I would be glad to design and PR. Just let me know if you like the idea and I do it.

Cheers
**Additional Information / Output**

**Comment by itsmattkc** [comment]
I would prefer if you combined some of these related issues into one rather than creating several for every minor issue.

The thinking behind having the vertical align option separate is that they work in different ways (especially internally). The options in the toolbar can be applied to any region of text, but the vertical alignment necessarily affects the entire thing. Internally, it's a completely different mechanism because HTML (used to render text) has fairly limited vertical alignment capabilities. It would take a completely different codepath to connect that to the toolbar.

However I do agree, and even considered while writing it, that it would be more sensible on the toolbar, so I can see what I can do at some point. If you want to PR icons, that would be good, but I'd prefer they looked more like this:
![image](https://user-images.githubusercontent.com/34096995/184184143-74d50a87-3f78-4305-9307-5748c302aef8.png)

**Comment by pgilfernandez** [comment]
I considered the option you said about it affects the whole box and not individual characters... but I still think it would be better to have them all in the toolbar.
I'll design them as you preferred and PR them.

**Comment by pgilfernandez** [comment]
I experimented with the vertical alignment icons having in mind they only get affected as a whole in the text box they are created:
<img width="555" alt="vertical2" src="https://user-images.githubusercontent.com/5942369/185574935-7fcbb885-0d59-4e2b-a7e8-058087b5f68f.png">

Do you like this option better or do you still like the original and more simple idea?:
<img width="555" alt="vertical1" src="https://user-images.githubusercontent.com/5942369/185575063-8123e614-53e6-45da-9655-4f7047f5f8b2.png">

**Comment by itsmattkc** [comment]
I prefer the second one. I think it'll be fairly clear how it works, it's not like there's much use case for "a paragraph" to be vertically aligned.

**Comment by pgilfernandez** [comment]
Hehehe, that's the best reason of that version. It is also a more simple icon that better fits with their neighbors. I'll PR them soon.
