### ISSUE TITLE
[NODES] Selecting a text is having problems after vertical alignment

### ISSUE THREAD

**Issue by porrarafaelmano** [olive-editor/olive#2018]
**Commit Hash**
b361ba8c

**Platform** 
Ubuntu Studio 22.04 LTS

**Comment by wezm** [comment]
I believe this is due to this hack noted in the code where the text of the editor is made transparent and the underlying rendering is relied upon to show what's happening. The editor doesn't appear to take the vertical alignment into consideration though.

https://github.com/olive-editor/olive/blob/b361ba8c51dc79640e77358951b7d4e8f55807f1/app/widget/viewer/viewertexteditor.cpp#L283-L300

**Comment by porrarafaelmano** [comment]
https://user-images.githubusercontent.com/110862268/186043598-56669c44-42a8-400c-844f-d6e2dd06b6ab.mp4

**Comment by elsandosgrande** [comment]
Not sure where that hash is from though, since that's not a valid hash.

**Comment by itsmattkc** [comment]
Known issue. It will be resolved eventually.
