### ISSUE TITLE
Sliding Gaussian blur values can freeze the interface

### ISSUE THREAD

**Issue by feeef** [olive-editor/olive#205]
When used on a 5th generation Intel i7 computer along with an Intel 520 GPU, the Gaussian blur effects is pretty slow and quickly sliding the radius value can freeze the interface, making the application useless for a moment.

I propose isolating the rendering process and displaying a feedback on the sequence viewer showing that the filter is being applied (if the rendering takes more than 1s). Current rendering jobs should be canceled as soon as the values change or the video is scrubbed, and then rendering would be triggered again for the current frame and values.

**Comment by itsmattkc** [comment]
Rendering has been moved to a different thread in 6d2dcecda4ff9b8c5864285b191dc08591b9e969. To an extent, heavy blurs will inevitably cause system lag because they're GPU accelerated and saturating the GPU will cause unresponsiveness in your system, however moving to a new thread should mitigate a lot of this issue.
