### ISSUE TITLE
[EDIT] Crash when stopping audio capture on Windows

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#2065]
**Commit Hash** 

f39a3b0e

**Platform** 

Windows 10

**Summary**

Olive crashes every time I stop an ongoing audio capture using the Record tool.

**Additional Information / Output**
Here's a full crash log as copied form the crash handler:
[crash log.txt](https://github.com/olive-editor/olive/files/9786024/crash.log.txt)

**Comment by dolarfred** [comment]
I noticed the same défault both on macbook pro  X86  (high sierra) and macbook pro ARM (monterey)

**Comment by dev-clavis** [comment]
Olive crash also on my windows 10 when stoping the capture. Is this only on windows and mac or also on linux happening ?

**Comment by dev-clavis** [comment]
I tried some things:
I thought that you have to follow a certain procedure within the node graph to record without crash and tried some different thinks but yet without success. When using the record tool in the timeline I was able to just click in the timeline which would as well start the process as when dragging a box, but when stoping or reaching the right  boundary of that box olive will crash.

Based on the crash msg I think the problem lies somewhere within the node graph.
```
[...]
Crash reason:  EXCEPTION_ACCESS_VIOLATION_READ
Crash address: 0x70

Thread 0 (crashed)
 0  olive-editor.exe!olive::Node::ConnectEdge(olive::Node *,olive::NodeInput const &) [node.cpp : 193 + 0x23]
    rbx = 0xafafa3e0   r12 = 0xafafa790   r13 = 0xecc032b0   r14 = 0xafafa450
    r15 = 0x00000000   rip = 0x9b249542   rsp = 0xafafa370   rbp = 0xed056250
    Found by: given as instruction pointer in context
 1  olive-editor.exe!olive::PreviewAutoCacher::AddEdge(olive::Node *,olive::NodeInput const &) [previewautocacher.cpp : 336 + 0x33]
    rbx = 0xafafa3e0   r12 = 0xafafa790   r13 = 0xecc032b0   r14 = 0xafafa450
    r15 = 0x00000000   rip = 0x9b28c7ea   rsp = 0xafafa3c0   rbp = 0xed056250
    Found by: call frame info
 2  olive-editor.exe!olive::PreviewAutoCacher::ProcessUpdateQueue() [previewautocacher.cpp : 270 + 0x11]
    rbx = 0xafafa3e0   r12 = 0xafafa790   r13 = 0xecc032b0   r14 = 0xafafa450
    r15 = 0x00000000   rip = 0x9b28e592   rsp = 0xafafa420   rbp = 0xed056250
    Found by: call frame info
 3  olive-editor.exe!olive::PreviewAutoCacher::TryRender() [previewautocacher.cpp : 645 + 0x7]
    rbx = 0xafafa3e0   r12 = 0xafafa790   r13 = 0xecc032b0   r14 = 0xafafa450
    r15 = 0x00000000   rip = 0x9b2906b5   rsp = 0xafafa480   rbp = 0xed056250
    Found by: call frame info
 4  Qt5Core.dll + 0x1de381
    rbx = 0xafafa3e0   r12 = 0xafafa790   r13 = 0xecc032b0   r14 = 0xafafa450
    r15 = 0x00000000   rip = 0x047be382   rsp = 0xafafa610   rbp = 0xed056250
    Found by: call frame info
[...]
```

Node.cpp (last line is 193)
```
void Node::ConnectEdge(Node *output, const NodeInput &input)
{
  // Ensure graph is the same
  Q_ASSERT(input.node()->parent() == output->parent());

  // Ensure a connection isn't getting overwritten
  Q_ASSERT(input.node()->input_connections().find(input) == input.node()->input_connections().end());

  // Insert connection on both sides
  input.node()->input_connections_[input] = output;
  output->output_connections_.push_back(std::pair<Node*, NodeInput>({output, input}));
[...]
```
When I trust the line of the crash msg. then I would assume that `output->output_connections_.push_back(std::pair<Node*, NodeInput>({output, input}));` fails, because of empty pointer.
When assuming this, I would say it has something to do with **output_connections_** of output

Finally I ask myself if _ConnectEdge(...)_ is used somewhere else and
* will it trigger a crash too?
 * based on the name I tried to play within the node graph without crash
 * what is different when recording than just dragging an audio file into the timeline (which creates a graph as well) or just connecting Edges ?
