### ISSUE TITLE
[CACHE] Is it possible to adjust the size of the cache? (My cache folder size is larger than my project folder size)

### ISSUE THREAD

**Issue by kburchfiel** [olive-editor/olive#2080]
**Commit Hash** 

6ce80f44

**Platform** 

Windows 10

**Summary**

After caching all of the 8K/24 fps videos in my project folder, I noticed that the size of my cache folder (44.7 GB) is larger than the size of my project folder (28.9 GB), even though I had cleared the cache folder beforehand. 

This isn't a serious issue for me, as the cached video clips play just fine, but I'm wondering whether the cached videos are of a higher quality than they need to be, and whether there is a way to specify a lower cache quality. (For instance, I'd be fine with 720p cached videos, since I don't need every detail rendered in order to figure out how to edit each clip.)

**Comment by itsmattkc** [comment]
In the sequence settings (right click sequence, click "Properties"), you can change the preview resolution which will affect the cache resolution. There are also ways to limit the disk cache's maximum size in Tools > Preferences > Disk Cache. There is also a chance that some stray files may not be getting accounted for, which can be resolved by manually deleting the disk cache folder.

Otherwise I should mention the cache generally _will_ be larger than your source footage (if you're caching everything) because less compression is specifically how the cache produces faster results.

**Comment by kburchfiel** [comment]
Ah, that's really interesting--I wouldn't have guessed that a larger video would be faster to process, but the compression explanation makes sense. And thank you for the explanation about how to change the preview resolution.

Ken
