### ISSUE TITLE
[CRASH] Curve Editor on volume parameter (mp3)

### ISSUE THREAD

**Issue by Avispa** [olive-editor/olive#2133]
### System

**Commit Hash** de8d50e
Platform: Windows 10

### Steps to Reproduce

1. Load mp3 audio file into timeline.
2. Set (in case it matters) 4 key frames with different volumes (first one infinite low, last 0 dB)
3. Switch to _Curve Editor_.
4. Click _Volume_ entry.
5. Freeze a.k.a. crash without dump.

**Comment by ThomasWilshaw** [comment]
Does this happen with most MP3 files or just a specific one?

**Comment by Avispa** [comment]
> Does this happen with most MP3 files or just a specific one?

At least with two so far:
1. reproduced on new project with same mp3
2. reproduced on new project with completely different mp3

I just mentioned mp3 because it's actually one. Didn't test on any other audio file format yet.

**Comment by Avispa** [comment]
Same for m4a.

#### Side note:
.. though kinda irrelevant for this issue: _mp3_ uselessly adds a video track to the timeline; while in contrast _m4a_ for example does not.

**Comment by ThomasWilshaw** [comment]
I can confirm this is happening on Windows 10 too. I think the issue is caused when you set a keyframe of `-inf` and then try to draw the curve in the UI, Olive hangs as it's in an infinite loop. I ran Olive through Very Sleepy whilst doing this and it pointed to `olive::CurveView::drawBackground`, specifically this section around line 129:
```
  do {
    y_grid_interval = qRound(y_interval * GetYScale());
    y_interval *= 2.0;
  } while (y_grid_interval < minimum_grid_space_);
```

Running through a debugger it seems that `GetYScale` is being set to 0 the loop never ends.

**Comment by mcDandy** [comment]
> Same for m4a.
> #### Side note:
> 
> .. though kinda irrelevant for this issue: _mp3_ uselessly adds a video track to the timeline; while in contrast _m4a_ for example does not.

MP3 might contain album cover.
