### ISSUE TITLE
[UI] Panels are Scaled/Zoomed In When Windows System Fonts are Scaled

### ISSUE THREAD

**Issue by LisaBBC** [olive-editor/olive#2182]
**Commit Hash** 

**Platform** 

Windows 10
**Summary**
I use scaled fonts in Windows and in the UI all the panels /  are scaled as well. Using Zoom - or Zoom = has no effect. I can only resize the panels slightly, not enough to make the elements as viewable as needed.

**Additional Information / Output**
<img width="958" alt="image" src="https://user-images.githubusercontent.com/73590484/221344237-877482e1-4704-4baf-90e7-b2eddcbdb298.png">

**Comment by itsmattkc** [comment]
To an extent, this is expected behavior - Windows scaling doesn't only scale text, it scales all UI objects to be proportional. However it does appear from your screenshot that Olive is being scaled slightly more than the Windows scaling, since its text is noticeably larger than the titlebar.

Unfortunately, I can't recreate this myself. At higher DPIs/larger scales on Windows, Olive still appears to scale proportionately. I think you'll have to provide more information about exactly what settings you're using.
