### ISSUE TITLE
[EDIT] Sequence viewer freezes while playhead is being moved too quickly

### ISSUE THREAD

**Issue by tjb0607** [olive-editor/olive#2198]
**Commit Hash**
2c2df99

**Platform**
Linux (X11)

**Summary**
If you drag the playhead too quickly with your mouse, the sequence viewer isn't updated at all while it's moving - your mouse has to come to a stop for long enough for a frame to finish rendering.

**Additional Information / Output**
Steps to reproduce:
1. Import a long enough video (e.g. an hours-long Twitch VOD)
2. Zoom out far enough to see the entire video in the timeline.
3. Click+drag the playhead across the timeline smoothly, making sure to keep the mouse continuously moving.

I would expect to see frames rendering to completion as quickly as the renderer can handle, but while the playhead is moving, the renderer never gets a chance to finish even a single frame, and thus the sequence viewer freezes entirely until you stop moving your mouse.

Demonstration:
https://www.youtube.com/watch?v=5CsX8XS1iVo

Long-term, I'd love to also see even more improvements to scrubbing performance, such as snapping to keyframes if you're scrubbing quickly enough / zoomed out enough. I believe mpv does this and has fantastic scrubbing performance as a result.

**Comment by itsmattkc** [comment]
Generally I don't keep "performance suggestion" issues like this open because performance is something I'm constantly working on; I don't need reminders to do it.

Some of your suggestions aren't really appropriate for a video editor. "Snapping to keyframes" only really works when you have a single video source and aren't concerned about precise frame accuracy. Olive is a video editor/compositor where the exact frame you're seeing is important, and if you have multiple sources in a composition, it's going to be disconcerting even while scrubbing if some of them end up being the wrong frame because you're not respecting that frame accuracy.

That being said, I did find a way to improve the visual appearance of scrubbing in e9c97407aadfbd02afaa55a27f14bc3dc0a537dc, you may find this helps.

I should also mention that you can use caching to improve scrubbing performance, though that subsystem is currently going through a rewrite and therefore may be rough around the edges.

**Comment by tjb0607** [comment]
makes perfect sense, and e9c9740 is _such_ a massive improvement, thank you so much!
