### ISSUE TITLE
[CRASH] Windows 7 incompatible? Missing Windows API symbol in kernel32.dll

### ISSUE THREAD

**Issue by Dim0s** [olive-editor/olive#2215]
Entry point CreateFile32 was not found in the KERNEL32.dll dynamic library

I know that this error is due to incompatibility of OS, if so change the minimum allowable OS in the description on the site.

**Comment by Simran-B** [comment]
Please include the version / commit hash of Olive.

Is this a 32-bit Windows?

**Comment by Dim0s** [comment]
last version Portable (64-bit) Olive 0.2 from official website - runing on wondows 7 x64 sp1

**Comment by itsmattkc** [comment]
We use `windows-latest`, so you're probably right that we've been bumped up to VS2022.

I didn't know they were dropping support for 7 with this release, but if so, this can probably be fixed by dropping it to `windows-2019` (or installing an older VS toolset and directing CMake to that, but that'll take more work and probably more time on the CI for each build).

**Comment by Simran-B** [comment]
Yeah, should be a simple fix in that case. For as long as GitHub supports the windows-2019 environment, that is. I would assume that it stays around for at least 2 more years.

**Comment by TrickyClock** [comment]
I found that when OpenImageIO.dll and OpenImageIO_Util.dll are replaced with versions from e7982239b8c736baab9ed29ba89e7a3f1342700a (expired action) and also replacing some other required stuff for the old OpenImageIO, It works fine.

If I'm wrong about something, please let me know.

**Comment by ik0jre** [comment]
I get some issue on Windows 7 intel 64bit, olive Olive-245a4f6d-Windows-x86_64-Portable.

**Comment by thevbw** [comment]
+1 not working, can't locate CreateFile2, Win7 x64, Olive 245a4f6d installer

**Comment by itsmattkc** [comment]
Turns out the issue was this specific line in OpenEXR, that's the only code calling `CreateFile2`: https://github.com/AcademySoftwareFoundation/openexr/blob/2205245599709d88013b7da03b176c1c73c8aedb/src/lib/OpenEXRCore/internal_win32_file_impl.h#L323

Thankfully they provide a path for Windows < 8.1 still, you just have to tell it explicitly which version to build for, which we do now. Latest commit should work on 7.

**Comment by ik0jre** [comment]
I confirm. Portable version 7fa69ea5 works on windows 7.
TNX
