### ISSUE TITLE
[Bug] Jumping time markers in Timeline

### ISSUE THREAD

**Issue by JanSeW** [olive-editor/olive#222]
Hey guys,

in the December 2018 build of Olive there is a graphic bug in the timeline. If you activate smooth-scrolling and then play the project, the time jumps around every second at the top of the timeline. This happens regardless of window size and scaling.
I myself use Linux Mint 19.1 Cinnamon and the proprietary NVIDIA drivers (390.77) with the GTX 560 Ti. Maybe this is also the case with other graphics cards. 
[Video with bug](https://cloud.abi19.eu/index.php/s/8Ajpda9H86LwNLb)

Thxalot,
JanSe

**Comment by itsmattkc** [comment]
Hi JanSe,

Technically, this isn't a bug, but rather an artifact of the way the timecodes are drawn. It starts with the first one timecode on screen from the left and skips any that it doesn't have space for. For example, at one point it draws "00:00:08;00", doesn't have room for "00:00:09;00", and so it skips to "00:00:10;00". But once "00:00:08;00" is offscreen, it instead draws "00:00:09;00" and then skips to "00:00:11;00", leading to the jumping effect you describe.

Regardless, it certainly is a jarring and mildly offputting effect, and I can probably write something so that it always skips the same timecodes (i.e. always skips from "00:00:08;00" to "00:00:10;00" instead of readjusting in the above example).

**Comment by itsmattkc** [comment]
This should be fixed as of 8d8e00c629b1ad0e70e39d527c6e248eb3babfae
