### ISSUE TITLE
Build fails on ARM

### ISSUE THREAD

**Issue by luigino** [olive-editor/olive#247]
On openSUSE Tumbleweed, both armv7l and aarch64.
Could it be on account of using OpenGL ES?

**Comment by itsmattkc** [comment]
This is a somewhat known issue, in that the Flatpak apparently doesn't compile on ARM due to some missing declaration: https://github.com/flathub/flathub/pull/794#issuecomment-450123703

I wonder if changing this one declaration (or perhaps adding an include) would allow it to build. I don't personally have an ARM-based computer but I could probably test in an emulator.

**Comment by luigino** [comment]
I forgot to add my build [log](https://github.com/olive-editor/olive/files/2729460/olive_arm.txt) and it looks like it's more than one missing declaration.

Like I said, it seems to me this is a limitation of GLES, but I haven't touched this stuff in almost 20 years.

**Comment by itsmattkc** [comment]
It does appear you're correct, it seems Olive is not fully GLES 2.0 compatible and that's the root cause of this issue.

**Comment by itsmattkc** [comment]
Olive standardizes around OpenGL ES 3.2 Core now. Hopefully that solves this issue.
