### ISSUE TITLE
preview while playback not updating with file sequences on high fps

### ISSUE THREAD

**Issue by PostPollux** [olive-editor/olive#248]
When i playback an image sequence (png 1.7mb each frame) I get the following problem:
(I keep the "sequence" fps at 25 fps and I only change the fps of the clip (imported image sequence) in the timeline)
With 25 fps it works quite well, it rarely happens that the preview is freezing.
The more I increase the framerate the earlier it happens that the preview is just freezing while the rest continues to update. As soon as I pause the playback, the preview updates with the correct image again.
With e.g. 60 fps I see maybe a quarter of a second and then it doesn't update anymore until I pause again.

I guess it's because of the huge amount of data to be read from the harddrive. But in this case I think it would be better if the playback is maybe not smooth 25 fps but you still get to see constant updates maybe with a small red indicator that informs you that you are not running the desired framerate. Or something like that.

Specs:
Olive b828171, Linux Manjaro, Intel I7 8550U, UHD620

**Comment by itsmattkc** [comment]
In Tools > Preferences, there's an option between "Accurate Seeking" and "Fast Seeking". See if the issue is reduced when set to "Fast Seeking".

**Comment by PostPollux** [comment]
Yes, the issue is reduced a bit, but still not really usable for filesequences. I've made a screencast where you can see it:

https://photos.app.goo.gl/8LjU8EMT1HZeMxhc8

As you can see it's not the whole viewport that isn't updating anymore, but only the file sequence clip itself. The higher the framerate, the earlier it stops updating. With fast seeking I get a framerate of maybe 1 fps instead of not updating.

Anyway, if you want to try it yourself, here is the filesequence to download: https://my.pcloud.com/publink/show?code=XZ3n5s7ZLKC0YHbl2pJn5fiefK6lYj1NnnzX

p.s. Thanks so much for making this awesome piece of software. It's the most promising open source cross plattform video editor out there. I'm so happy that professional video editing may finally come to linux! :)

**Comment by itsmattkc** [comment]
So, early on in Olive's history it was discovered that multithreading, while drastically improving the performance for most codecs, would produce garbled results on still images. So for various image formats, multithreading was disabled. This led to the poor image sequence performance you described.

However upon experimenting with this issue, I decided to try it with multithreading enabled again and surprisingly is actually worked perfectly.

In fee2c457f264cebc70fee3b45f69b356a860e31c, I've re-enabled multithreading on images. If you don't see a garbled image, you should see significantly better performance with image sequences (60ms per frame to under 4ms per frame on my end).

Just in case some setups still lead to garbled results on still images, I've added an option to disable it again, but I have a feeling Olive has just evolved so much since then that it's just no longer an issue.

**Comment by PostPollux** [comment]
What an improvment! I now get ultra smooth 60 fps playback with the same image sequence! Thank you so much! Until now I didn't get any problems with the multithreading. If I should encounter a problem I will let you know!
