### ISSUE TITLE
Title shown as opaque black area object instead of text object

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#278]
### Current behaviors

If add some title it shown just as opaque black area object

![pic.1](https://i.imgur.com/9NtRAjR.png)

It is reproducible for me in *Olive* `d51ce53` and `607d361` builds (not sure when this issue emerge)

### Expected behaviors

Title should be shown as text object (by design)

When I tried *Olive* `2b7103e` week ago all seems work as expected

![pic.2](https://i.imgur.com/muB9NvQ.png)

### System details

Here is my PC spec

![pic.3](https://i.imgur.com/iaKu2M1.png)

**Comment by itsmattkc** [comment]
Hi, if you run Olive from command line, is there any command line output when you place a title that comes up black?

**Comment by Symbian9** [comment]
Here is terminal output after title added

```
...
r300 FP: Compiler Error:
build_loop_info: Cannot find condition for if
Using a dummy shader instead.
r300 FP: Compiler Error:
build_loop_info: Cannot find condition for if
Using a dummy shader instead.
QFileInfo::absolutePath: Constructed with empty filename
```

**Comment by itsmattkc** [comment]
Huh... I haven't seen this before. I assume a shader isn't compiling properly.

To test this (assuming you're compiling from source), try commenting out or removing the line `enable_shader = true;` from `effects/internal/texteffect.cpp` (around line 27). If it's just the shader, the text should start working again (minus the ability to make set a drop shadow).

**Comment by Symbian9** [comment]
> To test this (assuming you're compiling from source)

NO! I not compile it by myself! I always use your AppImage-builds.

Also, as mentioned above, title work normally if I use `Olive-2b7103e-x86_64.AppImage` compiled by you.

Please, try search what happen in `master` branch since `2b7103e` that now break this shader in few last nightly builds.

**Comment by itsmattkc** [comment]
Sorry, I get the feeling I came off sounding accusatory, I don't think I explained myself very well.

I wasn't implying that you were compiling Olive incorrectly, I was just trying to narrow down the issue. GLSL shaders are compiled at runtime on your GPU, and it's usually up to the drivers as to how they're compiled, meaning shader code can be compiled differently, have different results, or even completely fail depending on which GPU, OS, and driver the user is using (e.g. #172).

A broken shader _could_ result in a black screen even when the shadow is disabled, as the shader is still "active" at that point but acting as a passthrough. From what you've shown, I believe the issue is that the shadow shader is indeed not compiling correctly, however in earlier builds a bug was causing Olive to not find the shaders, which meant it was never loaded and therefore never used (ironically providing a better outcome).

The fixes I see are:
* Try to fix the GLSL code so that it compiles on your GPU (I'll try to research the AMD RS600M)
* Disable shadow shader altogether if it's disabled so that if it fails to compile, it won't break the entire clip

I'll probably try to do both and push a fix to this later today, thanks for letting me know!

**Comment by itsmattkc** [comment]
Try 59ae02d8dc7529866d319199e3d806d985abcbe7, I've implemented a workaround (it won't try to use the shader if it can't compile it) so you can at least use the text effect (without shadow support). Without your hardware it would be difficult to actually determine the core issue, but I've made an adjustment to the GLSL code so let me know if that makes a difference to being able to make a shadow.

**Comment by Symbian9** [comment]
> Without your hardware it would be difficult to actually determine the core issue

Maybe, I could run some benchmarks on my PC and then give you needed results/logs?

**Comment by itsmattkc** [comment]
Yeah if they still don't work, feel free to make a new issue and send me the error messages you get when trying to use text shadows.
