### ISSUE TITLE
Title still shown as opaque black area

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#284]
> I've implemented a workaround (it won't try to use the shader if it can't compile it) so you can at least use the text effect (without shadow support)

Still has title as black area ("Shadow" is disabled)

![pic.1](https://i.imgur.com/9AN3M7w.png)

### Terminal Log

```
$ ./Olive-59ae02d-x86_64.AppImage
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/mint/Downloads/Су-27_прополз.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2016-11-23T07:24:52.000000Z
  Duration: 00:01:23.87, start: 0.000000, bitrate: 1219 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 1122 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2016-11-23T07:24:52.000000Z
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 93 kb/s (default)
    Metadata:
      creation_time   : 2016-11-23T07:24:52.000000Z
      handler_name    : ISO Media file produced by Google Inc.
[swscaler @ 0x7f3e8c5e49e0] Warning: data is not aligned! This can lead to a speed loss
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/mint/Downloads/Су-27_прополз.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2016-11-23T07:24:52.000000Z
  Duration: 00:01:23.87, start: 0.000000, bitrate: 1219 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 1122 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2016-11-23T07:24:52.000000Z
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 93 kb/s (default)
    Metadata:
      creation_time   : 2016-11-23T07:24:52.000000Z
      handler_name    : ISO Media file produced by Google Inc.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/mint/Downloads/Су-27_прополз.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2016-11-23T07:24:52.000000Z
  Duration: 00:01:23.87, start: 0.000000, bitrate: 1219 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 1122 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2016-11-23T07:24:52.000000Z
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 93 kb/s (default)
    Metadata:
      creation_time   : 2016-11-23T07:24:52.000000Z
      handler_name    : ISO Media file produced by Google Inc.
r300 FP: Compiler Error:
build_loop_info: Cannot find condition for if
Using a dummy shader instead.
r300 FP: Compiler Error:
build_loop_info: Cannot find condition for if
Using a dummy shader instead.
QFileInfo::absolutePath: Constructed with empty filename
```

**Comment by itsmattkc** [comment]
Do any of the other GLSL effects work for you?

**Comment by Symbian9** [comment]
> Do any of the other GLSL effects work for you?

Is there any benchmark for Linux for test which GLSL effects supported on users PC?

**Comment by itsmattkc** [comment]
Try effects like "Ripple" and "Corner Pin" for GLSL-based effects. If they have no effect or produce a black screen, that means they're failing too.

Weirdly it seems the code I wrote still isn't picking up the compile errors. I've added more debug log info to 342e4c765a71daad6e12741eb73a003fabe6f20e to help narrow down the issue.

**Comment by Symbian9** [comment]
Version: `Olive-b7f1fae-x86_64.AppImage`

"Ripple" and "Corner Pin" enabled, and seems work as expected:

![pic.1](https://i.imgur.com/VgB0o9y.png)

In same time "Toonify" has no any effect if it enabled

![pic.2](https://i.imgur.com/jrwrHy3.png)

But few effects give same black opaque area for me, as "Title":

- all "Blur" effects;
- "Fisheye";
- "Volumetric Light".

P.S.: I will try `342e4c7` now and will report in hour.

**Comment by itsmattkc** [comment]
Do they all have the same error? i.e.
```
r300 FP: Compiler Error:
build_loop_info: Cannot find condition for if
Using a dummy shader instead.
```

**Comment by Symbian9** [comment]
Just download `Olive-e0f6280-x86_64.AppImage` and test it: nothing changed for me, so all described in comment above still actual

- https://github.com/olive-editor/olive/issues/284#issuecomment-452916627

**Comment by itsmattkc** [comment]
I'm sorry to say, but everything I can find about the `r300 FP` is that it's simply too old for most GLSL compilers to compile for properly, which is why a lot of these effects are failing. [This thread on Stack Overflow](https://stackoverflow.com/questions/18666432/why-am-i-getting-r300-fp-compiler-error-while-attempting-this-opengl-tutoria) seems to cover this same issue. When it comes to errors like `Too many hardware temporaries used.`, the compiled shader just isn't efficient enough for the R300 architecture.

What I can do is the fix I was planning (but ended up trying another first), which is only bind the shader if the shadow is enabled. Try 9f3469857af14cf6d73148cb8c7d977d4f5a2016, the text _should_ work under normal circumstances (but should turn black if you enable the shadow).

Unfortunately, Olive doesn't have much in the way of software fallbacks for some of these other effects that are failing. Perhaps in the future there will be.

**Comment by Symbian9** [comment]
Okay, what you think about adding into *Olive* preferences tab for enabling/disabling effects (and option) by levels? Something like that:

> **GLSL Shaders support level**
> - [x] GLSL 1.00 ES
> - [ ] GLSL 2.00 ES
> - [ ] ...
> - [x] GLSL 1.10
> - [x] GLSL 1.20
> - [ ] ...
> - [ ] GLSL 1.50
> - [ ] ...

So, user could fully control which *level of shaders* should be enabled for this session and disabling some of them will also hide related options from UI and Actions list (for preventing bugs such bugs as above) and on import existed projects with such effects (temporary ignoring them). Maybe, later there we could fix all bugs, including those that at this moment look like non-solvable!

P.S.: I highly respect that nowadays many users has high-end powerful PC and for those users all functions in *Olive* should be usable.

But lets make *Olive* usable on older low-end PC too! 😉 (maybe with some limitations, by manually disabling unsupported options)

**Comment by itsmattkc** [comment]
I'm definitely open to supporting older low-end hardware. For the internal (C++ based) effects, I can certainly make sure they've all got software fallbacks (e.g. I can reuse some old code to make a software fallback for text shadows pretty easily).

The other GLSL effects would be a little more tricky because they're loaded externally so Olive itself has little awareness of their requirements and inner workings. Likewise, a software fallback for these would be  a completely different paradigm as that code would need to be compiled separately (with GCC or something).

It's also difficult to determine whether a GLSL version is actually problematic, for example "Box Blur" is version 1.10 but still manages to exceed the limitations of R300.

I could write a `--no-shaders` equivalent so that Olive won't try to use any shaders, but then R300 users will miss out on the GLSL effects that do work (such as "Ripple").

**Comment by Symbian9** [comment]
> I could write a --no-shaders equivalent so that Olive won't try to use any shaders, but then R300 users will miss out on the GLSL effects that do work (such as "Ripple")

Adding that would be useful at least for testing purposes while there are no "stable" releases, so if this is simple task, add that.

If possible, add also `--test` option for advanced testing purposes, where `$ ./Olive-*.AppImage --test=shadows` could be used for test all bundled effects executing without launch *Olive* in GUI mode.

> Try `9f34698`, the text should work under normal circumstances (but should turn black if you enable the shadow).

Yes, now this workaround works for "Title" ;-)

P.S.: This issue should be marked with tags: `known issue`, `low-end PC`

**Comment by itsmattkc** [comment]
Yeah I'm not sure if it is possible to test the shaders, Olive already tests if they compile (and apparently they do since the last fix didn't change anything), it looks more like the shaders are crashing during runtime and I'm not sure if I'm able to detect that (if someone knows more about this, let me know).

A shader disable option should be fairly simple for testing purposes, though apart from a software fallback for the text shadow, I'm not sure what can be done for this issue.

**Comment by itsmattkc** [comment]
Reimplemented software shadow for the text effect, try it in 20f4b8d4c777209865e0f7c3baecf8f79374851d (Preferences > General > Use Software Fallback When Possible).

**Comment by Symbian9** [comment]
Well, "black screens" still appear if add some of next effects

- all "Blur" effects;
- "Fisheye";
- "Volumetric Light".

If add "Toonify" effect there are NO black screen, but also there are no any effect. (seems like not working for me)

**Comment by alcomposer** [comment]
@itsmattkc you could always do what Davinci Resolve does: check to see if GPU is compatible on startup?

**Comment by itsmattkc** [comment]
@alcomposer As I mentioned earlier in this thread, I'm not sure if I can. Most of the failing effects compile properly, i.e. it's not about incompatible GLSL versions or specifications (most of Olive's shaders are 1.10 regardless of whether they fail on r300 or not). They just seem to crash at runtime as the r300 supports very limited operations compared to modern GPUs (and apparently most shader development and optimization occurred after it was discontinued). I'm not even certain I can detect these crashes since as I said they compile properly. I wouldn't want to disable all shaders because that means r300 users would miss out on the shaders that do work correctly.

The best I could probably do is maybe detect for r300 (or any other architectures with compatibility issues) and show a warning. Luckily, issues like this only really seem to affect older GPUs, even modern low-end GPUs seem to support Olive's effects fine, so I think as long as there are software fallbacks for older GPU users, that should cater to everyone.

**Comment by alcomposer** [comment]
Sorry, I didn't notice your original posts. If there is a software fallback, it would be good to have a way of knowing if the effect is rendered on GPU Vs CPU. (possibly some sort of indicator next to the effect)

**Comment by itsmattkc** [comment]
I've added Frei0r support in d00ad46f268a87ca3bbc989b62a71bea85584d75 which includes many CPU-based effects that I think provide alternatives to GLSL effects (as well as an extra architecture/API to add more effects yourself). I believe this should address this issue, if a GLSL effect doesn't work, look for a frei0r alternative.

**Comment by Member1221** [comment]
Afaik glGetError also returns shader errors at runtime

**Comment by Member1221** [comment]
As well it could be somewhat trivial to parse the preprocessor macro of the GLSL shader and get its version, using that to map out different GLSL versions and OpenGL support.
