### ISSUE TITLE
"Effects Control" widget overlap "Sequence Viewer" widget

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#298]
![pic.1](https://i.imgur.com/X6SBPJh.png)

Seems like this happen due to long font names shown on "Font:" drop-down list button

![pic.2](https://i.imgur.com/Zx7w80V.png)

**Comment by itsmattkc** [comment]
This is just one of those things you have to wrestle with with Qt layouts it seems. Olive tries to set the effects area to the minimum width suggested by the area's contents (mainly so the keyframe controls don't get clipped off the right side), but minimum width is very forceful in Qt, so much so that it can lead to this effect: widgets overlapping other widgets.

I figure I may as well remove the minimum width (ee019517b1696ece9852eb80e85ee0ad3ef65653), that way if people with limited screen space want more area for other things, they can do so, and it'll prevent this sort of thing from occurring.
