### ISSUE TITLE
[EDIT] Support for Interchange / OpenTimelineIO

### ISSUE THREAD

**Issue by Cambloid** [olive-editor/olive#310]
https://github.com/PixarAnimationStudios/OpenTimelineIO

**Comment by Cambloid** [comment]
Especially for professional tools is interoperability very important

**Comment by frink** [comment]
Until it becomes an accepted standard this is probably more of a "bragging rights" thing than something that is highly practical. Really, the bigger problem is how we managed very large projects and distribute them across a global diverse team. I don't believe that anyone is ready to answer that question yet. Until we do, formats like this will yield little more than a distraction from the main objective of creating an intuitive pro-grade NLE.

**Comment by BrimsonBhin** [comment]
@frink I believe it's less about bragging rights and more about having concern for the future

Some of Olive's flaws were caught early in development. Some examples that people addressed

- Code quality/maintainability
- Pixel/Color management
- The need to utilize proper libraries/apis and have actual support
  - OpenColorIO for color management
  - OpenTimelineIO for formatting/storing information
  - OpenImageIO for reading images

Imagine the state of Olive years down the line without such issues addressed. The code-base becomes complex and unreadable. Workarounds were made so the developers can succumb to feature requests. Someone requests something like OpenTimelineIO support, but it's too late.

**Comment by frink** [comment]
My concern is that we don't over engineer. If OpenTimelineIO makes sense then by all means let's use it. Even more than video timelines, I wish DAWs had a standard interchange format. Cakewalk, Nuendo and others have published their format but there's always a problem that nobody is happy with the accepted format...

https://xkcd.com/927/

Time series data is not difficult to catalog and display. But we make it nearly impossible to interchange. If Pixar is the savior then by all means let's do it. But if this is just a means to support some competing standard then we should probably wait until there is a clear winner.

I'm obviously not familiar with OpenTimelineIO so I should probably back off and let the experts talk or go read the spec or something...

**Comment by frink** [comment]
After a lot more reading I realize that while my views on this have grown my post did not. Forgive me...

Yes. Olive SHOULD include OpenTimelineIO at some point but it is not the golden goose that everyone seems to think that it is...

> **From [Pixar's Repo](https://github.com/PixarAnimationStudios/OpenTimelineIO):**
>  OTIO is not a container format for media, rather it contains information about the order and length of cuts and references to external media.

Encapsulation is a big part of making things portable. Also there is the idea of submixing low resolution proxies for different purposes both audio and video. I've been pushing for OpenTimelineIO in Ardour and I think that will probably happen at some point. But @x42 has a good point that Ardour will not edit or render video so having a bunch of clips doesn't really help there.

What we really need is a way to export PART of a project as a submix along with all the timeline information like markers etc. But we need to allow submixing as part of the export process. A few examples might be:

- **Color Grading** most studios color grade after the final cut is completed. But there is almost always some re-cutting that goes on and those conforming/reassembling needs to import the new edits. The problem is that the color grading only works on a single video timeline as opposed to at the clip level. Alternately, some editors like Lightworks tend to do coloring at the clip level. Both interactions need to be supported. If it's the final composite that is edited the reassembly should also import a new version of the render video in addition to changing marks on the timeline.

- **Compositing** various elements of the composite may need to be exported from several places and synced to a single master timeline. The timeline might start with only the editor marks and the backing footage with the actors. Then various elements may need to be synced and brought in. Compositing is interesting because it's cutting film in 3D. Depending on how it's done, the composite may happen before, after or during the cutting process. Understanding what needs to change hands is dicy. 

- **Film Scoring** - The composer needs some video but a rough comp in a lower resolution is fine as long as the timing is relatively set. Likewise, the composer might want to send the audio back via OTIO with his markers on where the most dramatic parts of the score fall. This could turn firm scoring into a more collaborative process between composer and editor. (Really this has been happening more and more for years on paper with SMPTE codes)

- **Foley** - Here the Foley needs a good picture to create sounds in sync and a scrap dialog and music track. But any sound effects added temporarily by the cutting room need to be exported in place so that the sound designer has the ability to manipulate these individual clips. However, when the foley sends things back it should be only a few stubs monster noises etc. But it may be hundreds of new markers...

_So my conclusion is that OpenTimelineIO is awesome. But only a part of the whole. We need to be able to slice and dice the export with submixes of both audio and video sometimes at proxy resolutions and sometimes at better than final quality depending. Managing these source files (even the throw away stuff) is just as important as interchange of the timeline makers._

PS - Ardour has been talking abou including OTIO which could have huge implications for film. Harrison Consoles is one of the big supporters of Ardour and also one of the few to make massive consoles for mixing film audio. If Mixbus gets OTIO it will likely force all the other DAWs to embrace OTIO too just to keep up. (Even though Mixbus is relatively small in the usage slice of the pie...) So that could be very exciting for this whole thing...

Thoughts?

**Comment by itsmattkc** [comment]
Initial support for OpenTimelineIO has begun and continued in various pull requests. I think this can be closed now.
