### ISSUE TITLE
VEGAS Pro features

### ISSUE THREAD

**Issue by main-gi** [olive-editor/olive#336]
(All these refer to an action you would perform on the timeline to change a param)
Drag the top left/right of a clip towards itself (so drag top left to the right, or top right to the left): Change fade/transition time (I guess these would have to work like keyframes)
Drag the bottom left/right of a clip towards itself: Change snap setting (Honestly I did not use this very much in Vegas so I wouldn't mind if this was changed to something else :P)
Drag the top of a clip downwards: Change opacity if video, volume if audio
Overlap two clips: Crossfade them instead of replacing them (but note that this is indeed two clips in the same position on the same track)

Knowing the Premiere-based workflow though this might need better functional descriptions if you haven't seen these effects used in Vegas :P

**Comment by BrimsonBhin** [comment]
I never heard of a Las Vegas editor. You meant to say **_Vegas Pro_**? lol

Yeah, the 1st and 4th features you proposed are in another video editor called **_Shotcut_**. Would like to see those features here as well

![image](https://user-images.githubusercontent.com/40442071/51410168-0ac40500-1b21-11e9-9dac-7416ce0cd0e6.png)

**Comment by oc1024** [comment]
> Overlap two clips: Crossfade them instead of replacing them (but note that this is indeed two clips in the same position on the same track)

Indeed, I often crash the video editor or permanently break audio and video links because overlaying a video "eats" the other clip's video without removing audio. This would turn this bug into a feature.

> Drag the top left/right of a clip towards itself (so drag top left to the right, or top right to the left): Change fade/transition time (I guess these would have to work like keyframes)

The transitions we already have work very similarly, although you have to add then first. Personally, I think something like an "Add Transition" button at the corner (visible when mousing over) would make it easier to implement, easier to discover, and keep the older functionality.

**Comment by alcomposer** [comment]
A huge inspiration for Olive is already Sony Vegas (or whoever owns it now).

**Comment by main-gi** [comment]
I know @itsmattkc well; he hasn't actually used Sony Vegas, and he used Adobe stuff for his previous video projects before this editor. :P I certainly have though, so I hope my descriptions are good enough for the functionality. And yeah now it's MAGIX or whatever.

As for "Las Vegas": https://ksr-ugc.imgix.net/assets/001/953/188/d8e52bdfec631b08d2cf4ac447fb34b1_original.jpg

**Comment by miltonics** [comment]
I would greatly love the ability to directly manipulate aspects of the sound or video tracks with handles. I have done quite a bit of editing with vegas pro, it was the only thing keeping me from jumping to linux. Once I found Olive I was impressed enough to make the jump!

**Comment by miltonics** [comment]
Coming from Vegas I developed a specific technique for removing um's and uh's from an presentation or interview. I cut the audio, remove the um and spliced the audio back together. 

In Vegas this was a matter of cutting, deleting, and then dragging the files over each other to create an automatic fade. In Olive I'm looking at extra steps selecting the appropriate tool, selecting the type of fade, adding it to the tracks, and then cinching it down. Additionally there seems to be a quantisation I can't turn off and I'm having trouble zooming in and out, placing the cursor could be easier. Right now I can only click on the ruler to move the cursor, perhaps anywhere on the time line would make things easier.

**Comment by DaniSeeh** [comment]
Olive is trying to be its own thing, and this issue is a little to non-specific to ever be able to close. I'm sure Matt will keep these ideas in mind while designing Olive, but right now these sorts of issues are kind of clogging up the issue tracker. Bear in mind Closed issues aren't gone, they can always be reopened and they can still be discussed even while closed.
