### ISSUE TITLE
Ripple delete does not work if invoked with keyboard

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#363]
tested on macOS

**Comment by itsmattkc** [comment]
Could you try this again making sure the timeline is focused? (click on the Timeline first)

**Comment by itsmattkc** [comment]
Just to confirm, this is the Shift+Del shortcut?

**Comment by pgilfernandez** [comment]
Yes, I have tried with shift+del and custom shortcuts and never worked...

**Comment by itsmattkc** [comment]
But it works manually triggering through the menus?

**Comment by pgilfernandez** [comment]
Yes, if triggered with the drop down menu (right mouse button) it works perfectly

**Comment by itsmattkc** [comment]
Oh, are you trying to use Shift+Del on empty space?

**Comment by pgilfernandez** [comment]
Yes, that's it... is it wrong?

**Comment by itsmattkc** [comment]
Ahh yes, the right click "Ripple Delete" function does not have a keyboard shortcut. Its function is to ripple delete empty space in the timeline that the user has right clicked on. The menu bar function (that Shift+Del triggers) is for ripple deleting clips that are currently selected. Shift+Del doesn't respond because you aren't selecting anything. They are two similar but ultimately distinct functions.

Perhaps the right click function should be renamed to avoid confusion.

**Comment by pgilfernandez** [comment]
Yes, that is the problem. I was hovering with the mouse the empty space where I wanted to ripple delete. Is is possible to get the mouse position and locate the empty space the user wants to ripple delete? that way it would work...
If not, I do agree renaming the functions in order to avoid confusion.

Thanks

**Comment by itsmattkc** [comment]
If "Hover Focus" is enabled, this will happen in c6da0b5912f13c92de5299dc966716e543cd20a3
