### ISSUE TITLE
[feature request] (some more) audio effects

### ISSUE THREAD

**Issue by inbguy** [olive-editor/olive#384]
I really need a way to manipulate my audio, and this is pretty much the only editor that meets my standards! (it's really great, you're doing a great job!) 
and by 'the only one that meets my standards' I mean that I've searched for 3 days nonstop and went through ~100 softwares... this is by far the best one I found.

**Comment by itsmattkc** [comment]
Firstly, thank you! I'm glad you like the software and find that it suits your needs. As far as audio effects go, Olive has VST2 support on all platforms (and LV2/LADSPA should be implemented soon), so I encourage you to find VST plugins that suit your needs. While I see merit in more internal effects, it's currently a low priority since Olive users already have more or less the entire library of VST plugins (available for their platform) at their disposal and there are other more pressing issues at the moment. But thank you for taking the time to file an issue and for using Olive!
