### ISSUE TITLE
Modularize blending

### ISSUE THREAD

**Issue by oc1024** [olive-editor/olive#385]
Taking advantage of Olive's new blending infrastructure, I'm implementing 4 new blending modes related to keying (#356 : Difference matte as requested by @goldenbait , Mask Below, Mask Above and Keep Alpha)

In order to implement them, I have to:

* Modify `transformeffect.cpp`
* Modify `effect.h`
* Modify `blending.frag` with new chains of if-else-if.

By comparison, #358 required me to write fairly easy-to-understand XML and C-style files.

If blending modes had the same sort of behavior as effects instead of being a huge monolithic shader, implementing new blending modes, having other users try them out and merging them to mainline Olive would be fairly easy.

**Comment by itsmattkc** [comment]
This can probably be done. The design was somewhat intentionally non-modular because the blending seemed somewhat mission critical, hence it was tied in closer to the C++. However with the addition of a non-shader based blending fallback (#375) it probably wouldn't be difficult or problematic to make them modular.

**Comment by oc1024** [comment]
Seems  64a4c4f addresses this.
