### ISSUE TITLE
[Feature Request] Hide and Unhide Video Layer, Mute/Unmute/Solo Audio Layer

### ISSUE THREAD

**Issue by DaniSeeh** [olive-editor/olive#420]
I hope this isn't already a feature that I stupidly haven't figured out how to use.

Edit: sorry, Track is the more appropriate word. Been using too much GIMP recently. Audio and Video Track hiding / muting

**Comment by itsmattkc** [comment]
There isn't really an equivalent feature for this yet, apart from using Edit > Enable/Disable (Shift+E) on individual clips.

**Comment by alcomposer** [comment]
In other editors, it's super useful to be able to hide a layer with a keyboard shortcut.

**Comment by DaniSeeh** [comment]
A keyboard shortcut would be awesome, but a UI element preferably to the left of the track would also be nice. It might be nice to be able to name tracks too.

**Comment by frink** [comment]
Until layering is fully fleshed out, (there still seems to be some discussion on how layers work) I don't expect that track/layer muting/soloing will exist... Would be helpful and probably not too hard to implement. But we need to know what track/layers mean first...

**Comment by Symbian9** [comment]
FTR, one of solution variants

![pic.1](https://i.imgur.com/G2q8ZiG.png)

**Comment by itsmattkc** [comment]
This has largely been addressed in the upcoming `furtherocio` and `nodes` branches.

**Comment by enzogian** [comment]
Is great to know this has been reported and suggested. I am sure it would represent a huge improvement on speed when working with lots of tracks etc... hope my suggestion on making audio level bars thinner could help to get that extra space in order to insert those controls at the left of the tracks.
Thanks and cheers to all developers for such a great tool (the best open source video editor so far)
