### ISSUE TITLE
Vector Olive Icon Redesign

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#429]
I'm sorry, but in my opinion the current Olive icon looks really dated.
And it does not help that it is still png.
That's why I tried to create a modern icon with Inkscape, because I've seen that you were recently porting the icons into vector graphics.
I hope you like it:
https://workupload.com/file/DrBXsCZc
symbolic:
https://workupload.com/file/GFEwaLGj

It would be so nice if this one or another one would be merged into the master branch.
Thank you in advance and keep up the great work!

**Comment by naj59** [comment]
@libalis 
Why not add a macOS-like circle to it. In my opinion it fits to all platforms.

![thumb](https://pre00.deviantart.net/8270/th/pre/f/2018/169/e/5/spark_for_macos_by_octaviotti-daq7sau.png)

**Comment by oc1024** [comment]
It already has an outline, it just needs drop shadow to make it apparent.

And I think a gradient would make it look nicer.

**Comment by libalis** [comment]
Yes, it would really look better with that shadow.
But I am total beginner in that space.
Therefore feel free to modify my icon until it fits your needs.
And don't forget to reply with the new link for the developers!

**Comment by oc1024** [comment]
Added a drop shadow to icon, added gradient, made reference image invisible and extra outlines.

https://workupload.com/file/8ZrZVst5

![olive](https://user-images.githubusercontent.com/7990860/52183535-6bbd2f80-27e7-11e9-9ccd-e2601b391806.png)

**Comment by naj59** [comment]
I like the outline but the outter green line should be removed. The gradient is ok but the path should be from top right to bottom left (in my opinion).

**Comment by itsmattkc** [comment]
Hi, thanks for putting the effort in to make a new logo, but I actually don't really like the modern flat UI trend and have been fairly intentionally avoiding it. The source is vector-based too (the source vector doesn't package with Olive because most icon systems utilize raster images).

**Comment by alcomposer** [comment]
This is an idea for a complete re-design:
![olive_logo](https://user-images.githubusercontent.com/12004932/52192015-7afbb600-2897-11e9-87b9-d10781169b43.png)

* Design clearly shows an Olive in center, and a spiral that creates a lower case 'e'
* Leaves at bottom of 'e' indicate the olive branch (in original logo)
* Clearly visible at small resolutions

I understand that this icon could be interpreted as being 'flat', however my main concern is visibility at low resolutions, (in Docks, start menu etc) and also to clearly communicate **Olive** **e**ditor

**Comment by alcomposer** [comment]
Thinner design, with mesh gradient.
![olive_gnome_colors](https://user-images.githubusercontent.com/12004932/52196193-cc617080-28aa-11e9-9db2-b832cfef13b3.png)

**Comment by naj59** [comment]
@alcomposer The one with mesh gradient is awesome!

**Comment by Gustavekkj** [comment]
I think simplicity is better for icons. The others are to elaborate (my personal opinion). just a five minute creation. 

![olive test](https://user-images.githubusercontent.com/31554493/52209150-4aaa1c80-2883-11e9-8c65-ef52355e26c1.png)

**Comment by Gustavekkj** [comment]
I couldn't get the idea out of my mind. Here is my 2nd attempt  :)

![olivelens](https://user-images.githubusercontent.com/31554493/52247277-91326200-28e9-11e9-813a-66281a4f4132.png)

**Comment by oc1024** [comment]
~~Big Matt is Watching~~

While I do think associating an olive with a camera was clever, I'm put off the this eye looking me sideways.

**Comment by Gustavekkj** [comment]
![olivelensnoside](https://user-images.githubusercontent.com/31554493/52247769-7fea5500-28eb-11e9-99f7-b028260d4287.png)

**Comment by alcomposer** [comment]
Here is the App Icon guidelines for Gnome (updated Jan):
http://jimmac.musichall.cz/blog/2019-01-23-the-big-app-icon-redesign/

It's a very good read, and coming from one of the oldest FOSS projects, I think the historic context is there.

**Comment by Gustavekkj** [comment]
![olivegn](https://user-images.githubusercontent.com/31554493/52275489-fcaf1a80-294f-11e9-8079-0fe03f4c7c80.png)

**Comment by naj59** [comment]
@alcomposer [off-topic] Is there an possibility to get the SVG of your concepts? Want to base my app icon on that and I am an absolute loser in graphics design. Would be nice 😄

**Comment by naj59** [comment]
Here is a slightly different version based on @oc1024 idea. In my opinion it fits more into that macOS world although it would look nice on Windows and Linux too.

![imgur](https://i.imgur.com/FJs2Xn4.png)
[Uppy svg link](https://master.tus.io/files/17298f579d9eed7eb8df2e8b906afca7+WFMpwcKB4Pfc.MCo9v62Klrmkher6U_.PQCA8R01_WPxG_PdmcAIMWx4b8kYsppVA0MC1kGgjSUPWXY1eQ.zJpajgdbvrXz7JXEKj0vJR56H4KfOZHYNmLqlJ7UydGf3)

**Comment by elsandosgrande** [comment]
@alcomposer I know this is not strictly regarding the Olive program, but could you maybe make a version of that alternative rainbow Olive icon with an expanded background? It would be nice as the Discord server's icon (the icon of an open Discord server expands from a circle to a rounded square, so having a square picture with the same dimensions would be lovely).

**Comment by alcomposer** [comment]
Hey @elsandosgrande,

Here is the logo as PNG & SVG:
![olive_discord](https://user-images.githubusercontent.com/12004932/53386389-f7367480-39d1-11e9-80fa-e8c88710cb69.png)
[olive_discord.zip](https://github.com/olive-editor/olive/files/2903678/olive_discord.zip)

I used Inkscape, and its a standard SVG file.

**Comment by brotenet** [comment]
used inkscape 
![Selection_146](https://user-images.githubusercontent.com/4510965/55395531-60b61f80-554a-11e9-99dd-ead8418d21e0.png)
![Selection_147](https://user-images.githubusercontent.com/4510965/55395538-6449a680-554a-11e9-98e0-3db5b8713668.png)
[olive-editor.svg.zip](https://github.com/olive-editor/olive/files/3033455/olive-editor.svg.zip)

**Comment by Symbian9** [comment]
> ![pic.1](https://user-images.githubusercontent.com/4510965/55395531-60b61f80-554a-11e9-99dd-ead8418d21e0.png)

AWESOME! Really like this variant!

**Comment by qubodup** [comment]
brotenet's is the only one that doesn't look busy

Too much detail and busyness are the main problem of the current official logo and many of the submissions here. I'm stating this as a user and somebody who has experience with using logos of applications to draw attention in video thumbnails, not as somebody who could even dream to create a better design on his own.

naj59 - yours is gorgeous but as an icon it has empty space and the detail is a problem. Maybe it would be possible to crop a section of the branch but I doubt it would be still recognizable.

brotenet - the film clip is too cartoony and generic. In general any design suffers from people not being familiar with the look of an olive on a branch, so without the dark olive/green branch/white bg colors it's hard to identify (looks like a weirdly lonesome grape to me when it's white on dark grey). Still my favorite though. Here's the ones from the svg that i like:
![image](https://user-images.githubusercontent.com/18312/55642010-96b80580-57cf-11e9-8d32-06b92c7789af.png)

Since Sony Vegas also uses the "adobe style" I would figure that its concept is free for grabs

![olivelogo](https://user-images.githubusercontent.com/18312/55642246-43928280-57d0-11e9-8a25-87850e5b671e.png) ![olivelogo2](https://user-images.githubusercontent.com/18312/55642247-43928280-57d0-11e9-9530-d95661b85835.png)

If the project owner wants to actually consider these, somebody please improve them. Neither is 100% square: [olivelogos.zip](https://github.com/olive-editor/olive/files/3048817/olivelogos.zip)

**Comment by Simran-B** [comment]
I agree with @qubodup and want to add, that the logo should be recognizable at small sizes because it will be used in several places where it matters:

- **favicon of website**:
  - 32x32 pixels appears to be common, although tab icons are displayed in Chrome on Windows at a scale of 16x16
- **application icon on Windows** ([info](https://stackoverflow.com/questions/3236115/which-icon-sizes-should-my-windows-applications-icon-include)):
  - 16x16 in Window title bar and in Explorer in list view mode
  - 24x24 on taskbar, but typically generated by the OS from the 32x32 icon it seems
  - 32x32 in Explorer's properties dialog
  - 48x48 by default on the desktop?
  - larger sizes on desktop and in explorer possible, computed from a 256x256 image
- **on macOS** ([info](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/)):
  - 16x16
  - 32x32
  - 128x128
  - 256x256
  - 512x512
  - all of the above at 2x, so twice the size as well (32..1024)
- **on Linux** ([info](https://icons8.com/articles/choosing-the-right-size-and-format-for-icons/)):
  - 16x16 GNOME menu icon size
  - 24x24 primary size for GNOME toolbar icons
  - 48x48 primary size for GNOME application icons
  - various sizes with KDE (16, 22, 32, 48, 64, 128, 256)

Anything larger than 256x256 pixels doesn't seem very useful to me. The olive branch in the startup message box is around 170 pixels, the red outline is 256:

![image](https://user-images.githubusercontent.com/7819991/56603474-18959480-6600-11e9-9b28-ca610ea53f96.png)

The logo should be created as SVG regardless, so that it can be scaled to whatever size. The grid alignment is important however, to get good results for the tiny icon sizes. For the 16x16 version it might be better to create a raster graphics variant by hand for optimal quality, but that highly depends on the icon itself.

I tweaked one of @brotenet's designs and it renders pretty well for 16, 32 and 256 pixel sizes:

![olive_16](https://user-images.githubusercontent.com/7819991/56606207-01f23c00-6606-11e9-8474-0ee02a22be85.png)
![olive_32](https://user-images.githubusercontent.com/7819991/56606208-028ad280-6606-11e9-83db-9e398e762502.png)
![olive_256](https://user-images.githubusercontent.com/7819991/56606209-028ad280-6606-11e9-9226-92bd26bef179.png)

A few remarks:
- 32x32 canvas as base
- increased the margins between elements (2-3px)
- increased the size of the light streak (otherwise it gets a bit lost at 16x16)
- 1px border margin
- made the green color a bit less vibrant
- branch terminal at the top is no longer rounded
- main elements are grid-aligned, although this isn't all that important for this icon because there are very few vertical or horizontal shapes which should be pixel-perfect

This was just an initial experiment. It's a great starting point, but it needs more tweaking in my opinion. 

- The leaves look a bit too disconnected and out of place with the increased margins, but it is somewhat necessary have such a gap between the elements so that they their pixels don't touch at 16x16.
- could be even more "reclined", for a more pronounced **J** shape to fill the space better. Might also help to solve above problem.
- at large scale, it looks rather boring and @itsmattkc doesn't like flat design. Might be worth to explore something more skeuomorphic, but I my suggestion is rather to go for a flat 2.0 style by adding some shadows and details similar as seen in many material design illustrations for instance. Subtle details shouldn't affect the recognizability at small sizes but make it more interesting at large sizes.
- not sure about adding a background or outline. I don't like the monochrome variants and a white outline is too much in your face if it's on a dark background like the black Windows 10 taskbar. Would it make sense to create different versions for macOS and other OSes to better fit the typical app icon style of the platform?

**Comment by maxxxlarsson** [comment]
I think one can go even further in simplifying the logo and overall UI of Olive. Here's one quick proposal using a more simple approach to the Olive:

![Olive icon redesign](https://user-images.githubusercontent.com/7046942/62355857-26688900-b510-11e9-97df-ed3d06a469e8.png)

I understand that it may be to simple for some, but I'd at least recommend moving away from the current screaming green colour, embossing and way to detailed logo. I think Gustavekkj and brotenet are on to something, but they could be simplified even further, in my opinion. And the colour scheme can be adjusted further as well.

Just my opinion.

**Comment by Simran-B** [comment]
Personally I really like your direction. Not sure if I see an olive in that logo, but it's a nice design. The green color is great, but not sure if it works on black in terms of contrast (we should check WCAG 2.0 accessibility) - in a logo it's not much of a concern, but to use the same color on a website might not work.

An idea I had the other day was to perhaps make the logo look a bit like a node graph to emphasize that future core aspect of Olive. Not sure if this is a possible in a minimalst design however.

**Comment by rubenwardy** [comment]
@brotent's variation is my favourite. Logos and icons should be recognisable and distincitve at a small size. Most of the other logos fail this.

I didn't even realise that the logo in the April 2019 release is an olive branch, I through that it was some strange character!

**Comment by Simran-B** [comment]
Some toying around with shapes and colors:

![image](https://user-images.githubusercontent.com/7819991/63931902-7591d300-ca56-11e9-8aad-6dd7cfe82667.png)

**Comment by rubenwardy** [comment]
I really like the second one on the second line. It's probably my favourite so far

**Comment by Symbian9** [comment]
FTR, Once when I tryed to search `Olive` on Twitter i discovered that there are few users (that also has "Olive" word in their names) with nice icons & colors

- «Olive Garden» ([@olivegarden on Twitter](https://twitter.com/olivegarden))
  ![Olive Garden icon](https://pbs.twimg.com/profile_images/788366775314423808/8P5Pxd6k_normal.jpg)
- «OliveTreeBible»([@OliveTreeBible on Twitter](https://mobile.twitter.com/OliveTreeBible?p=s))
  ![OliveTreeBible icon](https://pbs.twimg.com/profile_images/928318344461041664/FyGMqQmq.jpg)

**Comment by Simran-B** [comment]
What we need is a logo which is recognizable at small scales, so that it can be used as app icon, favicon, server icon on discord etc. Making an extended version with text is easy, and thus secondary. Your images have a way too high visual complexity and too thin elements. One olive and a leaf might work though.

**Comment by Symbian9** [comment]
> Making an extended version with text is easy

Fully agree! Sorry me, I was unclear - icons above I referenced only for colors example; Olive icon of course should not include text objects.

**Comment by timkrief** [comment]
Hi everyone, I made an icon using inkscape. It's a standard svg. 
Here's the result:
![OliveEditorLogoAlt](https://user-images.githubusercontent.com/14089949/65767849-65d9dd00-e12f-11e9-99ee-df95fcf721dd.png)
There's also an alternate colored version, but I prefer the monochrome one:
![OliveEditorLogo](https://user-images.githubusercontent.com/14089949/65767841-5eb2cf00-e12f-11e9-82a0-7fe4dc207870.png)

**Comment by timkrief** [comment]
OK I'm back with new proposals:

![image](https://user-images.githubusercontent.com/14089949/65789681-2bd3ff80-e15e-11e9-85d1-65b5fcb6b182.png)

**Comment by sobotka** [comment]
These are hideous. Please no. Stop.

Open source and design is truly an oxymoron, with emphasis on the moron.

**Comment by timkrief** [comment]
Icon concept felt right, it gets the message across (Olive Video Editor), recognizable as a tiny icon, unique. So I spent a day on this concept and I tried my best. I actually used a day in my life to make that without asking anything in return, so please be respectful.

@sobotka I'm not sure we'll go far with that kind of comments. However, if you have actual constructive comments to improve or try new concepts, please share them.

**Comment by sobotka** [comment]
Constructive comment: Don’t assume time spent is valuable.

**Comment by qubodup** [comment]
It doesn't look like any of these are liked by contributors enough to create a pull request, so it still will be useful as reference of what is not good enough.

Anybody annoyed by this ticket, can simply unsubscribe:
![image](https://user-images.githubusercontent.com/18312/65813507-9a54a400-e1d6-11e9-957c-9fe48c687cc8.png)

About using film rolls in icons: as opposed to floppy disk's meaning "save", film roll's meaning "video" seems to be dying out in modern video editors' logos.

**Comment by rubenwardy** [comment]
@timkrief's design is my new favourite, it combines both context (this is a video editor) and the name (olive) better than any other design so far, whilst being modern and minimalistic
