### ISSUE TITLE
Arch Linux - VST Segfault

### ISSUE THREAD

**Issue by oc1024** [olive-editor/olive#432]
I don't know if this is related to Arch Linux's extremely recent library versions, but any time I load a VST one of two things happen.

* Olive crashes as soon as I load the file. Case with DragonFly Reverb and ZynAddSubFX.
* Olive will load the plugin correctly and apply its effect, but as soon as I call its GUI it crashes. Case with Protoverb. Strangely enough, loading saved projects with a plugin affected by this variant of the issue work if save is performed manually, but segfaults if loaded from an autosaved file.

**Comment by itsmattkc** [comment]
Is there any debug output when you run from terminal?

**Comment by itsmattkc** [comment]
I see output mentioning MIDI, Olive doesn't implement any of VST's MIDI opcodes since there (presumably) isn't much point of utilizing MIDI in an NLE, but perhaps a few of the opcodes need to be implemented for some effects to work. I'll have to test these specific VST plugins myself and see if that's the answer.

**Comment by itsmattkc** [comment]
DragonFly Reverb (and presumably ZynAddSubFX) work as of 57e038afc4af4f6b8573cc0ada26a1ef7e75ee7b. They used a `main()` function for their entry point rather than the documented `VSTPluginMain()` - not uncommon it seems, but something I hadn't accounted for (Olive is also now crash-resistant if it can't find either). For some reason I can't set any parameters in DragonFly Reverb, but I'm not able to in other hosts either so I assume this isn't specific to Olive.

Let me know if this fixes the VST issues for you.

**Comment by oc1024** [comment]
DragonFly Reverb now loads, but its UI is irresponsive, as you noted.

However, ZynAddSubFX and its subsets still crash with no log but `Segmentation fault (core dumped)`

I tried an alternative to ZynAddSub's family of VSTs, the [ZAM](https://www.archlinux.org/packages/community/x86_64/zam-plugins/). While they load and you can hear their effect, their UI is completely black and I can't seem to edit anything.

**Comment by itsmattkc** [comment]
I'd consider filing a bug report with the developers of DragonFly Reverb, the UI is similarly unresponsive in OBS and even Audacity.

I'm guessing ZynAddSubFX is a completely separate crash because Olive _should_ protect against having no entry point. I guess I'll have to take a look

**Comment by oc1024** [comment]
I think I found the reason why ZynAddSub won't work: when loading a ZynAddSubFX into Audacity, it won't draw its own UI, but request the program to draw its controls, including sliders. Olive doesn't implement that and crashes.

![image](https://user-images.githubusercontent.com/7990860/52542301-059f5200-2d7d-11e9-86cd-06fbb2a86aaa.png)

ZAM also loads its UI properly, and DragonFly Reverb actually responds (bug fixed in a later release than Ubuntu's)?

**Comment by DaniSeeh** [comment]
I'm closing all pre-nodes merge Bugs. If Matt thinks they still apply, we should reopen. The entire infrastructure is changing so these bug reports likely aren't relevant anymore.
