### ISSUE TITLE
[Issue] Olive crashes if you try to revert a video clip

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#446]
Sorry, but I don't know what causses it, but everytime I try to revert a video clip, Olive crashes!
I'm using Ubuntu 18.10 with the newest AppImage!
Thank you in advance and keep up the great work!

**Comment by alcomposer** [comment]
@libalis are you talking about reverse? (That crashes on mine as well)

**Comment by oc1024** [comment]
In my case, Olive won't crash, but for a few moments it will display a garbled image and any form of playback will drop a lot of frames even when seeking at 2 seconds per pressing of the right key.

In order to get acceptable seeking speed, every once in a while I have to seek backwards (i.e. play video forwards) but if I do it too fast, then Olive will crash.

**Comment by itsmattkc** [comment]
This seems like a similar issue to #357. In the same vain (for testing purposes) if you press J on a non-reversed clip (so that the clip plays backwards), does this crash too?

**Comment by alcomposer** [comment]
Sorry @libalis, were you referring to **replace / re-link** by any chance? I just noticed that if I try to **replace / re-link** any footage Olive hangs.
![replace_relink_crashing_olive](https://user-images.githubusercontent.com/12004932/52420668-70b11480-2b42-11e9-868c-04fa5806786a.png)

**Comment by libalis** [comment]
Oh, Sorry, I missed this issue!
And, @alcomposer under properties there is reverse!
That's the function I meant!

**Comment by itsmattkc** [comment]
Assuming this is the same as #357, I'll fold this issue into that one for now.
