### ISSUE TITLE
[Bug] Video exporting turns out really weird.

### ISSUE THREAD

**Issue by deilias** [olive-editor/olive#447]
Here is the problem:
Basically after I finished my video, I tried exporting it (took more than 1 hour and I'm frustrated) and the result comes with the heavily distorted video (700 x 700).

Currently using the newest version of Olive (Jan 2019 Alpha). Also I tried exporting using other formats but it gives me the same distorted result.

**Comment by naj59** [comment]
Export settings + any type of screenshot what this video looks like?

**Comment by itsmattkc** [comment]
Sorry about the frustration, this was a recent regression from a rewrite of the rendering backend. It's fixed in 04084c36d25b4758e3b28db85024d83610dfe9b8, if you're on Linux (or compiling from source) most packagers will update automatically. If you're on Windows, you may have to wait momentarily for the website build to get updated.
