### ISSUE TITLE
[Issue] Languages don't work at all

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#454]
You can select them, but, even after a restart, Olive will default back to english and ignore the chosen language!
Would be nice if you could fix that!
Thank you in advance and keep up the great work!

**Comment by itsmattkc** [comment]
Which package are you using? Also not all the languages are complete, i.e. French, Spanish, and Italian are still completely untranslated unfortunately.

**Comment by Symbian9** [comment]
@itsmattkc , could you setup additional task to Travis CI for generate translation template (`olive-template.ts`) and deploy it as AppImages deployed under tag `continuos`?

**Comment by itsmattkc** [comment]
@Symbian9 I could just add a default English ts file to the Git repo?

**Comment by naj59** [comment]
@Symbian9 why? The projects file has them integrated. 

@itsmattkc it probably relies on where you call ``QApplication::installTranslator``, it should be done during startup otherwise the application does not register that a different language has been choosen.

**Comment by itsmattkc** [comment]
@naj59 I'm fairly certain we're allowed to install translators at any time - technically we don't even have to restart Olive to change the language, but that would require a function to update all user-visible strings after installing a new translator which I haven't written yet. As long as they're placed before the (re)creation of user-visible strings I believe that's compliant, and it would be tough to test other placements since the translations have worked so far on setups I've tried.

@libalis Assuming you're using a language that has been translated, do the Preferences literally set back to English, or is the config on another language with the strings still in English? This may be more of an issue of config saving/loading.

**Comment by libalis** [comment]
I never see the German translation, because I have to impatiently restart Olive and than nothing happens.
It literally sets the language back to English in the preferences.

I'm using Ubuntu 18.10 with the newest continuous build AppImage.

**Comment by itsmattkc** [comment]
It does sound like a config issue to me. I wonder if it's related to #448 where Olive's AppImage appears to fail getting correct paths/filenames.

**Comment by itsmattkc** [comment]
Issue should be fixed in 35db995c607196c3fa4195b85e4d0aef456cf4a3. Indeed a config issue, paths didn't work quite how I expected in AppImages.
