### ISSUE TITLE
[Feature Request] SmartEncode output functionality

### ISSUE THREAD

**Issue by FSharpCSharp** [olive-editor/olive#455]
It would be desirable if there were some kind of "SmartEncode" feature that only re-encodes the overlapping areas during output, not the entire video. This could speed up the encoding process enormously, and even shorten videos. The same should be possible for both video and audio data. There is already a proprietary product on the market that makes this possible (TMpegEnc SmartEncoder). It would be great if such a functionality would finally be available in an OpenSource product.

**Comment by BrimsonBhin** [comment]
That would be a nice feature, but I think that would require **a lot** of work from the developers. From the site, TMpegEnc was developed by a sizable Japanese company. Meanwhile, Olive only has a few developers and contributors.

I believe hardware encoding should be done first before something that sophisticated can be done. There is an audience of editors (like I) who do not mind using GPU encoders at the cost of video quality.

**Comment by FSharpCSharp** [comment]
@BrimsonBhin 
I realize this can't be done overnight. But now in the early phase it may be possible to set the course accordingly. Perhaps it is possible that certain preparations can already be made so that the actual development will not take so long. I just think that you can catch and convince people with such features.

**Comment by frink** [comment]
By the time this could be developed it's value would be minimal. The leaps and bounds made in computational power and IO speed make this sort of effort moot when you consider all of the other colossal mountains that ust be climbed to create a truly professional editor.

**Comment by FSharpCSharp** [comment]
It's a real shame that the topic is played down here as if it doesn't make any difference at all. Unfortunately, I have already experienced that such functionality is essential for 4K content, because re-encoding sometimes takes ages. But apparently I'm the only one who does and faces these problems. But even with Full-HD content it makes no difference whether I wait half a day for the result or maybe 10 - 15 minutes. Unfortunately, not everyone has a render farm in the garden where they can process such content. I'm sorry that I can't afford it like everybody else.

**Comment by frink** [comment]
I don't think we are saying your problem is invalid or of no importance. Simply that there are mountains to climb in building software and this is not something that has the prerequisites built. As I stated earlier, by the time this is likely tacked in Olive (and I believe Olive may try to tackle this at some point) the return on coding time will be of less value since computing and integration of GPUs will be greater than today - making this problem less pronounced...

Several old audio editors used to do renders in the background. It works but sometimes produces wonky results before the render is complete or when it aborts prematurely...

I think there is a place for such background rendering. But it probably belongs in distributing the load to a render farm in the cloud rather than trying to conserve the computation energy of a single machine. If Eevee in Blender is able to renderX high quality scenes in real time, then then we can't be far behind in rendering composite video edits in real time...

**Comment by oc1024** [comment]
> As I stated earlier, by the time this is likely tacked in Olive (and I believe Olive may try to tackle this at some point) the return on coding time will be of less value since computing and integration of GPUs will be greater than today - making this problem less pronounced...

If by that point 8/16K becomes prevalent, any advance in performance - and squeezing more of it from current technology is getting harder and harder - will be completely irrelevant. As the issue opene said, this is a lifesaver for high-resolution editing.

**Comment by frink** [comment]
Absolutely understand. However, by the point we have GFX cards that can handle 16K/120fps images the computation of blending pixels will no longer be the bottleneck. the FLOPS required for such an operation isn't that difficult compared to IO considerations. The proxy solution fixes both constraints quite easily for editors and render farms solve the problems associated with large format sizes.

From this I concluded that selective rendering is more in the realm of render farms than that of the editor for true professional grade productions. If anything, what we should be looking to is render farm management connectivity. Seems lie that is the real pro-grade solution. Especially with more render farm cloud solutions popping up daily...
