### ISSUE TITLE
Units used for "Shake > Rotation" effect

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#457]
What units used for "Shake > Rotation" effect?

Think, it should be `°` ("degrees"), and value should be `-∞..+∞`.

**Comment by itsmattkc** [comment]
I'm pretty sure it is in degrees yes. A negative value doesn't really make sense since it'll rotate both left and right regardless.

**Comment by Symbian9** [comment]
> I'm pretty sure it is in degrees yes.


Please, check! Because I found issue with it (will add screenshot later)

> A negative value doesn't really make sense since it'll rotate both left and right regardless.

Regardless to what?

Normally, `90` should rotate to 90deg clockwise; `-90` should rotate 90deg counterclockwise.

**Comment by itsmattkc** [comment]
In all honesty, you're not really supposed to think of it as an absolute value like that. The shake effect is supposed to produce a smooth "natural" looking movement using randomly generated mathematical algorithms. It doesn't simply rotate in one direction or oscillate between two values, the rotation field just specifies a maximum/multiplier for how much rotation will be implemented into the shake. A rotation value of "90" doesn't guarantee that it will rotate 90deg because oscillating between, say, 0deg and 90deg wouldn't produce a smooth looking shake, it's more of a "feel" based value.

If you must know, the specific formula is that the actual rotation in degrees will be smoothly interpolated random values anywhere between -VALUE/10 and +VALUE/10 (e.g. a value of 900 will oscillate anywhere between -90deg and +90deg). But as I said, I don't think it's productive to consider it an absolute value since it's all randomly generated.
