### ISSUE TITLE
olive version on top bar 

### ISSUE THREAD

**Issue by welon68** [olive-editor/olive#460]
Is it possible to display the correct version?
![image](https://user-images.githubusercontent.com/32037656/52509372-28ecc480-2bf8-11e9-9a77-f20670319f00.png)

**Comment by naj59** [comment]
Actually the current version should be the last git hash. From which source do you got Olive?

**Comment by itsmattkc** [comment]
I assume you're on the apt version? I ran into a strange problem there with the version marking. Because Launchpad repos are all Bazaar based and the Git repo is just routinely "imported" into it, by the time Launchpad compiles it, there's no trace of the Git hash anymore so it doesn't show up. I haven't found a decent solution to this yet.

**Comment by welon68** [comment]
yes I have version from apt

**Comment by itsmattkc** [comment]
Fixed in eb792d8cd6825afea3c385b3e857f9f6141454d6
