### ISSUE TITLE
[Feature Request] Add Windows builds (to Continuous build)

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#482]
Please add Windows compiler to Travis CI!
Another Question: What are the AppImage.zsync files?
Thank you in advance and keep up the great work!

**Comment by elsandosgrande** [comment]
It was removed by a contributor with this commit comment: `Can't build on Windows - affected by https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/10`.

I would say that that should answer your question quite adequately. Have a nice day!

**Comment by itsmattkc** [comment]
Believe me, I really want to add Windows to the CI, but the Travis Windows support is still in "early stages" and having a secure variable (e.g. the one used to authenticate uploads to GitHub) currently causes builds to hang indefinitely on Windows. It's a known issue (see https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/10) that people have been reporting since October (see https://travis-ci.community/t/choco-install-hangs-forever/307) but no fix has been announced.

There's a workaround by revealing the secure variable in the build log, but that would theoretically give anyone the password to upload whatever they wanted to the Olive releases page.

The only real solutions are using some other kind of buildbot or just waiting until this issue is fixed.

**Comment by itsmattkc** [comment]
I've seen a project using Travis CI for Mac and Linux and AppVeyor for Windows, maybe that's the solution to having a continuous Windows build.

**Comment by itsmattkc** [comment]
Windows builds are now part of the CI utilizing AppVeyor instead of Travis.
