### ISSUE TITLE
[Feature Request] Redesigning A/V timeline slots 

### ISSUE THREAD

**Issue by malnaanah** [olive-editor/olive#510]
I think the current design of A/V timeline slots is a little bit confusing. It would be great if it is redesigned to be more like Kdenlive  (versions prior to the refactoring branch) with the following notes.

1- Not splitting audio/video tracks automatically and leave it for the user to do it manually, this makes editing easier and more logical.
2- The A/V slots should be visible before adding any A/V clip. The current design is confusing.
3- The color for active and inactive clip should be made clearer, like making the active clip having red color. The current color of active clips is confusing.

**Comment by oc1024** [comment]
While I don't agree with the "easier and more logical" part in 1, this would make Olive more versatile and able to accomodate more workflows (such as yours), so yes, this would be a nice addition.

2 and 3 I've experienced myself, to the point where I often ask "why can't this video clip go here?" and it's a either another video clip ahead on it's an audio track (that looks identical to the video track).

**Comment by manokara** [comment]
Yeah I've been thinking about this recently, there's a splitter in the middle of the timeline which is how you can tell the video and audio tracks apart. Video tracks are above the splitter, audio below. 

The approach used by Premiere (which is where Olive draws some inspiration from) of having A1, A2, V1 and V2 track columns for audio and video respectively, with buttons to control visibility, effects and such would be more intuitive, and honestly I think that's what Matt was going for but prioritized other things. Maybe I can give a shot at that... Hmm.

**Comment by elsandosgrande** [comment]
@manokara Please get those buttons integrated! While it's not a deal-breaker, it is quite annoying to not see the borders.

**Comment by oc1024** [comment]
Aren't `epoch=`, `pkgrel=` and `function pkgver` better options? They'd even allow an `olive-git` package.

**Comment by itsmattkc** [comment]
(1) is a maybe, I don't necessarily think not splitting them is more logical, though I can see a preference for it.

It's true that the design was influenced by Premiere, which has track labels to the left which would make (2) clearer as the video/audio areas would be labelled. Technically, that issue is the same as #420 and will likely be implemented at some point.

As for (3), I'm really not sure what you mean by "active".

**Comment by malnaanah** [comment]
It will be great if an option is added to not splitting A/V tracks by default.

Regarding 3, the color of selected, i.e. Active, clip is not differentiated enough, may be if the color changed to red or

**Comment by elsandosgrande** [comment]
I think it's best to leave the highlight color up to preference with the default unchanged, since most people would most likely be used to the lighter differences in color (honestly, I first thought that the color came straight from KDEnlive, so that's a plus in my book).

**Comment by malnaanah** [comment]
I totally agree with that, it is good to implement preferences for different users tastes.

**Comment by frink** [comment]
This also need to be discussed in light of more complex layed compositing. Two layers will not be enough for many scenarios. We need to understand what extreme layering looks like. At some point we need to push things to a dedicated compositor like Natron or something. But at the same time, layers are a common part of the workflow in some cases and a single timeline with cuts makes more since in others. So the concept of layers really needs to be fleshed out before we can dig deeper...

As to the separation of audio and video. It's common that we cut audio and video at different points. The source of audio and video in a dialogue scene is many times separate and even when it is the same some camera's audio will be discarded while other camera audio is used. It is very common to cut audio before we cut to the new video in a scene necessitating the separation of the two sources. This is why Premiere and most pro editors separate the sources...

**Comment by itsmattkc** [comment]
The `furtherocio` branch has about as much as I wish to "redesign" the timeline.
