### ISSUE TITLE
[Discussion] Development process

### ISSUE THREAD

**Issue by jonno85uk** [olive-editor/olive#518]
Rather than a stable fork as mentioned in #504 what I do see as better is a versioned "stable" branch just for bugfixes, whilst the main branch continues on, pulling in the bugfixes from "stable" and at a later date branch from the main to a differing version "stable".

From how i'm reading it, [this is how the linux development process loosely works](https://www.kernel.org/doc/html/v4.14/process/2.Process.html).

This could allow people with differing goals potentially work (i.e. stability vs features) and provide distro-maintainers have a better understanding of what state the project is in.

**Comment by elsandosgrande** [comment]
Well, that's for when Olive enters beta in my opinion. Either way, it's @itsmattkc 's decision, so I guess we'll just wait for what he has to say.

**Comment by jonno85uk** [comment]
True, but rather than assuming that's what'll happen it's better to get the idea out there.

**Comment by elsandosgrande** [comment]
All right.

**Comment by itsmattkc** [comment]
This may indeed be something for further down the line. A while back the master branch was more or less "stable" and there was an "alpha" branch which all development went towards. People seemed to find that confusing though as far as where the latest builds were/what to PR to.

The approach you mention would probably be less confusing though since the main branch would be development and people would instead opt for working on/using the stable branch. I think for the moment Olive development is small enough to stay with one branch, but can see this becoming useful as development becomes more structured and more people start contributing.
