### ISSUE TITLE
Olive no render, no export 

### ISSUE THREAD

**Issue by gebaldi** [olive-editor/olive#537]
Unfortunately the Olive editor is not exporting videos from the timeline, on windows it stays at 0%, and on mac it comes out when we try to export. Grateful for the attention
```

**Comment by mdmayfield** [comment]
@gebaldi In order to help, the developers will need more details. When you opened the issue, you probably saw a template - the information requested there will help. (Olive version, source, OS, CPU, GPU)

Can you please clarify - what do you mean by "it comes out when we try to export"? 

Also, what output does the terminal window show over the course of running Olive?

**Comment by gebaldi** [comment]
The attempt to export, on an older Mac, and on a Dell i5, with 8 GB ram, Radeon video card, was not possible, on the Mac it closes the program as soon as I click on export, and on Dell i5 it is stopped in 0%. Meanwhile on my personal computer, an AMD octacore with video card media FX 1050 Ti, everything went well, rendered and exported quickly.

**Comment by itsmattkc** [comment]
@gebaldi When it closes on Mac, does it come up with a "closed unexpectedly" message that lets you show details and see a debug log?

As for the one that stops at 0%, what happens when you then cancel it and check Help > Debug Log?

**Comment by itsmattkc** [comment]
If you can, try the latest build. The playback engine has been revised and may have addressed this in the process.

**Comment by itsmattkc** [comment]
I'll assume the new rendering backend has fixed this. You can reply back if you have further issues.
