### ISSUE TITLE
French and Russian translations causing conflicts

### ISSUE THREAD

**Issue by elsandosgrande** [olive-editor/olive#538]
So, I pulled from upstream to local just a few minutes ago. In the pull, git said that there were conflicts between old and new French and Russian translation files respectively that could not be resolved and the mergers were failures. So, after running ˙lupdate olive.pro˙, I thought that the conflicts would be resolved, but instead I got this error: `Parse error at /opt/Olive-translating/olive/ts/olive_fr.ts:41:2: Unexpected '<'.`
It's the same error for Russian as well.

Soooo, is this a local issue or one from upstream?

**Comment by naj59** [comment]
The ts-file is based on the XML format and there is an unexpected ``<`` found. Probably this is a manual editing problem.

**Comment by elsandosgrande** [comment]
In that case, what are `41:2` (possibly line 41, second character)?

**Comment by naj59** [comment]
I am on mobile, cannot look up that. But 41 is definitely the line number.

**Comment by elsandosgrande** [comment]
So, ![olive ts file screenshot](https://user-images.githubusercontent.com/40576902/53115094-9a583b80-3545-11e9-819e-e051b5ff4a6f.png)

I think that's a commit note (the bit after a lot of > looks like a git hash). Well, time to manually remove a bunch of these.

**Comment by itsmattkc** [comment]
This is part of Git's "merging" process when it detects that files have changed locally and remotely and can't automatically determine which changes to prioritize (you're supposed to manually choose between HEAD and the commit you're trying to merge which is what those `<<<<<<<` are trying to symbolize. This is another reason to avoid commit language files that you didn't change as Git will get confused like this thinking you made changes yourself to French/Russian. Since you haven't and the local versions are just older versions of the translations, just use Git to prioritize the other branch (I think `git checkout --theirs path/to/file` does it).

**Comment by elsandosgrande** [comment]
That did it. Thank you!

**Comment by elsandosgrande** [comment]
Ummm, considering the only way to get the conflict resolved was to add the `git add` the Russian and French files alongside my own, how to I get a pull request to pull only my files?

**Comment by naj59** [comment]
Push the french and russian one [except yours](https://stackoverflow.com/a/4475506), then just push yours to your repo and create a pull request (hope I did not misunderstood).

**Comment by elsandosgrande** [comment]
@naj59 Thank you! I will see which works best when I get home (it's lunch break, again).

**Comment by elsandosgrande** [comment]
OK, it's still giving me every single language file when I click "Compare", so I've got no clue where to go from here.
