### ISSUE TITLE
Width of effect controls vs. keyframe timeline not saved

### ISSUE THREAD

**Issue by mdmayfield** [olive-editor/olive#571]
Very happy to see eb4c2fdad382a16bf39fce4f25b2828bd088f972 implementing #424!

One remaining loose end is the Effects sub-panes.

While project is open, after setting width to access Video Effects controls:
![image](https://user-images.githubusercontent.com/26154258/53580607-a180da00-3b41-11e9-9bf0-e743baad6203.png)

After closing and re-opening Olive:
![image](https://user-images.githubusercontent.com/26154258/53580721-da20b380-3b41-11e9-8084-c28254938cf7.png)

It may also be worth making the default width of the left-hand effects controls section wide enough to access all controls - 300-320 px for basic video effects, 400ish for the Text effect.

@itsmattkc I will give implementing this a go; let me know if you're already working on it.

**Comment by itsmattkc** [comment]
The left section actually used to automatically set its minimum width to the fit its contents, which would have addressed a lot of this, but led to #298 which was why it was taken out. I liked the behavior of it auto-adjusting a lot, but I'm not sure how to reconcile Qt glitching out like that if the window is too small.

The splitters will actually be fairly easy - all I'm doing for the panels is `saveState()`/`restoreState()` (which was funnily enough implemented for a very long time, but I couldn't get it working properly because Qt) and the splitters have the same functions. I think I'll do them because I'm thinking of putting them both into an XML file and base64 encoding them for convenience.
