### ISSUE TITLE
[FR] Suggestion: Don't auto-save unless the project has changed state

### ISSUE THREAD

**Issue by mdmayfield** [olive-editor/olive#574]
It looks like Olive is auto-saving the project unconditionally every 60 seconds. Maybe consider not auto-saving unless the project has been updated since the most recent auto-save?

One possible reason might be if Olive is left open on a computer with a project saved on a spinning hard drive - it would prevent the drive from spinning down while idle.

Not saying it's a high priority; just wanted to document it.

**Comment by Symbian9** [comment]
Also *Olive* should ask for save non-saved (new empty) project firstly before any sequence or media would be added to this project.

**Comment by itsmattkc** [comment]
It's not really "unconditional" in that it only saves if the project has unsaved changes. There is certainly value to not auto-saving again if no further changes have been made, but it'd probably require an override (of some kind) of `setWindowModified()` since that's only got two states: changed and unchanged, and we'd be introducing a second variable for whether the auto-recovery has been saved since the last change or not.

@Symbian9 I don't really agree, I think the user should be able to make small projects in Olive without having to save a project file.

**Comment by alcomposer** [comment]
> I think the user should be able to make small projects in Olive without having to save a project file.

Doesn't Olive already **auto save** unsaved projects? If not it may be good to auto-save unsaved projects, and if the user decides not to save at the end of session, to delete the auto-saves, (could even be a setting? `auto-save unsaved projects` & `delete auto-saved projects if not saved`)

The only use for auto-save would be to guard against Olive crashing, and a user loosing all of their data, without having a nag screen asking where to save. (crashing happens - even the best of software crash)

**Comment by itsmattkc** [comment]
Yes this is already Olive's behavior, i.e. auto-saving projects regardless of whether they're saved or not and automatically clearing them when they're no longer necessary. I don't think it really constitutes a privacy concern though since the projects are cached locally and never sent anywhere else. It'd be different if Olive was saving the data to "the cloud" without the user's knowledge.

**Comment by alcomposer** [comment]
> I don't think it really constitutes a privacy concern

Yes, I didn't intend that last sentence to be as serious as it probably reads. It was more about playing devils advocate. I have no problem with it myself at all. I think (as I stated) that the default behaviour of auto-saving unsaved work is a good idea.  (at least that is a [feature request] that is already done!)
