### ISSUE TITLE
[Feature request] Add "Swap channels" stereo audio effect

### ISSUE THREAD

**Issue by elsandosgrande** [olive-editor/olive#575]
I am not sure what VST can do, but having a built-in swap effect would be great (the Samsung Galaxy S4 has some weirdness when it comes to stereo recording).

**Comment by alcomposer** [comment]
There are many use cases for this, even more than 'swap'.

Such as:

* Mono to stereo
* Routing `n` channel to `n` channel (Many portable recorders allow recording of up to 8 channels, all of which may be different)

Obviously there is a difference to routing media audio channels, and actually panning them. I would say that there would be 2 aspects to this: Simple `n` to `n` routing, then allow specialist VST (or any other plugin supported by Olive) to work with the media. 

This will become even more important once olive gets surround sound processing.

**Comment by elsandosgrande** [comment]
I think there should be default presets available and there should be an option to either make a new preset, or to save the current configuration as a preset.

**Comment by frink** [comment]
Use Ardour to do your audio... The NLE is not a DAW and should not replace one...

**Comment by elsandosgrande** [comment]
Hey, I just asked for a channel swap, not surround-sound-level things. Sure, Audacity is for audio work, but Olive should have at least the basic things, like channel swapping.

**Comment by frink** [comment]
What's the reason for channel swapping? Seems like that quickly gets into the realm of sound design which is far beyond the realm of the NLE. Audacity won't work for most things either. It's a great podcast editor for trivial tasks. But for serious non-destructive audio work you need something more like Ardour or Pro Tools...

**Comment by unfa** [comment]
Actually I think coding in an effect like this is going to be very easy. The code for FillLeftRight is a nice template.

**Comment by unfa** [comment]
@frink I think that NLE cannot neglect audio, as it's a vital part of my video experience. Sure we don't need MIDI synthesizers and a full blown audio mixer, but some basic stuff shouldn't hurt. The convenience of not having to bounce all your files between different programs is a big plus. Sometimes we have to do that, but for something like swapping L and R - is it really helpful to send people out to use Ardour?

**Comment by alcomposer** [comment]
Even with an Ardour / Pro-Tools workflow, a user will need to be able to tell Olive *what* audio is *what*.

For second system sound recorders they can have many channels, (4,8,16 etc) some could be stereo, mono, etc. Some can contain boom mic's, lapel, plant, etc... An editor would want to have some control how those files are added to the project. Then sent out to a DAW.

**Comment by frink** [comment]
@unfa - I'd like to understand your case for audio in the NLE a little more.

**Where I'm Coming From:**
To me it's not a question of can it be added but rather does adding a feature push us towards our goal or away from it. The goal of Olive is a clean, intuitive, open source, professional grade NLE. My pushback here has nothing to do with whether the feature is "useful" or "easy to implement". Rather, my concern is that we stay focussed on what a professional grade editor should be and keep driving towards that.

**Case for Audio in the NLE**
By being slightly antagonistic towards audio in the NLE particularly, I'm trying to root out what the job of the NLE is in terms of audio. We need to understand and respect the dividing line between NLE and DAW. It's definitely gotten fuzzy. There's two concepts that we've talked a bit about. 1) Interoperable exchange formats... 2) Audio for editor workflow help...

I read an article someone posted the other day about ways to deliver audio to a composer. The suggestion was to put temp music in the left and dialog and effects in the right to allow for quick composition to mute reference music while keeping dialog. It's a good solution, but the foley at least needs to be stereo. I bring that up because it is relevant to why we need audio processing in the NLE...

@unfa I'm curious how you think the NLE should and should not be used for audio editing. It's a complex issue - which is why there are so many open tickets on this issue. But tell me, what is your ideal workflow?

**Specific to this issue**
I'm interested in understanding what stereo swap in the NLE give you that exporting audio and working in the DAW does not...

**Comment by artmarvin** [comment]
Routing a channel to another channel would be very useful to have fx like sidechain compression to auto-duck the audio in background.

**Comment by alcomposer** [comment]
Whatever eventuates with this request, the solution also needs to play well with interchange.

* Editor drops multi-track mono bwav file into Olive, selects boom channel, how is Olive going to mark that as the selected audio stream and then export with OpenTimelineIO for example?

**Comment by frink** [comment]
@alcomposer I've been giving this a lot of thought. I think we may be chicken/egging the thing.  We probably first need to implement the interchange format. (Assuming at this point OpenTimelineIO) and get at least one other project to use that format... ( Probably Ardour considering who has already commented on this stuff.) Then we can practically test some of the interchange philosophy that we have been batting back and forth. I don't know how we can answer some of these questions without a testbed of passing the interchange back and forth a bit...
