### ISSUE TITLE
[Feature Request] Audio recording with different codecs

### ISSUE THREAD

**Issue by BrimsonBhin** [olive-editor/olive#599]
Olive currently records in the .wav format and .wav only

Will there be other codecs in the future such as Vorbis or Opus? I believe there are some people who prefer to record in Opus instead of .wav (due to technical or philosophical reasons)

**Comment by itsmattkc** [comment]
I'm hesitant to record in anything compressed/non-PCM because high CPU usage has a chance of interrupting a recording. I know realtime audio encoding is fairly lightweight nowadays, but if Olive is already playing the current sequence while recording, I want to mitigate as much CPU usage as I can. Sure it could be deferred until after the recording, but I'm not sure people would want to wait for their recordings to be encoded each time.

If people have philosophical issues with WAV, I'm open to other uncompressed audio file formats (I know AIFF is commonly an option in cases like this too, and OggPCM looks like it'd work too).

**Comment by BrimsonBhin** [comment]
Looking back at it, this FR sort of goes against the new design direction this software's heading to

I'll use something like Audacity to record my audio (like it's intended to), no worries
