### ISSUE TITLE
[PROJECT] Automatically Relink All Media In Same Folder Upon Relink

### ISSUE THREAD

**Issue by DaniSeeh** [olive-editor/olive#610]
Didn't see this already requested, so I thought I'd suggest it. I just reorganized a bunch of my files and it unlinked almost all the media in my project, so I had to relink it all one by one. It would be nice if Olive automatically relinked every other file it found in the same directory that matched other project files.

And, maybe way down the line we could even have a Link Media Search tool like Premiere has.

**Comment by itsmattkc** [comment]
I actually think an pseudo-intelligent link media search tool is the next step. Olive's current methodology is checking if the file is relative to itself (the containing folder was moved) or relative to its original position (the project file was moved). I think the next step is a full on heuristic design for relocating media.

**Comment by frink** [comment]
This should probably also be couched in a larger discussion about why we move files and folders in the first place...

**Organization Workflow**
Basically there are three use cases I can think of off the top of my head:

1. **Renaming captured files to be more descriptive...** The only way to detect changes like this is to maintain a set of file hashes and look for a file which bears this hash...
2. **Relocating folders for space or organization...** In this case the same mechanism of a hash table could be used to find the fingerprint of that folder...
3. **Editing media externally and moving things for the sake of versioning...** This has no easy solution yet. Symbolic links may be a simple elegant way to manage versions without requiring the copy of media. Otherwise, I'm not sure.  Since the underlying media was changed we don't know whether it was intentional to replace a piece of media with a new piece of media or whether the overwrite was an error...

Are there other reasons that we move and reorganize media that I've missed?

**Comment by DaniSeeh** [comment]
Relying on Symlinks would cause trouble on Windows though right? I can't think of any other reasons people move media.

**Comment by frink** [comment]
If we used some form of symbolic linking it would have to be our own format rather than the UNIX default. (Although, I've heard speculation that the next version of Windows may support symlinks... Here's hoping...)

I like where @itsmattkc's thinking is at. Relocating large files is a pain. It's not quite as bad as trying to send them through the internet. But it still makes everyone's butts sore for sure...

**Comment by itsmattkc** [comment]
Footage relinking functionality was added in a recent commit
