### ISSUE TITLE
[Feature request] Switch to or allow Breeze QStyle

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#625]
I am using KDE Plasma and Fusion does not look as good and native as the default Breeze "QStyle".
While this is subjective I would really like seing the Breeze design as default or at least as an option therefore I dont have to go into the code after every update and recompile it which takes a really long time.
Thank you for taking the time and keep up the great work!

**Comment by oc1024** [comment]
Similar to #606

**Comment by frink** [comment]
Is there a way we can abstract some of this stuff so that people can style however they want? Most NLEs and DAWs have a style switcher of some sort. While this isn't really a big deal in terms of usage, a preferred interface really helps power users enjoy their time in the program.

If we marry one style and customize our own components we will be forced to close most requests of this sort from the get go. If we abstract things from the beginning then we won't have to do so much wrangling of style requests since we just send them to restyle things themselves...

Either way, we need to make the decision transparent to the users...

**Comment by itsmattkc** [comment]
@frink It already is to an extent, Olive can load QSS files to style its UI:

![](https://cdn.discordapp.com/attachments/550374368383991821/555236273615536128/unknown.png)

It wouldn't even be hard to get Olive to use the native OS styling. The difficulty would be making it look decent since most UIs use light styling and Olive is designed for dark styling:

![](https://cdn.discordapp.com/attachments/550374368383991821/555239935414894603/unknown.png)

**Comment by frink** [comment]
That first one looks sweet!

Perhaps including several QSS files and switching between these themes might be as fancy as we need to get. Ardour does something similar with GTK. Looks great...

**Comment by itsmattkc** [comment]
Olive can now be switched to use native styling rather than Fusion (which is still the default).

**Comment by frink** [comment]
That's the simplest solution!
