### ISSUE TITLE
Strange audio glitch at split points

### ISSUE THREAD

**Issue by SebastianTheFish** [olive-editor/olive#63]
This seems to be with the razor tool itself, not just the shortcut.

**Comment by itsmattkc** [comment]
This is caused by Olive not stopping the previous audio precisely at the timeline out point which means a little bit leaks over into the next clip. This technically affects any and all audio in Olive but is most noticeable when splitting an audio clip and playing the two split clips one after the other.

This may or may not be exacerbated by the second audio starting not precisely at the clip's in point as well, causing a skip (Olive seeks to a timestamp in the audio and retrieves a "frame" - really a chunk of, say, 2048 samples or something - but said "frame" may not begin precisely at the timestamp requested meaning I might have to make it skip a few samples to make a seamless transition - this is also why the first issue occurs, Olive plays until the end of the "frame" rather than calculating what part of that "frame" is the out point and stopping there).

**Comment by itsmattkc** [comment]
As of 26f7b5a15deb255b1d961b776c4c414d65422aa0, audio playback is ludicrously more intelligent now and this has now been fixed.
