### ISSUE TITLE
OS freeze while exporting video from Olive

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#644]
### System Information

**Olive version:**  f00d2ff (git master)
**Source:** Github
**Operating system:** Linux Mint 18.3
**CPU:** Ryzen 7 1700
**RAM:** 32GB
**GPU:** NVIDIA Geforce GTX 1060 6 GB (Nvidia 384.130)

### Detailed Description

The whole system freezes when exporting video from Olive.
Happens every time I try to export anything from Olive if I let it run long enough.
Out of a few tries - no video was exported fully without freezing the OS.

### Steps to reproduce

Render any video. Wait a few minutes - the OS will completely freeze.

### Output Log
I've captured dmesg output on another machine:

[dmesg.txt](https://github.com/olive-editor/olive/files/2985392/dmesg.txt)

**Comment by unfa** [comment]
I've had two attempts to reproduce in `54c03ef` commit, to no avail so far - these are first two renders from Olive without a crash or system freeze ever on my side. Woo-hoo!

**Comment by DaniSeeh** [comment]
Such a strange issue to crash Linux Mint completely. I wonder if it might not have been entirely Olive's fault, an interaction between OS and Olive together. A combined error of some sort

**Comment by itsmattkc** [comment]
The dmesg output indicates the NVIDIA driver is what crashed, which makes sense since it's about the only system component that _could_ crash using Olive.

Putting aside the fact that the fairly high level OpenGL probably shouldn't be able to crash a driver, give the `furtherocio` branch a shot. It standardizes strictly around OpenGL 3.2 Core rather than the mishmash of OpenGL 1 and 2 in `master`.

**Comment by unfa** [comment]
I can't reproduce in the current Master branch, so I think we can close this for now.
