### ISSUE TITLE
Freeze with image sequence

### ISSUE THREAD

**Issue by bernique** [olive-editor/olive#664]
### System Information

**Olive version:**  March 2019 alpha f0dd2ff
**Source:** Website
**Operating system:** W10
**CPU:** Intel i5-6300U
**RAM:** 8GB
**GPU:** Intel Core i5 Integrated Graphics

### Detailed Description
I am new with Olive, with a project based on large image sequences. I have had several freeze of the program while reading some sequences. I Finally think to have found the reason: all images in the sequence need to have successive numbers. In my case, the freeze was on sequences where I had deleted some images. After renaming images with the right numbers everything went fine.
I have another bug: when I import some pictures from a folder, Olive imports all the images of the folder.

**Comment by AGI-THB** [comment]
your version is old.

try a recent build and give feedback.

**Comment by bernique** [comment]
I have updated to latest built, but the bug can be reproduced. I have 500 pictures with names including successive numbers. If I keep all pictures, I can import the sequence and display it fully. If I delete some pictures, I can import, but everything freezes when I play with the sequence.

**Comment by itsmattkc** [comment]
@bernique I think you answered your own question: Olive won't like it when you have an image sequence with missing indices. The fix was preventing it from locking up indefinitely, so you should be able to seek elsewhere and recover. But no, it won't play an image sequence with missing images smoothly because that's an error. Is there truly a use-case for an image sequence that's missing frames?
