### ISSUE TITLE
Cannot insert a keyframe into Graph Editor

### ISSUE THREAD

**Issue by MisterTeeXD** [olive-editor/olive#681]
### System Information

**Olive version:**  [cc69f5b]
**Source:** [.exe on daily build page]
**Operating system:** [Windows 10 64bit]
**CPU:** [Intel i5-6400]
**RAM:** [4GB]
**GPU:** [Intel Graphics 530 128MB (Latest Drivers)]

### Detailed Description

[For some reason, i cannot get to insert a Keyframe into the graph editor, even if i click the Keyframe button]

### Steps to reproduce

[Open up the graph editor, click on an image and then click on the Keyframe button, there won't be a keyframe inserted]

### Output Log

```
[Non right now]
```

### GDB/CDB Backtrace (for crashes)

```
[Non right now]
```

### Note

Here is a gif i recorded showing the problem:
![a2h0e6ZHc1](https://user-images.githubusercontent.com/37266538/54872523-e6f59780-4dcd-11e9-861f-ecf65457071e.gif)

**Comment by itsmattkc** [comment]
You need to enable keyframing on the row you want to keyframe in the Effects panel first.

**Comment by AGI-THB** [comment]
I noticed a small UI-bug.
when i have keyframes enabled (eg. on the scale property, the clock symbol indicates that it is set) and some keyframes are set, Olive asks me if I want to delete all keyframes, when i decide to klick on the clock-symbol again.
Now this is of course the expected behavior.
BUT when i tell Olive "no" (i dont want to disable keyframing on this property) the clock symbol still switches to unset-mode.

I hope you understand what i mean.

**Comment by itsmattkc** [comment]
@AGI-THB Fixed in ad44b00eb390e0c88fa93bc085aaf58c482b0f71
