### ISSUE TITLE
Add "Format" ("Units") option for "Timecode" (frames, miliseconds, etc.)

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#726]
Add option to "Timecode" for set units/format indepently from global units.

Currently "Timecode" depend on global units.

**Comment by frink** [comment]
Which units did you want to support? How would the conversion of units work?

Paul from Ardour is doing a major rewrite currently in order to support time conversion between different units. Depending on how crazy you go time conversion can become much more difficult than it probably needs to be...

That said. I think we're all open to the idea just trying to think how this would be helpful to a pro editor who almost always edits either in terms of reel film length (old style) or SMPTE time (new way) or by Frame number. Just wondering what scenarios this solves...

**Comment by Symbian9** [comment]
> Which units did you want to support?

Same as *Olive* already support.

Just want keep separate units of each applied "Timecode" effect from global units

**Comment by itsmattkc** [comment]
Same as #723
