### ISSUE TITLE
Blur Issues

### ISSUE THREAD

**Issue by MrTeeXD** [olive-editor/olive#730]
### System Information

**Olive version:**  [a581d36b]
**Source:** [zip form github]
**Operating system:** [Windows 10 64-bit]
**CPU:** [Intel i5-6400]
**RAM:** [4GB]
**GPU:** [Intel Graphics HD 530 128MB (Latest Drivers)]

### Detailed Description

[When applying the blur effect in one clip only, it applies to other clips as wel]

### Steps to reproduce

[Click the "Add Video Effect" button and select any blur effect, look at other clips to see if the effect has been applied as well]

### Output Log

```
[Nothing]
```

### GDB/CDB Backtrace (for crashes)

```
[Nothing]
```

**Comment by cgvirus** [comment]
I think it's a feature rather than bug. If you select multiple strips and add effect, all selected strips will have the effect.
You need deselect all the strip with crlt+shift+a  or just click outside the strip to deslect, then select desired strip and effect.
It seems we can also animate it with multiple strips.

**Comment by MrTeeXD** [comment]
I only had one clip selected at that time

**Comment by cgvirus** [comment]
reproducible only selecting multiple strips here:
Olive version: [a581d36]
OS: Debain 10

**Comment by MrTeeXD** [comment]
I had one clip selected, only one and it gave the others the effect which i did not do

**Comment by cgvirus** [comment]
No problem, May be a bug with Windows version. Tagged just to confirm the behavior in Linux version.
