### ISSUE TITLE
Add an "Invert" option to the Crop Effect

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#789]
It'd be great if the Crop effect could work in reverse.

Instead of cutting a rectangle from the middle and rejecting the outer parts - I'd sometimes like to reject the inner parts and just keep the borders.

**Comment by DaniSeeh** [comment]
This might ultimately be treading on Masking territory and already be planned to be handled via that avenue. Up to @itsmattkc on how easy this would be to implement and whether it is worth doing or just waiting to Masking naturally fills that demand.

**Comment by frink** [comment]
If we're talking masks there should be good feathering to go with that...

**Comment by unfa** [comment]
Looking at Nodes - possibly an Invert node (effect) could be added with option to select which channels should be inverted (R, G, B, A).

That'd make it much more useful.

**Comment by cgvirus** [comment]
@unfa 
Have created a pull request. For now you can check it here:
https://github.com/cgvirus/olive/blob/master/effects/shaders/crop.frag
https://github.com/cgvirus/olive/blob/master/effects/shaders/crop.xml

**Comment by itsmattkc** [comment]
I think a general "alpha invert" node in the node restructure would be the best long-term solution here

**Comment by cgvirus** [comment]
Or better a node named invert where R G B or A can be inverted with bool.

**Comment by itsmattkc** [comment]
Hmm I'm not sure there's such thing as inverted R/G/B in scene linear. @sobotka ?

**Comment by sobotka** [comment]
@itsmattkc Ha! I had a long post to this very issue, then deleted it because I didn’t familiarize myself with the code.

You are indeed absolutely correct, and it is quite a wise observation. Even `max(RGB)` will have a shortcoming unless calculated every time. “Negative” is literally an output referred distillation.

Most of these sorts of slipper ideas can be more accurately solved if they are broken down to what they are trying to do. For vignette, thankfully, it’s quite easy: It constricts light near the periphery of the lens due to optics and construction.

So what does “invert” do? Is it inverting the light constricting in the centre region? Is it increasing the exposure in the vignette region?

The two seem like similar questions, but they are quite different. Decreasing exposure is a simple multiply against a value `<= 1.0` and works fine in scene referred linear. Likewise, so does increasing exposure when applied on values `> 1.0`. I’m just not sure what need an “invert” is solving in vignette, nor even sure vignette is a useful operation to have as a separate “effect”. Wiser might be to simply use the multiply operation fed with a mask, which solves all vignette needs as well as secondary grading to augment exposure on a keyed / rotoed region, and other contexts as well.

**Comment by sobotka** [comment]
Specifically addressing @unfa’s comment, this would probably fall into a “canvas” operation? Growing / shrinking extents would seem part of that.

**Comment by cgvirus** [comment]
When mask will be implemented this will be no longer an issue as we can simply invert the Luma (well, should have this feature). 
We have an invert effect which inverse RGB altogether to create negative effect. I can enhance it to invert separate channels which will be 1.0-R etc. Not sure though about scene linear, if it uses >1.
Invert can be an useful node if Olive is involved or have plan in composting or channel shuffling. Other than that not that useful

**Comment by sobotka** [comment]
@cgvirus See above. “Invert” doesn’t have meaning in a scene referred model; the values range from zero to infinity.

**Comment by cgvirus** [comment]
@sobotka agreed.

**Comment by unfa** [comment]
Maybe it'd make sense to have a tool that'd invert RGB, or other values (Luma?), but only after clipping the input to 0-1 range?
Becasue that can be a useful artistic tool, when we're not going for preserving the dynamic range and "realistic" look.

What do you think?

**Comment by sobotka** [comment]
"Luma" isn't a thing. Or rather, it _is_ a thing, but folks toss all sorts of terminology around without considering the context. So to start, Olive operates on RGB, which is relative. There is no _luma_ nor _luminance_ unless the RGB data is transformed accordingly, which is a whole other kettle of fish.

**Comment by unfa** [comment]
@sobotka Alright. When we render out H.264 we are producing RGB values between 0-255.
This is aligned with the current 8-bit pipeline Olive has.
Now with the new CM-ed pipeline we're not limited to that. We can have RGB values between -Inf and +Inf, - however for the final distribution format (often 8bpp 4:2:0 H.264 streams) all these values have to be fit into the 0-255 integer range (they even have to be squeezed into that range for display).
That can be done with transfer curves for a gentle, pleasing effect, but maybe you want to do other things?

So imagine I'm working with display-reffered footage (screenscast). The RGB values fro that footage will never exceed the 0-255 range. There's no reason I cannot perform an inversion on the RGB values using the "0-1" float range and discaring everything outside, as there's nothing to discard in the first place.

I don't agree that clipping isn't a good thing to do ever, because artistically sometimes *wrong* things are *right* - and you cannot dispute an artistic decision. You may disagree with, but you can't say it's wrong. Of course it's not a good way to retain high-quality of your work if you're going for that, but I think a Clamp node still is going to be useful in some situations.
It could be a very destructive operation on a camera footage - but maybe I want a brief screen flash and this is exactly what the piece calls for?

I could still do this with RGB Curves, right? I would only need to manyally clamp the values to unwanted avoid artifacts.

Let me draw an analogy from the music history - The Beatles were experimenting with new sounds, and they made a sound engineer overdrive a mixer preamp while recording a guitar fro one piece - that was technically *wrong* and the engineer wasn't happy about it. But it served an artistic purpose and started a revolution in music.

I think a good tool lets you do *wrong* things, as that often leads to creating amazing art, and history-changing discoveries.

Also - you can't stop a noob from braking stuff anyway, so why bother? ;)

**Comment by cgvirus** [comment]
There are needs, in fact in my own project :). I have to enhance the existing invert node either way. A classic example is editing to mimic flashback.

**Comment by sobotka** [comment]
> That can be done with transfer curves for a gentle, pleasing effect, but maybe you want to do other things?

Not sure what you mean here. You are _always_ rendering a scene referred domain image buffer to a display / output referred state, and _always_ doing it via a transform. No exceptions. Even simply lopping off scene referred data is indeed a transform, albeit one that is disconnected from meaning.

>So imagine I'm working with display-reffered footage (screenscast). The RGB values fro that footage will never exceed the 0-255 range. There's no reason I cannot perform an inversion on the RGB values using the "0-1" float range and discaring everything outside, as there's nothing to discard in the first place.

Except the internal model is scene referred. It just so happens that our entry point is rather unfortunately garbaged up a bit. That means that in reference to the internal pipeline, it's still operating under a scene referred model. A simple example would be exposure. If you bump up a display linear image by two stops, it's fine because you are operating on scene referred data. That means that even though your data is only display linear, you've still correctly slid it up two stops.

> - and you cannot dispute an artistic decision. You may disagree with, but you can't say it's wrong. Of course it's not a good way to retain high-quality of your work if you're going for that, but I think a Clamp node still is going to be useful in some situations.

This is discussing default assumptions about data state, which helps the architecture immensely. Assuming a clamp comes around, it can be applied incorrectly as one wishes. By default however, the assumption is that the data in the reference space is of a particular set of chromaticities, under a particular white point chromaticity, and operating under a scene referred model.

> It could be a very destructive operation on a camera footage - but maybe I want a brief screen flash and this is exactly what the piece calls for?

That isn't done via a clip.

>Also - you can't stop a noob from breaking stuff anyway, so why bother?

The point I'd make is that in order to have a properly managed system, certain assumptions must be made about the state of the reference space. This is about those assumptions, and under those assumptions, no such idea of "inversion" exists.

**Comment by unfa** [comment]
I see. Thanks for the clarification, @sobotka .
I think I now understand a bit better why this is a problem when we're working in scene reffered color space.
How do you do Curves in such space anyway?
I know Blender extrapolates the Curve outside the "nomianal" 0-1 range, but one can actually zoom out and work with the curves in any range.

I'll have to find my way to work on display-reffered footage in a scene-reffered pipeline - but I think even that will have it's benefits. Like opening me up to a broader world of possibilities.

**Comment by sobotka** [comment]
>...when we're working in scene reffered color space.

To clarify, scene referred is an _attribute_ of a well defined model, not _the_ model; scene referred is a _facet_ of a well defined model, not a colour space per se.

>How do you do Curves in such space anyway?

It's a great question. UI elements expose a transform on the UI. This allows the pixel pusher to choose the appropriate transform for the data. For example, if your transfer function is mapping from `-0.125` to `55.432` scene referred, you could select the appropriate transfer function on the curve interface, and the minimum to maximum portion of the curve would be mapped appropriately. There are other useful facets to having per-UI transforms of course, including the ability to select from a greyscale representation of a colour picker, properly range non-colour data values, etc.

>I know Blender extrapolates the Curve outside the "nominal" 0-1 range, but one can actually zoom out and work with the curves in any range (even on negative values).

Blender's existing system is horrific. Worse, there are internal inconsistencies that make for a randomly generated shibboleth. When discussing things like inversion for example, it's important to pay attention to how some applications violate the internal reference semantics and make things a nightmare for the end audience member. Blender is a _fantastic_ example as to how *not* to do things with regards to pixel management.

> I'll have to find my way to work on display-reffered footage in a scene-reffered pipeline - but I think even that will have it's benefits. Like opening me up to a broader world of possibilities.

If your content is strictly stuck in display referred land, you still gain from display linear manipulations, and the huge payoff that comes with that. It shouldn't be terribly different from what you are used to, other than a few incompatible ideas missing and a few new concepts.
