### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by ekself** [olive-editor/olive#797]
[If you are reporting a bug, please try to fill out all the information below. If you are requesting a feature, you can clear this template.]

### System Information

**Olive version:**  Olive (March 2019) 6264123b
**Source:** https://www.olivevideoeditor.org
**Operating system:** Windows 10 32bit
**CPU:** Intel G850 @ 2.90GHz
**RAM:** 2GB
**GPU:** Unknown

### Detailed Description

I do not get any picture in the sequence viewer

### Steps to reproduce

[Describe the steps to demonstrate the issue you're reporting]

### Output Log

```
[Paste output log]
```

### GDB/CDB Backtrace (for crashes)

```
[If you can reproduce this issue, try running Olive through GDB and retrieving a backtrace, then paste the backtrace here. Instructions are available in the Wiki on how to acquire this backtrace.]
```

**Comment by qubodup** [comment]
Thanks for reporting. People mentioned similar in the comments of videos.

Does this happen with video or images/photos?

Does it happen with ALL files or only some files?

If you have not tested a JPG or PNG file yet, what happens if you test using a JPG or PNG file?

What file format are your affected files? MTS? MP4? AVI? JPG? PNG? WEBM?

What were the files made with? Camera? Phone? OBS? Downloaded? (from where)

If you recorded these files, is it possible to make a short test recording and upload that to google drive, mega.nz, dropbox or similar for us to test?

If none of the above helps, can you try following the steps in https://www.youtube.com/watch?v=ee04vna0_eU and tell us at which time code (eg 00:23) it doesn't work any more?

If you don't know where to get PNG/JPG etc files for testing, you can get them here: https://www.youtube.com/watch?v=1IHGBRFXUGM

**Comment by itsmattkc** [comment]
>GPU: Unknown

Please determine your GPU and ensure its drivers are installed and up to date.

**Comment by mpmc** [comment]
Small note, **the URL in OP isn't the correct one**. Do not go to that site, in my case it tried to trick me into installing a "security check" extension to chrome. Amusingly when you cancel the install it plays an audio file announcing this and then redirects to olivevideoeditor.org 🤣

**Comment by itsmattkc** [comment]
@mpmc Interesting, thanks for the heads up. I've edited the OP to direct to the correct URL to be safe.

**Comment by qubodup** [comment]
mpmc: ouf. whois info: Created Date: 2019-04-12

bloody scammers

**Comment by mpmc** [comment]
Here's the URL I get redirected to for those interested...
```https://gsafe.getawesome6.com/wim/static/wi/main3.html?tp=iw&cid=8201&v=23&gnum=6&clickid=00240416p072022755073&cachecode=Q69zqzb-wyejD9Pn4kg9Rg&q=olivevideoeditor&dkw=olivevideoeditor.com&g=GB&cc2=9OSGlC3u2ByIUU2oEKKCnQ%3D%3D%3AZmVkY2JhOTg3NjU0MzIxMA%3D%3D```

**Comment by itsmattkc** [comment]
I find the timing of this suspicious. Domain was registered yesterday, this is the first issue OP has made with no previous activity (indicating the account is probably new), weirdly formatted title and post, with the wrong URL and malformed markdown (pre-edit). If OP shows this to be a legitimate issue, I'll re-open this.
