### ISSUE TITLE
PyQt/Pyside

### ISSUE THREAD

**Issue by Chadt54** [olive-editor/olive#808]
Along with Python scripting, if your interface was implemented using Qt, you could allow for python scripting with PyQt/Pyside to allow users to create their own interfaces for their plugins.

Most of the Python enabled applications that I referenced in my python feature request also allow for programming with (usually PySide2) for more advanced plugins.

**Comment by Chadt54** [comment]
And if implemented correctly, you could allow the Python scripting to access all areas of the main application's interface and users could add their own menus, buttons, etc. right into the application as if it was built in from the start (I've written applications for Nuke/Hiero that integrated the application with the cloud (Shotgun Software) to sync our company's shots, and the way I wrote the extension made it look like the plugin was apart of the original software, since it was able to integrate into the menus throughout the project, and even take on the color scheme used by the application by default)

**Comment by Digitante** [comment]
This would be of great use to us on "Lunatics!"/FilmFreedom project, because it would provide the necessary hook for our context-aware TACTIC client (proposed - there's a description and PyQt/PySide based mock-up on our "KitCAT" github: https://github.com/Digitante/kitcat/wiki ).

I know that project is a long way from fruition, but I just want to be clear that there is a concrete use-case for this, and it would be a reason for us to migrate from Kdenlive to Olive in the near future, since Kdenlive doesn't have this.

Our idea is to add a hook in the UI to open the KitCAT app in another window (the UX effect is similar to KitCAT being part of the program, though in fact it's a separate app and process). The plugin would access context information -- project status/metadata, etc and allow the KitCAT client to retrieve related status information from the studio server, thus bringing all of the project management information to the editor's fingertips when working on a cut in a team project. Similar functionality is planned for Blender and other creative applications, also using scriptability. It's typically going to be limited by just how much the various apps allow this kind of scripting.
