### ISSUE TITLE
Consider supporting Mac OS X 10.9+ with Qt 5.6+

### ISSUE THREAD

**Issue by follower** [olive-editor/olive#899]
### Background

In my experience, Apple's relatively recent yearly OS update/deprecation release cycle has led to Qt-based FLOSS software being much less well supported than it used to be--even when the software doesn't actually use/need any of the new "features".

This seems to be driven primarily by:

 * Homebrew's policy of not supporting older/multiple Qt versions. (And, I assume, being the most common method of installing Qt-based FLOSS software on Mac.)

 * Qt's apparent policy of reducing the number/years of older OS versions supported in LTS releases. (Even their *support* of describing which versions they support has decreased! But, see: [5.6-5.10](https://doc.qt.io/archives/qt-5.10/supported-platforms-and-configurations.html#qt-5-6), [5.11](https://doc.qt.io/qt-5.11/supported-platforms.html#supported-configurations), [5.12](https://doc.qt.io/qt-5.12/supported-platforms.html#supported-configurations).)

 * Apple's handling/support of SDK releases.

 * Continuous integration providers.

These policies make sense in relation to reducing their workload and not having to deal with Apple's general lack of interest in supporting these projects or older releases.

But to people running older Mac OS X/macOS versions for whatever reason, it's a bit a galling to not be able to run a piece of software even though it's theoretically possible (e.g. it's not actually *using* any more recent features). (Particularly when a non-trivial application like Blender supports OS X 10.7+ (for v2.79) and OS X 10.9+ (for v2.80 beta).)

Anyway, this isn't really a Olive-specific rant, it was just something that had been on mind and was related to #894. :)

I realise that it *is* a non-zero amount of extra work to test/support older platform/toolkit releases and it's understandable when projects choose to not.

### Qt workaround

For access to older Qt versions, rather than building against the Homebrew supplied Qt it's possible to download binaries from e.g. <https://download.qt.io/official_releases/qt/5.6/5.6.2/>.

### Olive-specific modifications

The only two source changes I needed to make to get the current version c5f63ec2 of Olive were:

 * PR #898: "Remove `makeCurrent()` call that sometimes causes blank previewers."
 * PR #900: "Fix Qt 5.6 compatibility" (includes "[Fix to work w/ Qt 5.6+ removes non-critical `setDesktopFileName()`](https://github.com/olive-editor/olive/pull/900/commits/ddb57dcb6a9ea9146cd773fc2d1ad1f0d5005f2c)".)

Neither of which should negatively impact building with later version.

### CI Compilation modifications

In terms of CI compilation settings it should be possible to support older OS version releases with use of TARGET version flags but at a certain point it might also require older toolchain versions and/or SDK versions (which do apparently exist here: https://github.com/phracker/MacOSX-SDKs).

### Conclusion

Anyway, I hope that you are able to merge my two PRs as with them I was able to happily run Olive, create a test sequence and export it with Qt 5.6 and Mac OS X 10.9 combination.

And, if you'd also like to support older OS/framework versions hopefully this has pointed out some useful approaches for doing so.

Thanks for your efforts on Olive & reading all this. :)

*Edit:* Add/update some links.

**Comment by follower** [comment]
And who doesn't like pretty pictures..? :)

![olive-xclt-mac-osx-10 9-build-screenshot-02](https://user-images.githubusercontent.com/189962/57015269-0ce14800-6c68-11e9-8308-bcbe96232ba1.png)

**Comment by itsmattkc** [comment]
Funnily enough Olive used to specifically target Qt 5.6 for 10.9 support, but there were a number of issues with users running 10.12 (probably 10.12+). Updating the Qt version seemed to address it (while unfortunately killing off old Mac OS support). Not sure if there's a happy medium to supporting 10.9 and newer versions (I'm guessing there are just weird Qt incompatibilities), but I'm happy to merge the PR so it can at least be compiled.

**Comment by follower** [comment]
Yeah, I suspect multi-version binary compatibility is probably a lost cause but multi-version source compatibility should be attainable (assuming appropriate Qt version checks/feature usage).

I've been over some of this Qt/Mac version compatibility ground via https://github.com/LMMS/lmms/ before and the end result was that LMMS now releases two binary/dmg versions (10.8+ and 10.13+) which seems like a workable approach: https://github.com/LMMS/lmms/releases/tag/v1.2.0-rc8

I'm not 100% sure what process is used to generate the two binaries but I'm sure @tresf has nothing better to do with his time than tell us. ;D

**Comment by tresf** [comment]
> I'm not 100% sure what process is used to generate the two binaries but I'm sure @tresf has nothing better to do with his time than tell us. ;D

The newer binaries are simply built by a Mac in CI.

The older binaries are much more interesting.  I have a full tutorial in the wiki's Mac section but in short, I use a 10.8 VM in Parallels for the system and Homebrew for the dependencies.  It's gets worse...

* The SSL support is grossly dated so I have to shim a newer `git`
* As mentioned above Homebrew abandons backwards compatibility, so instead I use a formula commit (e.g. qt5.rb at commit hash a1b2c3d) by URL and wait for Homebrew to build.  It's so much trial and error to get a working version that I need to keep the exact URLs in the wiki so I can rebuild the environment if needed.
* I have a few manual patches I apply as well, also documented in the wiki.
* ... and if course I commit patches upstream if they don't hinder the project.  Having commit access really helps with the trivial stuff.

I've been told that older SDKs can be targeted directly on newer machines but never had luck running them afterward.  Keeping around the old VM has been the most reliable approach.

That said, I try not to go against the norm.  If an OS is discontinued, often in binaries can be obtained (instead of Frankensteining a VM and trying to offer support).  LMMS also has bugs that are Qt-specific that linger in the old builds but not the new.
