### ISSUE TITLE
[Feature Request] Freeze frame

### ISSUE THREAD

**Issue by sssssamvh** [olive-editor/olive#902]
### Detailed description of the feature request

I'd like to request a Freeze Frame feature.
1. Select a clip in the timeline.
2. Place the playhead on the desired frame.
3. Hit a shortcut key combination.
4. The entire clip now consists of the chosen frame, but keeps its duration.

### Why should Olive include the feature? What are the benefits?

I've used Olive in a project similar to ones I've previously used DaVinci Resolve in. These projects are mostly demo reels for the studio I work at, and in Resolve, being able to freeze a clip to a certain frame allowed us to then show a breakdown of said frame. I'm sure there are more cases for which this feature will come in handy.

**Comment by follower** [comment]
![breakfast-club-freeze-frame-maxresdefault](https://user-images.githubusercontent.com/189962/57074040-fb1aa600-6d36-11e9-80de-0deeefacb60e.jpg)

(Totally including that as an example and not just as an excuse to meme. :D )

Just for context for @itsmattkc, when you say "demo reels for the studio I work at" do you mean 
Blender Animation Studio? :)

**Comment by sssssamvh** [comment]
> when you say "demo reels for the studio I work at" do you mean
Blender Animation Studio? :)

That's the one! :)

**Comment by unfa** [comment]
BTW - you can workaround the animation problem with slowing down a single frame to a freeze by NEsting that strip into it's own Sequence, and adding effects onto that sequence - you can animate that normally then.

**Comment by musaire** [comment]
In Sony Vegas I have always captured frame (save frame as..  - it saves to the project "bin") of the original material and then used it as an image and dragged out to a clip as long as needed. 
Freezing with one click is obviously more convenient and quick.
This feature shouldn't be a priority. :)

**Comment by sobotka** [comment]
I strongly suspect that this “feature” is a really awful UI solution provided by another poorly thought out application. I’m going to close this because, having thought on potential design approaches, it is really an idiotic thing.

**Comment by sobotka** [comment]
Whoops, wrong issue. Sorry peeps.

**Comment by sobotka** [comment]
Posting this because I accidentally deleted it.

> In Sony Vegas I have always captured frame (save frame as.. - it saves to the project "bin") of the original material and then used it as an image and dragged out to a clip as long as needed.
> Freezing with one click is obviously more convenient and quick.
> This feature shouldn't be a priority. :)

For the record, this is an _awful_ UI design. The idea of freezing a single frame like Vegas does it is a great tip that it’s to be avoided.

It’s essentially setting an in and out point and extending the relative duration.

**Comment by musaire** [comment]
> It’s essentially setting an in and out point and extending the relative duration.

Oh yes, I could have also solved this problem of freezing the frame in Vegas by cutting out a single frame, left it on timeline, and then making it a subclip (otherwise Vegas and most other software recover the cut-out parts when extending) and then extending it to desired length.
Not sure where the UI topic comes in :) but all the captured frames were acting the same as all the images with its default clip lengths (ca. 2sec) when brought to timeline. I was more worried about the captured frame's compression to a picture format, should have tried subclip route. Luckily these wasn't too serious projects, though frames from 4K footage look like decent quality photos.
Anyway, not a critical one-click feature. I would always work around somehow lol.

**Comment by sobotka** [comment]
The UI topic comes in because it is clear that Vegas is a ghastly shitbag solution.

It strikes me that a “frozen frame” is nothing more than the relative in and out representing a single frame, and the relative duration being repeated. Adding functionality when in truth it is the same concept as a generic edit / in out setting is bonkers.

This came up in the other “screenshot” issue, that needs closing because it too feels like someone had mucked with the junkware instance and arrived at it being somehow a design solution, when it just is a nuance of aforementioned junkware.

**Comment by musaire** [comment]
Haha. I agree.

**Comment by dimitarsp** [comment]
I could envision two possibilities by right clicking on a clip and selecting a new option hold/freeze frame to do either of the following:
- provide a nice user interface for users that want a quick way to freeze a frame with the method described
- automate the process of extracting a png of the current frame, place it in the same place that WAV files are saved, and position it on timeline, maybe on a new channel above the current clip

**Comment by alcomposer** [comment]
NLE is non-destructive. So freeze frame would need to be in-timeline.

Problem is that images added to timeline should  be media added to project (photos, graphics etc). Not stills that already exist in the video file.
