### ISSUE TITLE
[Bug] Fail to open recent projects with accent marks in the filename or path

### ISSUE THREAD

**Issue by dinilu** [olive-editor/olive#954]
**Your Setup:**
- Olive version (window title or Help > About): Olive (March 2019 | Alpha | 8cef5ce9)
- Source: website
- Operating system: Windows 10
- CPU: Intel Core i7 CPU 920 @ 2.67GHz
- RAM: 19Gb
- GPU: NVIDIA GFORCE 210 

**Describe the Bug**
If I try to open from the "File -> Open recent" menu a recent project which name has an accent mark in the filename or path the program refuse to open it with the next error message:
Specified project 'D:\Universidad de C�rdoba\Regina Berjano - Proyecto innovacion docente\Proyecto 2018_19\Tema Terrestrializacion\Video\Terrestrializacion.ove' does not exist.

Where the symbol "�" should be a ó.

**To Reproduce**
1.- Create a project which name or path has any of the different characters: á, é, í, ó, or ú. 
2.- Close Olive software
3.- Open Olive software and try to open the project from the "Open recent" option in the "File" menu, or double click in the project.ove file in the windows folder.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/6606471/57703353-2ae37b00-7660-11e9-8587-1a3345693913.png)

**Comment by DaniSeeh** [comment]
This is a very old build, and the version is prior to the major rewrite occurring now. This may already be fixed or simply irrelevant due to the present save/load troubles.

**Comment by dinilu** [comment]
Is there a newer build for windows? I dowloaded the file 2-3 weeks ago and seems to me there is no updates. Anyway, sorry if the report was outdated.
The RAM configuration is the result of an update in an inherited computer at the office. I think the configuration is 3x1Gb + 2x8Gb.

**Comment by DaniSeeh** [comment]
There is actually a major rewrite to nearly every part of Olive occurring at the moment. Because of this, 0.1.0 has been tagged off and is the version people should use if they just want to edit video. However, for testers the current continuous build is where all the useful work can be done. Matt and and the other devs are working on rewriting the timeline, adding caching, and reworking the entire way that effects and almost everything else related to the way clips organize themselves work. Essentially, a nodes backend is being created, and a GUI for that backend is in the process of being decided. Color has already been reworked, and FFmpeg is likely to start taking more of a backseat as well and not being so intimately relied on. All of this is going to take a ton of work to pan out, and we will all just have to patiently wait (or if you can code, contribute where you can). Because of all this being merged into the master branch only about a week ago, builds from even that short a time ago are practically useless in terms of testing. The download on the website is likely to point to 0.1.0 until all these changes start to reach some semblance of stability, but for now making bug reports for 0.1.0 is likely not going to be particularly helpful (unless Matt corrects me on this and I am totally wrong.)

**Comment by dinilu** [comment]
Got it! Thank you for the explanation and the incredible work you are doing with Olive. I was impresed when discovered it. The most advanced and stable video editing open-source software I have found even being an alpha version.

**Comment by DaniSeeh** [comment]
Haha, not me. I'm just a tester and community moderator. But the dev team is doing amazing work. The lead developer is ItsMattKC, with sobotka and alcomposer also helping out a lot. Others have also contributed.
