### ISSUE TITLE
[Feature Request] Considering typeless timeline design in the road map

### ISSUE THREAD

**Issue by malnaanah** [olive-editor/olive#966]
I have just read the roadmap on patron page  https://www.patreon.com/posts/olive-roadmap-26853206 
Which looks amazing, especially adding masking and node editing.
  I have just two comments
1- I hope cached playback will not make olive hungry for memory, because one amazing feature of olive is the low memory it consumes and its speed. 
2- Could you consider timeline design to be typeless, by which I mean it is possible to put video or audio in the same track and the video/audio tracks are  not split by default, I believe typeless design is strait forward and makes more sense if node based editing is used. And it makes editing much easier. 

Regards,

**Comment by frink** [comment]
1. Depends very much on caching design. The goal would be to make smart decisions all the way round. However, most video editors DO use beefy machines because this stuff takes a lot of CPU. Most of those machines have a ton of RAM anyway. Even using a couple GIGs of RAM for something like this is no longer considered unreasonable. Olive is not intended to run on IoT... ;-)

**Comment by frink** [comment]
2. Typeless design would probably add confusion rather than clarity. It would also make much of the interoperability stuff that we are discussing 10x more difficult because no other major NLEs or DAWs share this paradigm...

**Comment by AGI-THB** [comment]
I don't see why the developer should waste time on this. 
Implementing functionality just because people are too lazy to adapt to Olive's paradigm ist not only time consuming, it also introduces more complexity / bugs in the software.

16gb of RAM cost about 70 Dollars these days. 
Lots of RAM became affordable, therefore there is no  reason to not make use of it if it speeds up peoples worklflow.

**Comment by DaniSeeh** [comment]
Caching shouldn't bring anything but a performance improvement, regardless of how much RAM you have. I wouldn't worry about it being negative, and it's not like people play intense games or something while they are editing videos, so why not use nearly all RAM available if it is necessary to improve performance? Obviously memory leaks or inefficient usage is one thing, but RAM is meant to be used to improve performance when it can.

I also wonder how much will be cached to a scratch disk and not RAM in the first place.

**Comment by philiplb** [comment]
>     1. Typeless design would probably add confusion rather than clarity. It would also make much of the interoperability stuff that we are discussing 10x more difficult because no other major NLEs or DAWs share this paradigm...

Blender VSE has it. I like it. :)
