### ISSUE TITLE
[Feature Request] Starburst Effect

### ISSUE THREAD

**Issue by emma-15** [olive-editor/olive#984]
Olive should have a starburst effect
# Example Image:
![spin](https://user-images.githubusercontent.com/48891420/58674114-f7694780-8313-11e9-8b6c-5e4af3ca232d.gif)

It should be located at ***Video Effects>>Render>>Starburst***
And the options should look something like this:
![options](https://user-images.githubusercontent.com/48891420/58675945-1a97f500-831c-11e9-9aaa-1d5fd93b2ca7.JPG)

**Comment by musaire** [comment]
If this software is for professionals, I would think a professional would build these gimmick-effects themselves.
 I mean, do these in Fusion from zero, or this specific one - why don't you just rotate an image? Do we really need to have specific effects for rotating any image on video track, cmon guys... Let's make real software! Maybe another effect for rotating 3 lines instead of 2.... Another for rotating a cat and choosing the hair amount in its mustache.
Even the transitions are just simple effect presets keyframed in time - not important for professionals, best transition is just a cut anyway, but opacity fade comes handy and should be easily reachable (like in Sony Vegas for example). 
The best effects are analogue-emulating. Believe me. Analogue, not because that is from our past (well, nostalgia is good as well), but because that is natural and fits in everywhere and it works - it is based on the laws of physics. In the analogue world, there was chemistry and waves reacting to physics and world around us in this universe, not some made-up s**t. 
 It is this way in sound and audio, music production and it is this way in video, movie production!!! We don't need digital abstract stuff!!!  If we have, let's say, haze or mist, let's make it as analogue-looking as possible. In sound, we have tape saturation and analogue EQ, analogue compression, analogue interference. 
So, the most important effects in video are kinds of how film reacts to light - **film emulation**, len's flare emulation, **grain emulation**, any real-world-and-what-is-actually-around-us emulation.
Some of these are really hard to make realistic and true to the original acting - so I wouldn't expect Olive Team to do that profound research in these analogue fields - that is why **supporting external effects by using OFX or alternative is so important**.  
Can you reconsider OFX? Well, it doesn't need to happen in the beginning. I am excited about making the core development correctly, thats the priority.

But Olive has already delivered the utmost essential effects. Blurs and such! :)

(PS:
 BTW. With using CGI, we will not reach the same level of building realism that took place when using puppets. The new terminator movie pales in comparison with T2. Interesting in its own art form though.)

**Comment by sobotka** [comment]
I agree with a majority of what @musaire listed.

>but opacity fade comes handy and should be easily reachable (like in Sony Vegas for example).

Handling the footage properly actually means that even something as simple as a fade behaves radically differently than in something like Vegas, where the footage is handled completely incorrectly.

>Can you reconsider OFX? 

OFX is not managed. At all. That means by adding it, if someone uses an effect, they essentially destroy their data. To understand what sort of destruction can happen, have a look at [this excellent demonstration of scene linear blurring from Nick Shaw](https://twitter.com/nickshaw27/status/1021807238539866113?s=21).

If you care about the excellent imaging that comes from scene linear and proper management, that means that it is up to OFX to sort out its bungled mess.

It just isn’t worth the trade of designing a system from the ground up to maintain a proper pixel management pipeline, only to let crap software libraries destroy it.

**Comment by DaniSeeh** [comment]
Rotating an image with the transform effect doesn't take significantly longer, or perhaps longer at all, and you have finer control over that to begin with. Nodes will allow even tighter control over such effect building. I don't think this is a priority worth keeping in the tracker, but if Matt disagrees then we can reopen.

Glad you are passionate about the software @emma-15, feel free to build the effect yourself for 0.1.0 and add it to the community effects, or wait for nodes to be finished and you could use them to make such an effect that could be copied. I'm sure community effects will eventually adapt to the new Nodes structure too and someone could make one like this if you really don't want to just rotate images to do this effect or if there was some keyframe-able element you wanted.

**Comment by musaire** [comment]
> 
> To understand what sort of destruction can happen, have a look at [this excellent demonstration of scene linear blurring from Nick Shaw](https://twitter.com/nickshaw27/status/1021807238539866113?s=21).
> 

Wow, that 4th defocus actually looks like real in camera defocus, indeed! With the bright saturated parts being "duplicated" in bokeh, instead of "dissolving them down" in brightness and color.
In the past, I've used defocus tools, and just tweaked the settings so that it looks the way I want. But to be honest, my priority would be that color and light would behave naturally in the first place. 
Yes. Over anything else. I'd rather not apply any effects at all.

**Comment by sobotka** [comment]
It’s extremely difficult to communicate many of the upsides of a tightly colour managed pipeline as most people, understandably, think this is about goofy ICC profiles and farting around with minor colour differences.

The good news is that when the image makers _see_ the differences, their responses are generally of the sort you just posted. It requires quite a bit of resolve to get the core basics right, and more to arrive at an audience that appreciates and respects what that means for their own pixels.

It takes a village.
