### ISSUE TITLE
[Bug] Builds are failing on Travis CI

### ISSUE THREAD

**Issue by probonopd** [olive-editor/olive#993]
**Describe the Bug**

Builds are failing on Travis CI. As a result, no continuous AppImages get built and uploaded anymore.

https://github.com/olive-editor/olive/commit/b819a30c01d3d3f8eed4f2befa475f7559ff8731 seemingly broke them on May 4, looking at https://travis-ci.org/olive-editor/olive/builds.

It's best practice to only merge PRs once they build "green".

**Comment by sobotka** [comment]
Travis is taking a backseat to the large core foundation rewrite. It was decided that development will happen in master, and those interested in the pre-alpha previous state can use the 0.1.x tag lineage.

**Comment by probonopd** [comment]
It would be good to have continuous builds of master available so that one can follow development. Anything preventing this from happening?

**Comment by sobotka** [comment]
I don’t think so? The issue would be the unpredictable changes for anyone who tried to massage it into shape. I’m sure @itsmattkc would be open to PRs for it?

**Comment by itsmattkc** [comment]
Not so much that it can't, just that it doesn't seem very important right now. Olive's master is literally unusable right now and making the CI work with the new build structure seems like a low priority. I also don't think there's much to be gained encouraging people to use it (again, literally unusuable).

**Comment by probonopd** [comment]
Fwiw, people seem to have liked the AppImage builds from the "latest and greatest" development branch:
https://twitter.com/probonopd/status/1079154249253179392

**Comment by itsmattkc** [comment]
I appreciate that and the CI will be very likely be fixed soon, but let's not conflate "latest" with "greatest" here - Olive's master is mid-overhaul and, I cannot overstate, broken and unusable at the moment.

Through a lot of Olive's development, it was encouraged to use the master because it was mostly new features and bug fixes which made it relatively safe, but this is different. The internal structure is being completely reworked, and as a consequence, basic functionality like saving/loading is completely broken (any project saved with it right now will be corrupt).

When I say I don't want to encourage people to use the master as-is right now, it's because of things like that - users may think it's still just new features and bug fixes, but it will literally destroy projects made in previous builds if people try to use one and save over it. Yes, the software could warn/disable saving/loading, but this too seems like a low priority when even simple editing is basically impossible in the current master meaning there's little point to testing it at the moment.

But as I say, this should all be fixed eventually.

**Comment by probonopd** [comment]
> let's not conflate "latest" with "greatest" here - Olive's master is mid-overhaul and, I cannot overstate, broken and unusable at the moment

OK, I get it, thanks for the explanation :+1:
