### ISSUE TITLE
[Bug] Current head broken ?

### ISSUE THREAD

**Issue by hzeller** [olive-editor/olive#994]
When compiling from head, the resulting instance seems to be broken, which looks like a result of current refactoring going on.

For instance, when saving things, `<footage>` items are not enclosed in the `<media></media>` tag or `<sequence>` in `<sequences></sequences>`. Or `NodeShader::Create()` factory returns a nullptr.

The last commit is 25 days back, so I am wondering if there is something 'in the pipeline' which would make head work again. I'd like to contribute, but in order to get going from head, I'd have to do some work to even get it running again, but I suspect that is already work in progress by olive team. Is there an ETA when things might start working again from head ?

**Comment by itsmattkc** [comment]
The `notracks` branch is slightly newer, but yes Olive's head is in currently mid-overhaul meaning many things are broken now (hence the tagging off at v0.1.0). Unfortunately I got caught up in another work obligation I agreed to a while ago, which is why development has been slow for the past few weeks, but it should be wrapping up with the next few days so you should see some updates very soon.

**Comment by itsmattkc** [comment]
Current master can be compiled, but it's still recommended to stick to the 0.1.x branch for anything usable.
