### ISSUE TITLE
Olive will not compile

### ISSUE THREAD

**Issue by emma-15** [olive-editor/olive#997]
I am following the **windows** compile instructions from https://olivevideoeditor.org/compile.php#win32
but after I run `make` the error: `make: *** No targets specified and no makefile found.  Stop.` comes up. And I'm stuck there.

**Comment by sobotka** [comment]
I believe those documents are well out of date as Olive switched to `cmake` and removed the `qmake` path.

It shouldn’t be much different. Simply `cmake /path/to/source` from a clean directory, then try the `make` from there.

**Comment by Corruptinator** [comment]
I do believe that the problem is figuring out how CMAKE works, as I'm getting errors on attempting to make the compile pre-process:

```
$ cmake -G "Ninja" ../olive/
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: opengl32
-- Found OpenColorIO: C:/msys64/mingw64/lib/libOpenColorIO.dll.a
CMake Error at C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:15 (message):
  The imported target "Qt5::Gui" references the file

     "C:/building/msys32/mingw64/x86_64-w64-mingw32/lib/libglu32.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:45 (_qt5_Gui_check_file_exists)
  C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:70 (_qt5gui_find_extra_libs)
  C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:212 (include)
  C:/msys64/mingw64/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  CMakeLists.txt:27 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Github/olive-build/CMakeFiles/CMakeOutput.log".

```

I think there may be some missing steps required to get CMAKE to work, though this is from being the Windows User trying to get the compile process to work.

@sobotka, do you know how you got the compiling process to work?

**Comment by Simran-B** [comment]
Even with cmake it is pretty broken, see https://github.com/olive-editor/olive/issues/925

OCIO can be installed with `pacman -S mingw-w64-x86_64-opencolorio` and `cmake -G "Ninja"` should find it afterwards. However, it will still fail:

> The imported target "Qt5::Gui" references the file
>   "C:/building/msys32/mingw64/x86_64-w64-mingw32/lib/libglu32.a"
> but this file does not exist.

This is actually a bug in MSYS2: https://github.com/msys2/MINGW-packages/issues/5253

As a workaround, you can open `C:\msys64\mingw64\lib\cmake\Qt5Gui\Qt5GuiConfigExtras.cmake` and replace `C:/building/msys32/` by `C:/msys64/`. It should be on line 70.

Before:
```
_qt5gui_find_extra_libs(OPENGL "C:/building/msys32/mingw64/x86_64-w64-mingw32/lib/libglu32.a;C:/building/msys32/mingw64/x86_64-w64-mingw32/lib/libopengl32.a;C:/building/msys32/mingw64/x86_64-w64-mingw32/lib/libgdi32.a;C:/building/msys32/mingw64/x86_64-w64-mingw32/lib/libuser32.a" "" "")
```

After:
```
_qt5gui_find_extra_libs(OPENGL "C:/msys64/mingw64/x86_64-w64-mingw32/lib/libglu32.a;C:/msys64/mingw64/x86_64-w64-mingw32/lib/libopengl32.a;C:/msys64/mingw64/x86_64-w64-mingw32/lib/libgdi32.a;C:/msys64/mingw64/x86_64-w64-mingw32/lib/libuser32.a" "" "")
```

This fixed the cmake configuration step for me. Then I started the compilation by running `ninja`, but it failed:

```
[125/190] Building CXX object CMakeFiles/olive-editor.dir/rendering/shadergenerators.cpp.obj
FAILED: CMakeFiles/olive-editor.dir/rendering/shadergenerators.cpp.obj
C:\msys64\mingw64\bin\c++.exe  -DGITHASH=\"d3b00efc\" -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -I. -I../ -Iolive-editor_autogen/include -isystem C:/msys64/mingw64/include/QtCore -isystem C:/msys64/mingw64/share/qt5/mkspecs/win32-g++ -isystem C:/msys64/mingw64/include/QtGui -isystem C:/msys64/mingw64/include/QtWidgets -isystem C:/msys64/mingw64/include/QtMultimedia -isystem C:/msys64/mingw64/include/QtNetwork -isystem C:/msys64/mingw64/include/QtOpenGL -isystem C:/msys64/mingw64/include/QtSvg -Wno-reorder -std=c++11 -MD -MT CMakeFiles/olive-editor.dir/rendering/shadergenerators.cpp.obj -MF CMakeFiles\olive-editor.dir\rendering\shadergenerators.cpp.obj.d -o CMakeFiles/olive-editor.dir/rendering/shadergenerators.cpp.obj -c ../rendering/shadergenerators.cpp
../rendering/shadergenerators.cpp: In function 'QOpenGLShaderProgramPtr olive::shader::SetupOCIO(QOpenGLContext*, GLuint&, OpenColorIO::v1::ConstProcessorRcPtr, bool)':
../rendering/shadergenerators.cpp:157:23: error: 'OpenColorIO::v1::GpuShaderDesc::GpuShaderDesc()' is protected within this context
  157 |   OCIO::GpuShaderDesc shaderDesc;
      |                       ^~~~~~~~~~
In file included from ../rendering/shadergenerators.h:6,
                 from ../rendering/shadergenerators.cpp:1:
C:/msys64/mingw64/include/OpenColorIO/OpenColorIO.h:1429:9: note: declared protected here
 1429 |         GpuShaderDesc();
      |         ^~~~~~~~~~~~~
../rendering/shadergenerators.cpp:157:23: error: cannot declare variable 'shaderDesc' to be of abstract type 'OpenColorIO::v1::GpuShaderDesc'
  157 |   OCIO::GpuShaderDesc shaderDesc;
...
```

**Comment by Corruptinator** [comment]
Wow, this isn't the first time I had to deal with MSYS Bugs...

**Comment by Corruptinator** [comment]
Got the compile to work now. Thank you @Simran-B!

As based on Simran's pointing out the MSYS bug, the build instructions were able to be put together after using:

cmake -G "Ninja" ../olive/
(Instruction Build being put together)
then typing:
`ninja`
afterwards starts the compiling process.

Also, @Simran-B, have you tried deleting the CMakeFiles Folder and the CmakeCache.txt before using CMake? Your error could be the result of corruption in the build process.

**Comment by Simran-B** [comment]
I also installed Doxygen (`pacman -S mingw-w64-x86_64-doxygen`) and its `dot` component through GraphViz (`pacman -S mingw-w64-x86_64-graphviz`), so that it can find everything it looks for. I ran `git reset --hard`, `git checkout master`, `git pull` and `git clean -fdx` to clean up the repo. The `build` directory was a fresh folder, but I keep getting the compile error.

Does it compile for you? Do you use different dependencies, especially OpenColorIO? (From Blender?)

BTW: `cmake --build .` works as well, it invokes Ninja.

**Comment by Corruptinator** [comment]
It was able to compile successfully @Simran-B:

![image](https://user-images.githubusercontent.com/5027750/59339675-7ae24b80-8cb9-11e9-8d0c-0187375e71fa.png)

**Comment by sobotka** [comment]
If you folks have a tidy PR that permits compiling on Windows, I’m sure @itsmattkc would consider it. At the very least, updating the wiki or what not would be great.

**Comment by Simran-B** [comment]
It does not compile on my machine for some reason, therefore I'm a bit hesitant about updating the instructions. It wasn't tested on Linux and macOS either, and the MSYS workaround is kinda nasty.

Is Ninja actually desired (GCC) on Windows, or do we aim for a MSVC solution (.sln)?

**Comment by sobotka** [comment]
The path with the least complexity to a compile is probably the shortest distance between two points, and likely a pretty good choice here?

**Comment by itsmattkc** [comment]
Yes, the compiling process in general has changed from the instructions, but Windows is a particularly tough platform to compile on right now.

@Simran-B is correct, there's currently an erroneously hardcoded path in one of the Qt+CMake headers provided by MSYS2/MinGW64 - out of Olive's control without providing some kind of hacky patch. As he also found, the only OpenColorIO package provided on MSYS2 is the current Git master, whose headers seem to be missing some of the v1 functions that Olive utilizes (unless we're missing something? I haven't explored OCIO's v2 much yet)

You'll need to compile OCIO [from a v1.x package](https://github.com/imageworks/OpenColorIO/releases/tag/v1.1.1), but there are problems here too. OCIO's build process also assumes Windows == MSVC, with no apparent support for MinGW. So either you compile Olive (and its dependencies) with MSVC, or  - like the Qt+CMake error - you need to manually edit the OCIO CMakeFiles to compile on MinGW (usually in the form of changing *most but not all of* the `if (WIN32)` conditionals in the various CMakeLists to `if (WIN32 AND NOT MINGW)`.

These are obviously issues that need addressing at some point, but haven't been a high priority for the timebeing since the current master doesn't have much that's usable in it at the moment ([see here](https://github.com/olive-editor/olive/issues/993#issuecomment-501330780)).

**Comment by Simran-B** [comment]
What would be the downsides of CMake+MSVC?
- No packet manager for the external dependencies (pacman), unless there is a substitute?
- Performance regressions or crashes???
  Are dependencies like ffmpeg problematic in combination with MSVC?
- Microsoft's compiler might require special care in the code, like more explicit data types from what I've seen in other projects, as well as workarounds for quirks and outright bugs. On the other hand, most code uses whatever Qt provides and should therefore be portable and require little to no special treatment (I hope).

The benefits would be:
- no trouble with OCIO
- ability to develop in Visual Studio
- "native" toolchain for Windows (no msys2/mingw)

**Comment by itsmattkc** [comment]
@Simran-B More or less. Olive compiles fine with MSVC - I've actually historically compiled with MSVC on Windows myself because MinGW's GDB performance is garbage (MSVC's CDB is way faster, but also way harder to set up - it's not available in any Visual Studio installers, instead requiring a separate download/install from Windows SDK). In general the easier setup with MSYS2 is why the tutorial (and Windows CI) are written for it rather than MSVC (plus the resulting compiled code is about the same, some even argue GCC's is better than MSVC's). But I have thought switching to MSVC may be a good idea in the long run, especially since strange bugs like these (and the earlier Qt bug @Corruptinator mentioned) keep occurring.

vcpkg is the substitute package manager for that toolchain but I have little experience with it. I know it has less packages compared to MSYS2's pacman (no OCIO at all, though as we know it's not like MSYS2's is actually usable here), which again potentially makes building Olive harder. On Windows, I generally resort to downloading Qt manually from https://qt.io, getting FFmpeg headers and development libs from Zeranoe, and compiling OCIO manually, but these are all cumbersome steps to describe in a tutorial.

**Comment by Simran-B** [comment]
Having to install the entire Windows SDK would suck, but I assume it's optional?

For the time being, I would be fine with anything working. I tried to compile OCIO but ran into several more issues, eventually tried Blender's OCIO (v1.0.9?) but still gives me that "protected in this context" error. Not sure what's wrong, for @Corruptinator it worked. I consider to try it under Linux instead.

**Comment by Corruptinator** [comment]
Now I'm back to square one again, had to reinstall MSYS to fix the Pacman.exe not found. Followed all the steps, and OpenGL is now missing once again:

```
$ cmake -G "Ninja" ../olive/
-- The CXX compiler identification is GNU 9.1.0
System is unknown to cmake, create:
Platform/MINGW64_NT-10.0-17134 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Check for working CXX compiler: /mingw64/bin/CC.exe
System is unknown to cmake, create:
Platform/MINGW64_NT-10.0-17134 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Check for working CXX compiler: /mingw64/bin/CC.exe -- works
-- Detecting CXX compiler ABI info
System is unknown to cmake, create:
Platform/MINGW64_NT-10.0-17134 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
System is unknown to cmake, create:
Platform/MINGW64_NT-10.0-17134 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
System is unknown to cmake, create:
Platform/MINGW64_NT-10.0-17134 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
System is unknown to cmake, create:
Platform/MINGW64_NT-10.0-17134 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
System is unknown to cmake, create:
Platform/MINGW64_NT-10.0-17134 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
System is unknown to cmake, create:
Platform/MINGW64_NT-10.0-17134 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.14.5/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
  OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.14.5/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.14.5/Modules/FindOpenGL.cmake:397 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:23 (find_package)


-- Configuring incomplete, errors occurred!
See also "/c/Github/olive-build/CMakeFiles/CMakeOutput.log".
```

Aside the "System is unknown to cmake, create:" warning message that repeats, Its now looking for OpenGL.

**Comment by Simran-B** [comment]
I ran into the same issue of "unknown system" and "could not find OpenGL" when I had renamed my original msys installation folder and reinstalled all packages needed for Olive. Not sure what went wrong there. I gave up on msys/pacman/ninja and went with Visual Studio 16 2019 as generator and worked around several CMake path finding issues by specifying the ones it would be reluctant to find by hand in the CMake GUI.
